//
//  french.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-12.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let french = [
    "person"    :    "la personne"    ,
    "bicycle"    :    "vélo"    ,
    "car"    :    "voiture"    ,
    "motorcycle"    :    "moto"    ,
    "bird"    :    "oiseau"    ,
    "cat"    :    "chat"    ,
    "dog"    :    "chien"    ,
    "horse"    :    "cheval"    ,
    "sheep"    :    "mouton"    ,
    "bottle"    :    "bouteille"    ,
    "chair"    :    "chaise"    ,
    "couch"    :    "canapé"    ,
    "potted plant"    :    "plante en pot"    ,
    "tv"    :    "la télé"    ,
    "cow"    :    "vache"    ,
    "airplane"    :    "avion"    ,
    "hat"    :    "chapeau"    ,
    "license plate"    :    "plaque d'immatriculation"    ,
    "bed"    :    "lit"    ,
    "laptop"    :    "portable"    ,
    "fridge"    :    "frigo"    ,
    "microwave"    :    "four micro onde"    ,
    "sink"    :    "évier"    ,
    "oven"    :    "four"    ,
    "toaster"    :    "toaster"    ,
    "bus"    :    "autobus"    ,
    "train"    :    "train"    ,
    "mirror"    :    "miroir"    ,
    "dining table"    :    "table à manger"    ,
    "elephant"    :    "l'éléphant"    ,
    "banana"    :    "banane"    ,
    "bread"    :    "pain"    ,
    "toilet"    :    "toilette"    ,
    "book"    :    "livre"    ,
    "boat"    :    "bateau"    ,
    "plate"    :    "assiette"    ,
    "cellphone"    :    "téléphone portable"    ,
    "mouse"    :    "Souris"    ,
    "remote"    :    "éloigné"    ,
    "clock"    :    "l'horloge"    ,
    "face"    :    "visage"    ,
    "hand"    :    "main"    ,
    "apple"    :    "Pomme"    ,
    "keyboard"    :    "clavier"    ,
    "backpack"    :    "sac à dos"    ,
    "steering wheel"    :    "volant"    ,
    "wineglass"    :    "verre de vin"    ,
    "chicken"    :    "poulet"    ,
    "zebra"    :    "zèbre"    ,
    "shoe"    :    "chaussure"    ,
    "eye"    :    "œil"    ,
    "mouth"    :    "bouche"    ,
    "scissors"    :    "les ciseaux"    ,
    "truck"    :    "un camion"    ,
    "traffic light"    :    "feu de circulation"    ,
    "eyeglasses"    :    "lunettes"    ,
    "cup"    :    "Coupe"    ,
    "blender"    :    "mixeur"    ,
    "hairdrier"    :    "sèche cheveux"    ,
    "wheel"    :    "roue"    ,
    "streetsign"    :    "Panneau de signalisation"    ,
    "umbrella"    :    "parapluie"    ,
    "door"    :    "porte"    ,
    "firehydrant"    :    "incendie"    ,
    "bowl"    :    "bol"    ,
    "teapot"    :    "théière"    ,
    "fork"    :    "fourchette"    ,
    "knife"    :    "couteau"    ,
    "spoon"    :    "cuillère"    ,
    "bear"    :    "ours"    ,
    "headlights"    :    "phares"    ,
    "window"    :    "fenêtre"    ,
    "desk"    :    "bureau"    ,
    "computer"    :    "ordinateur"    ,
    "refrigerator"    :    "réfrigérateur"    ,
    "pizza"    :    "Pizza"    ,
    "squirrel"    :    "écureuil"    ,
    "duck"    :    "canard"    ,
    "frisbee"    :    "frisbee"    ,
    "guitar"    :    "guitare"    ,
    "nose"    :    "nez"    ,
    "teddybear"    :    "ours en peluche"    ,
    "tie"    :    "attacher"    ,
    "stopsign"    :    "panneau stop"    ,
    "surfboard"    :    "planche de surf"    ,
    "sandwich"    :    "sandwich"    ,
    "pen/pencil"    :    "stylo / crayon"    ,
    "kite"    :    "cerf-volant"    ,
    "orange"    :    "Orange"    ,
    "toothbrush"    :    "brosse à dents"    ,
    "printer"    :    "imprimante"    ,
    "pans"    :    "des casseroles"    ,
    "head"    :    "tête"    ,
    "sports ball"    :    "ballon de sport"    ,
    "broccoli"    :    "brocoli"    ,
    "suitcase"    :    "valise"    ,
    "carrot"    :    "carotte"    ,
    "chandelier"    :    "lustre"    ,
    "parking meter"    :    "parcmètre"    ,
    "fish"    :    "poisson"    ,
    "handbag"    :    "Sac à main"    ,
    "hotdog"    :    "Hot-dog"    ,
    "stapler"    :    "agrafeuse"    ,
    "basketball hoop"    :    "panier de basket"    ,
    "donut"    :    "beignet"    ,
    "vase"    :    "vase"    ,
    "baseball bat"    :    "batte de baseball"    ,
    "baseball glove"    :    "gant de baseball"    ,
    "giraffe"    :    "girafe"    ,
    "jacket"    :    "veste"    ,
    "skis"    :    "des skis"    ,
    "snowboard"    :    "snowboard"    ,
    "tablelamp"    :    "lampe de table"    ,
    "egg"    :    "Oeuf"    ,
    "door handle"    :    "poignée de porte"    ,
    "power outlet"    :    "prise de courant"    ,
    "hair"    :    "cheveux"    ,
    "tiger"    :    "tigre"    ,
    "table"    :    "table"    ,
    "coffee table"    :    "table basse"    ,
    "skate board"    :    "planche à roulette"    ,
    "helicopter"    :    "hélicoptère"    ,
    "tomato"    :    "tomate"    ,
    "tree"    :    "arbre"    ,
    "bunny"    :    "lapin"    ,
    "pillow"    :    "oreiller"    ,
    "tennis racket"    :    "raquette de tennis"    ,
    "cake"    :    "gâteau"    ,
    "feet"    :    "pieds"    ,
    "bench"    :    "banc"    ,
    "chopping board"    :    "planche à découper"    ,
    "washer"    :    "machine à laver"    ,
    "lion"    :    "Lion"    ,
    "monkey"    :    "singe"    ,
    "hairbrush"    :    "brosse à cheveux"    ,
    "light switch"    :    "interrupteur"    ,
    "arms"    :    "bras"    ,
    "legs"    :    "jambes"    ,
    "house"    :    "maison"    ,
    "cheese"    :    "fromage"    ,
    "goat"    :    "chèvre"    ,
    "magazine"    :    "magazine"    ,
    "key"    :    "clé"    ,
    "picture"    :    "image"    ,
    "frame"    :    "Cadre"    ,
    "cupcake"    :    "cupcake"    ,
    "fan(ceil/floor)"    :    "ventilateur (plafond / plancher)"    ,
    "frogs"    :    "grenouilles"    ,
    "rabbit"    :    "lapin"    ,
    "owl"    :    "hibou"    ,
    "scarf"    :    "écharpe"    ,
    "ears"    :    "oreilles"    ,
    "homephone"    :    "téléphone fixe"    ,
    "pig"    :    "porc"    ,
    "strawberries"    :    "des fraises"    ,
    "pumpkin"    :    "citrouille"    ,
    "van"    :    "van"    ,
    "kangaroo"    :    "kangourou"    ,
    "rhinoceros"    :    "rhinocéros"    ,
    "sailboat"    :    "voilier"    ,
    "deer"    :    "cerf"    ,
    "playing cards"    :    "jouer aux cartes"    ,
    "towel"    :    "serviette"    ,
    "hyppo hyppo"    :    "hyppo hyppo"    ,
    "can"    :    "pouvez"    ,
    "dollar bill"    :    "billet d'un dollar"    ,
    "doll"    :    "poupée"    ,
    "soup"    :    "soupe"    ,
    "meat"    :    "moi à"    ,
    "muffins"    :    "muffins"    ,
    "tire"    :    "pneu"    ,
    "necklace"    :    "Collier"    ,
    "tablet"    :    "tablette"    ,
    "corn"    :    "blé"    ,
    "ladder"    :    "échelle"    ,
    "pineapple"    :    "ananas"    ,
    "candle"    :    "bougie"    ,
    "desktop"    :    "bureau"    ,
    "carpet"    :    "tapis"    ,
    "cookie"    :    "biscuit"    ,
    "toycars"    :    "voitures de jouet"    ,
    "bracelet"    :    "bracelet"    ,
    "bat"    :    "chauve souris"    ,
    "balloon"    :    "ballon"    ,
    "gloves"    :    "gants"    ,
    "milk"    :    "Lait"    ,
    "pants"    :    "un pantalon"    ,
    "wheelchair"    :    "fauteuil roulant"    ,
    "building"    :    "bâtiment"    ,
    "bacon"    :    "Bacon"    ,
    "box"    :    "boîte"    ,
    "platypus"    :    "ornithorynque"    ,
    "pancake"    :    "crêpe"    ,
    "cabinet"    :    "cabinet"    ,
    "whale"    :    "baleine"    ,
    "dryer"    :    "séchoir"    ,
    "torso"    :    "torse"    ,
    "lizard"    :    "lézard"    ,
    "shirt"    :    "chemise"    ,
    "shorts"    :    "short"    ,
    "pasta"    :    "Pâtes"    ,
    "grapes"    :    "les raisins"    ,
    "shark"    :    "requin"    ,
    "swan"    :    "cygne"    ,
    "fingers"    :    "des doigts"    ,
    "sidetable"    :    "sidetable"    ,
    "gate"    :    "porte"    ,
    "beans"    :    "des haricots"    ,
    "flip flops"    :    "tongs"    ,
    "moon"    :    "lune"    ,
    "road/street/"    :    "route / rue /"    ,
    "fountain"    :    "Fontaine"    ,
    "faxmachine"    :    "faxmachine"    ,
    "hotair balloon"    :    "montgolfière"    ,
    "cereal"    :    "céréale"    ,
    "seahorse"    :    "hippocampe"    ,
    "rocket"    :    "fusée"    ,
    "cabinets"    :    "armoires"    ,
    "basketball"    :    "basketball"    ,
    "telephone"    :    "Téléphone"    ,
    "movie(disc)"    :    "film (disque)"    ,
    "football"    :    "Football"    ,
    "goose"    :    "oie"    ,
    "long-sleeve shirt"    :    "chemise à manches longues"    ,
    "short-sleeve shirt"    :    "chemise à manches courtes"    ,
    "raft"    :    "radeau"    ,
    "rooster"    :    "coq"    ,
    "copier"    :    "photocopieuse"    ,
    "radio"    :    "radio"    ,
    "fences"    :    "clôtures"    ,
    "goalnet"    :    "goalnet"    ,
    "toys"    :    "jouets"    ,
    "engine"    :    "moteur"    ,
    "soccerball"    :    "ballon de football"    ,
    "fieldgoal posts"    :    "messages fieldgoal"    ,
    "socks"    :    "chaussettes"    ,
    "tennisnet"    :    "tennisnet"    ,
    "seats"    :    "des places"    ,
    "elbows"    :    "coudes"    ,
    "aardvark"    :    "Aardvark"    ,
    "dinosaur"    :    "dinosaure"    ,
    "unicycle"    :    "monocycle"    ,
    "honey"    :    "mon chéri"    ,
    "legos"    :    "legos"    ,
    "fly"    :    "mouche"    ,
    "roof"    :    "toit"    ,
    "baseball"    :    "base-ball"    ,
    "mat"    :    "tapis"    ,
    "ipad"    :    "ipad"    ,
    "iphone"    :    "iphone"    ,
    "hoop"    :    "cerceau"    ,
    "hen"    :    "poule"    ,
    "back"    :    "arrière"    ,
    "table cloth"    :    "nappe de table"    ,
    "soccer nets"    :    "filets de football"    ,
    "turkey"    :    "dinde"    ,
    "pajamas"    :    "pyjamas"    ,
    "underpants"    :    "slip"    ,
    "goldfish"    :    "poisson rouge"    ,
    "robot"    :    "robot"    ,
    "crusher"    :    "broyeur"    ,
    "animal crackers"    :    "craquelins d'animaux"    ,
    "basketball court"    :    "terrain de basketball"    ,
    "horn"    :    "klaxon"    ,
    "firefly"    :    "luciole"    ,
    "armpits"    :    "aisselles"    ,
    "nectar"    :    "nectar"    ,
    "superhero costume"    :    "costume de super-héros"    ,
    "jetpack"    :    "jetpack"    ,
    "robots"    :    "des robots"
]
