//
//  french.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-12.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let french = [
        "kit fox"    :    "kit fox"    ,
        "English setter"    :    "Setter anglais"    ,
        "Australian terrier"    :    "Terrier australien"    ,
        "grey whale"    :    "baleine grise"    ,
        "lesser panda"    :    "petit panda"    ,
        "Egyptian cat"    :    "Chat Ègyptien"    ,
        "ibex"    :    "ibex"    ,
        "Persian cat†"    :    "chat persan"    ,
        "cougar"    :    "puma"    ,
        "gazelle†"    :    "gazelle"    ,
        "porcupine"    :    "porc-Èpic"    ,
        "sea lion†"    :    "Lion de mer"    ,
        "badger†"    :    "blaireau"    ,
        "Great Dane†"    :    "Grand danois"    ,
        "Scottish deerhound"    :    "Daim Ècossais"    ,
        "killer whale"    :    "orque"    ,
        "mink†"    :    "vison"    ,
        "African elephant"    :    "…lÈphant d'Afrique"    ,
        "red wolf"    :    "Loup rouge"    ,
        "jaguar"    :    "jaguar"    ,
        "hyena"    :    "hyËne"    ,
        "titi"    :    "titi"    ,
        "three-toed sloth"    :    "paresseux ‡ trois doigts"    ,
        "sorrel†"    :    "oseille"    ,
        "black-footed ferret"    :    "furet ‡ pieds noirs"    ,
        "dalmatian"    :    "dalmatien"    ,
        "Staffordshire bullterrier"    :    "Staffordshire Bullterrier"    ,
        "Bouvier des Flandres"    :    "Bouvier des Flandres"    ,
        "weasel†"    :    "belette"    ,
        "miniature poodle†"    :    "caniche miniature"    ,
        "bighorn"    :    "Grosse corne"    ,
        "fox squirrel"    :    "Ècureuil de renard"    ,
        "colobus"    :    "colobus"    ,
        "tiger cat†"    :    "chat tigre"    ,
        "impala"    :    "impala"    ,
        "coyote"    :    "coyote"    ,
        "Yorkshire terrier†"    :    "Yorkshire Terrier"    ,
        "Newfoundland"    :    "Terre Neuve"    ,
        "red fox"    :    "Renard rouge"    ,
        "hartebeest†"    :    "bubale"    ,
        "grey fox"    :    "renard gris"    ,
        "Pekinese"    :    "pÈkinois"    ,
        "guenon"    :    "guenon"    ,
        "mongoose†"    :    "mangouste"    ,
        "indri"    :    "indri"    ,
        "tiger"    :    "tigre"    ,
        "wild boar"    :    "sanglier"    ,
        "zebra†"    :    "zËbre"    ,
        "ram"    :    "RAM"    ,
        "orangutan"    :    "orang-outan"    ,
        "basenji†"    :    "basenji"    ,
        "leopard"    :    "lÈopard"    ,
        "vizsla"    :    "vizsla"    ,
        "squirrel monkey"    :    "Ècureuil singe"    ,
        "Siamese cat"    :    "chat siamois"    ,
        "chimpanzee"    :    "chimpanzÈ"    ,
        "komondor†"    :    "komondor"    ,
        "proboscis monkey"    :    "Singe proboscis"    ,
        "guinea pig"    :    "Cochon d'Inde"    ,
        "white wolf"    :    "Loup blanc"    ,
        "ice bear"    :    "ours polaire"    ,
        "gorilla"    :    "gorille"    ,
        "ox†"    :    "búuf"    ,
        "Tibetan mastiff†"    :    "Mastiff tibÈtain"    ,
        "spider monkey"    :    "singe araignÈe"    ,
        "Doberman"    :    "Doberman"    ,
        "warthog†"    :    "phacochËre"    ,
        "Arabian camel"    :    "Chameau arabe"    ,
        "siamang"    :    "siamang"    ,
        "golden retriever†"    :    "Golden retriever"    ,
        "Border collie†"    :    "Border collie"    ,
        "hare†"    :    "liËvre"    ,
        "boxer†"    :    "boxeur"    ,
        "patas"    :    "patas"    ,
        "baboon†"    :    "babouin"    ,
        "macaque†"    :    "macaque"    ,
        "capuchin"    :    "capucin"    ,
        "flat-coated retriever†"    :    "retriever ‡ revÍtement plat"    ,
        "hog"    :    "porc"    ,
        "Eskimo dog"    :    "Chien esquimau"    ,
        "Brittany spaniel†"    :    "Epagneul breton"    ,
        "dial telephone"    :    "tÈlÈphone"    ,
        "maze"    :    "Labyrinthe"    ,
        "Gordon setter†"    :    "Gordon setter"    ,
        "dingo"    :    "dingo"    ,
        "hamster†"    :    "hamster"    ,
        "Arctic fox"    :    "le renard arctique"    ,
        "water buffalo"    :    "buffles d'eau"    ,
        "American black bear"    :    "Ours noir amÈricain"    ,
        "Angora"    :    "Angora"    ,
        "bison†"    :    "bison"    ,
        "howler monkey"    :    "singe hurleur"    ,
        "hippopotamus"    :    "hippopotame"    ,
        "giant panda"    :    "Panda gÈant"    ,
        "tabby"    :    "tigrÈ"    ,
        "marmoset†"    :    "ouistiti"    ,
        "Saint Bernard"    :    "Saint-Bernard"    ,
        "armadillo†"    :    "tatou"    ,
        "redbone†"    :    "redbone"    ,
        "polecat"    :    "putois"    ,
        "marmot†"    :    "marmotte"    ,
        "gibbon"    :    "gibbon"    ,
        "llama†"    :    "lama"    ,
        "wood rabbit"    :    "lapin de bois"    ,
        "lion"    :    "Lion"    ,
        "Irish setter"    :    "Setter irlandais"    ,
        "dugong"    :    "dugong"    ,
        "Indian elephant"    :    "…lÈphant indien"    ,
        "beaver†"    :    "castor"    ,
        "Madagascar cat"    :    "Chat de Madagascar"    ,
        "Rhodesian ridgeback†"    :    "Ridgeback rhodÈsien"    ,
        "lynx"    :    "Lynx"    ,
        "African hunting dog"    :    "Chien de chasse africain"    ,
        "langur†"    :    "langur"    ,
        "timber wolf"    :    "loup de bois"    ,
        "cheetah"    :    "guÈpard"    ,
        "sloth bear"    :    "ours paresseux"    ,
        "German shepherd"    :    "Berger allemand"    ,
        "otter†"    :    "loutre"    ,
        "koala"    :    "koala"    ,
        "tusker†"    :    "tusker"    ,
        "echidna"    :    "echidna"    ,
        "wallaby"    :    "wallaby"    ,
        "platypus"    :    "ornithorynque"    ,
        "wombat†"    :    "wombat"    ,
        "revolver"    :    "revolver"    ,
        "umbrella†"    :    "parapluie"    ,
        "schooner†"    :    "goÈlette"    ,
        "soccer ball†"    :    "ballon de football"    ,
        "accordion"    :    "accordÈon"    ,
        "ant"    :    "fourmi"    ,
        "starfish"    :    "Ètoile de mer"    ,
        "chambered nautilus"    :    "Nautilus chambrÈ"    ,
        "grand piano"    :    "grand piano"    ,
        "laptop"    :    "portable"    ,
        "strawberry†"    :    "fraise"    ,
        "airliner†"    :    "avion de ligne"    ,
        "warplane"    :    "avion de combat"    ,
        "airship"    :    "dirigeable"    ,
        "balloon†"    :    "ballon"    ,
        "space shuttle†"    :    "navette spatiale"    ,
        "fireboat†"    :    "bateau-pompe"    ,
        "gondola†"    :    "gondole"    ,
        "speedboat†"    :    "vedette"    ,
        "lifeboat†"    :    "canot de sauvetage"    ,
        "canoe†"    :    "canoÎ"    ,
        "yawl†"    :    "yawl"    ,
        "catamaran†"    :    "catamaran"    ,
        "trimaran†"    :    "trimaran"    ,
        "container ship"    :    "porte-conteneurs"    ,
        "liner"    :    "doublure"    ,
        "pirate"    :    "pirate"    ,
        "aircraft carrier"    :    "porte-avions"    ,
        "submarine"    :    "sous-marin"    ,
        "wreck†"    :    "Èpave"    ,
        "half track†"    :    "¿ mi-parcours"    ,
        "tank"    :    "rÈservoir"    ,
        "missile†"    :    "missile"    ,
        "bobsled"    :    "bobslevel"    ,
        "dogsled"    :    "traÓneau ‡ chiens"    ,
        "bicycle-built-for-two"    :    "vÈlo-construit-pour-deux"    ,
        "mountain bike"    :    "vÈlo de montagne"    ,
        "freight car†"    :    "wagon ‡ marchandises"    ,
        "passenger car"    :    "voiture de voyageurs"    ,
        "barrow"    :    "brouette"    ,
        "shopping cart†"    :    "chariot"    ,
        "motor scooter"    :    "moteur scooter"    ,
        "forklift†"    :    "chariot ÈlÈvateur"    ,
        "electric locomotive†"    :    "locomotive Èlectrique"    ,
        "steam locomotive†"    :    "locomotive ‡ vapeur"    ,
        "amphibian"    :    "amphibie"    ,
        "ambulance†"    :    "ambulance"    ,
        "beach wagon"    :    "wagon de plage"    ,
        "cab"    :    "taxi"    ,
        "convertible†"    :    "convertible"    ,
        "jeep"    :    "jeep"    ,
        "limousine"    :    "limousine"    ,
        "minivan†"    :    "monospace"    ,
        "Model T†"    :    "ModËle T"    ,
        "racer"    :    "coureur"    ,
        "sports car"    :    "voiture de sport"    ,
        "go-kart†"    :    "go-kart"    ,
        "golfcart"    :    "voiturette de golf"    ,
        "moped†"    :    "vÈlomoteur"    ,
        "snowplow"    :    "chasse-neige"    ,
        "fire engine"    :    "camion de pompier"    ,
        "garbage truck"    :    "camion ‡ ordures"    ,
        "pickup"    :    "ramasser"    ,
        "tow truck"    :    "dÈpanneuse"    ,
        "trailer truck"    :    "camion de remorque"    ,
        "moving van†"    :    "Camion de dÈmÈnagement"    ,
        "police van"    :    "fourgon"    ,
        "recreational vehicle"    :    "vÈhicule rÈcrÈatif"    ,
        "streetcar"    :    "tramway"    ,
        "snowmobile†"    :    "motoneige"    ,
        "tractor†"    :    "tracteur"    ,
        "mobile home"    :    "maison mobile"    ,
        "tricycle"    :    "tricycle"    ,
        "unicycle"    :    "monocycle"    ,
        "horse cart"    :    "char ‡ cheval"    ,
        "mosquito net†"    :    "moustiquaire"    ,
        "oxcart†"    :    "char ‡ búufs"    ,
        "bassinet†"    :    "berceau"    ,
        "cradle†"    :    "berceau"    ,
        "crib"    :    "lit de bÈbÈ"    ,
        "four-poster†"    :    "quatre affiches"    ,
        "bookcase†"    :    "bibliothËque"    ,
        "china cabinet"    :    "armoire de porcelaine"    ,
        "medicine chest"    :    "coffre de mÈdecine"    ,
        "chiffonier"    :    "chiffonnier"    ,
        "table lamp†"    :    "lampe de table"    ,
        "file"    :    "fichier"    ,
        "pay-phone"    :    "tÈlÈphone payant"    ,
        "park bench†"    :    "banc de parc"    ,
        "barber chair†"    :    "chaise de coiffeur"    ,
        "throne†"    :    "trÙne"    ,
        "folding chair†"    :    "chaise pliante"    ,
        "rocking chair"    :    "fauteuil ‡ bascule"    ,
        "studio couch"    :    "canapÈ-studio"    ,
        "toilet seat†"    :    "siËge de toilette"    ,
        "desk†"    :    "bureau"    ,
        "pool table"    :    "table de billard"    ,
        "dining table"    :    "table ‡ manger"    ,
        "entertainment center†"    :    "centre de divertissement"    ,
        "wardrobe"    :    "garde-robe"    ,
        "Granny Smith†"    :    "Granny Smith"    ,
        "orange†"    :    "Orange"    ,
        "lemon†"    :    "citron"    ,
        "fig†"    :    "figue"    ,
        "pineapple"    :    "ananas"    ,
        "banana†"    :    "banane"    ,
        "jackfruit"    :    "jacquier"    ,
        "custard apple†"    :    "pomme custard"    ,
        "pomegranate†"    :    "Grenade"    ,
        "acorn†"    :    "gland"    ,
        "hip"    :    "hanche"    ,
        "ear"    :    "oreille"    ,
        "rapeseed†"    :    "colza"    ,
        "corn†"    :    "blÈ"    ,
        "buckeye"    :    "Buckeye"    ,
        "organ"    :    "organe"    ,
        "upright"    :    "droit"    ,
        "chime"    :    "carillon"    ,
        "drum"    :    "tambour"    ,
        "gong"    :    "gong"    ,
        "maraca†"    :    "maraca"    ,
        "marimba"    :    "marimba"    ,
        "steel drum†"    :    "tonneau en acier"    ,
        "banjo†"    :    "banjo"    ,
        "cello"    :    "violoncelle"    ,
        "lampshade"    :    "abat-jour"    ,
        "harp†"    :    "harpe"    ,
        "acoustic guitar†"    :    "guitare acoustique"    ,
        "electric guitar†"    :    "guitare Èlectrique"    ,
        "cornet"    :    "cornet"    ,
        "French horn"    :    "cor franÁais"    ,
        "trombone†"    :    "trombone"    ,
        "harmonica"    :    "harmonica"    ,
        "ocarina"    :    "ocarina"    ,
        "panpipe"    :    "panpipe"    ,
        "bassoon†"    :    "basson"    ,
        "sax"    :    "saxo"    ,
        "flute"    :    "fl˚te"    ,
        "daisy†"    :    "Marguerite"    ,
        "yellow lady's slipper"    :    "pantoufle de dame jaune"    ,
        "cliff"    :    "falaise"    ,
        "valley"    :    "vallÈe"    ,
        "alp†"    :    "alp"    ,
        "volcano†"    :    "volcan"    ,
        "promontory"    :    "promontoire"    ,
        "sandbar"    :    "barre de sable"    ,
        "coral reef†"    :    "rÈcif de corail"    ,
        "lakeside"    :    "bord du lac"    ,
        "seashore"    :    "rivage"    ,
        "geyser†"    :    "geyser"    ,
        "hatchet†"    :    "hachette"    ,
        "cleaver"    :    "couperet"    ,
        "letter opener"    :    "ouvre-lettre"    ,
        "plane"    :    "avion"    ,
        "power drill†"    :    "perceuse Èlectrique"    ,
        "lawn mower"    :    "tondeuse ‡ gazon"    ,
        "hammer†"    :    "marteau"    ,
        "corkscrew"    :    "un tire-bouchon"    ,
        "can opener"    :    "ouvre-boÓte"    ,
        "plunger"    :    "piston"    ,
        "screwdriver†"    :    "Tournevis"    ,
        "shovel†"    :    "pelle"    ,
        "plow"    :    "charrue"    ,
        "chain saw"    :    "tronÁonneuse"    ,
        "cock†"    :    "coq"    ,
        "hen†"    :    "poule"    ,
        "ostrich"    :    "autruche"    ,
        "brambling"    :    "brouillage"    ,
        "goldfinch"    :    "chardonneret"    ,
        "house finch"    :    "maison finch"    ,
        "junco"    :    "junco"    ,
        "indigo bunting"    :    "Bruant indigo"    ,
        "robin"    :    "Robin"    ,
        "bulbul†"    :    "bulbul"    ,
        "jay†"    :    "geai"    ,
        "magpie†"    :    "pie"    ,
        "chickadee†"    :    "mÈsange"    ,
        "water ouzel"    :    "eau ouzel"    ,
        "kite†"    :    "cerf-volant"    ,
        "bald eagle"    :    "Aigle chauve"    ,
        "vulture†"    :    "vautour"    ,
        "great grey owl"    :    "grand hibou gris"    ,
        "black grouse†"    :    "Grouse noire"    ,
        "ptarmigan†"    :    "lagopËde"    ,
        "ruffed grouse"    :    "gÈlinotte huppÈe"    ,
        "prairie chicken"    :    "poulet de prairie"    ,
        "peacock†"    :    "paon"    ,
        "quail†"    :    "Caille"    ,
        "partridge†"    :    "perdrix"    ,
        "African grey"    :    "Gris africain"    ,
        "macaw†"    :    "ara"    ,
        "sulphur-crested cockatoo"    :    "cacatoËs ‡ huppe"    ,
        "lorikeet†"    :    "lorikeet"    ,
        "coucal†"    :    "coucal"    ,
        "bee eater†"    :    "mangeur d'abeilles"    ,
        "hornbill†"    :    "calao"    ,
        "hummingbird†"    :    "colibri"    ,
        "jacamar†"    :    "Jacamar"    ,
        "toucan†"    :    "toucan"    ,
        "drake†"    :    "canard"    ,
        "red-breasted merganser"    :    "hargneux ‡ poitrine rouge"    ,
        "goose†"    :    "oie"    ,
        "black swan"    :    "cygne noir"    ,
        "white stork"    :    "cigogne blanche"    ,
        "black stork"    :    "cigogne noire"    ,
        "spoonbill†"    :    "spatule"    ,
        "flamingo†"    :    "flamant"    ,
        "American egret"    :    "Aigrette amÈricaine"    ,
        "little blue heron"    :    "petit hÈron bleu"    ,
        "bittern†"    :    "butor"    ,
        "limpkin"    :    "limpkin"    ,
        "American coot"    :    "Coq d'AmÈrique"    ,
        "bustard†"    :    "outarde"    ,
        "ruddy turnstone"    :    "tourmente rouge"    ,
        "red-backed sandpiper"    :    "BÈcasseau ‡ dos roux"    ,
        "redshank"    :    "le chancre"    ,
        "dowitcher†"    :    "dowitcher"    ,
        "oystercatcher"    :    "huÓtrier"    ,
        "European gallinule"    :    "Gallinule europÈenne"    ,
        "pelican†"    :    "pÈlican"    ,
        "king penguin"    :    "roi pingouin"    ,
        "albatross"    :    "albatros"    ,
        "great white shark"    :    "grand requin blanc"    ,
        "tiger shark"    :    "requin tigre"    ,
        "hammerhead"    :    "marteau"    ,
        "electric ray"    :    "rayon Èlectrique"    ,
        "stingray†"    :    "Stingray"    ,
        "barracouta"    :    "barracouta"    ,
        "coho"    :    "coho"    ,
        "tench"    :    "tanche"    ,
        "goldfish"    :    "poisson rouge"    ,
        "eel†"    :    "anguille"    ,
        "rock beauty"    :    "beautÈ du rock"    ,
        "anemone fish†"    :    "poisson anÈmone"    ,
        "lionfish†"    :    "lionfish"    ,
        "puffer"    :    "puffer"    ,
        "sturgeon†"    :    "esturgeon"    ,
        "gar"    :    "gar"    ,
        "loggerhead"    :    "calËche"    ,
        "mud turtle†"    :    "tortue de boue"    ,
        "terrapin†"    :    "terrapin"    ,
        "box turtle"    :    "tortue-boÓte"    ,
        "banded gecko†"    :    "gecko ‡ bandes"    ,
        "common iguana"    :    "iguane commun"    ,
        "American chameleon"    :    "CamÈlÈon amÈricain"    ,
        "whiptail"    :    "whiptail"    ,
        "agama†"    :    "Agama"    ,
        "frilled lizard"    :    "lÈzard ‡ collerette"    ,
        "alligator lizard†"    :    "lÈzard d'alligator"    ,
        "Gila monster"    :    "Gila monstre"    ,
        "green lizard"    :    "lÈzard vert"    ,
        "African chameleon"    :    "CamÈlÈon africain"    ,
        "Komodo dragon"    :    "Dragon de Komodo"    ,
        "triceratops†"    :    "tricÈratops"    ,
        "African crocodile"    :    "Crocodile africain"    ,
        "American alligator"    :    "Alligator amÈricain"    ,
        "thunder snake"    :    "serpent du tonnerre"    ,
        "ringneck snake"    :    "serpent ringneck"    ,
        "hognose snake"    :    "serpent hognose"    ,
        "green snake"    :    "serpent vert"    ,
        "king snake"    :    "Roi serpent"    ,
        "garter snake"    :    "couleuvre"    ,
        "water snake†"    :    "serpent d'eau"    ,
        "vine snake†"    :    "serpent de vigne"    ,
        "night snake"    :    "serpent de nuit"    ,
        "boa constrictor"    :    "Boa constrictor"    ,
        "rock python"    :    "python de roche"    ,
        "Indian cobra"    :    "Cobra indien"    ,
        "green mamba†"    :    "mamba vert"    ,
        "sea snake†"    :    "serpent de mer"    ,
        "horned viper"    :    "vipËre cornue"    ,
        "stone wall†"    :    "mur de pierre"    ,
        "sidewinder"    :    "sidewinder"    ,
        "European fire salamander"    :    "Salamandre de feu europÈenne"    ,
        "common newt"    :    "triton commun"    ,
        "eft†"    :    "Eft"    ,
        "spotted salamander"    :    "salamandre tachetÈe"    ,
        "axolotl"    :    "axolotl"    ,
        "bullfrog"    :    "ouaouaron"    ,
        "tree frog"    :    "rainette"    ,
        "tailed frog"    :    "grenouille ‡ queue"    ,
        "whistle†"    :    "sifflet"    ,
        "wing†"    :    "aile"    ,
        "paintbrush†"    :    "pinceau"    ,
        "oxygen mask†"    :    "masque d'oxygËne"    ,
        "snorkel†"    :    "tuba"    ,
        "loudspeaker"    :    "haut-parleur"    ,
        "microphone"    :    "microphone"    ,
        "screen"    :    "Ècran"    ,
        "mouse"    :    "Souris"    ,
        "electric fan"    :    "ventilateur Èlectrique"    ,
        "oil filter†"    :    "filtre ‡ l'huile"    ,
        "strainer†"    :    "passoire"    ,
        "space heater†"    :    "appareil de chauffage"    ,
        "stove†"    :    "poÍle"    ,
        "guillotine†"    :    "guillotine"    ,
        "barometer†"    :    "baromËtre"    ,
        "rule"    :    "rËgle"    ,
        "odometer"    :    "odomËtre"    ,
        "scale"    :    "Èchelle"    ,
        "analog clock†"    :    "horloge analogique"    ,
        "digital clock†"    :    "horloge digitale"    ,
        "wall clock†"    :    "horloge murale"    ,
        "hourglass†"    :    "Sablier"    ,
        "sundial†"    :    "cadran solaire"    ,
        "parking meter†"    :    "parcmËtre"    ,
        "stopwatch"    :    "chronomËtre"    ,
        "digital watch†"    :    "montre numÈrique"    ,
        "stethoscope†"    :    "stÈthoscope"    ,
        "syringe†"    :    "seringue"    ,
        "magnetic compass†"    :    "compas magnÈtique"    ,
        "binoculars"    :    "jumelles"    ,
        "projector†"    :    "projecteur"    ,
        "sunglasses"    :    "des lunettes de soleil"    ,
        "loupe"    :    "loupe"    ,
        "radio telescope"    :    "radiotÈlescope"    ,
        "bow†"    :    "arc"    ,
        "cannon†"    :    "canon"    ,
        "assault rifle"    :    "fusil d'assaut"    ,
        "rifle†"    :    "fusil"    ,
        "projectile"    :    "projectile"    ,
        "computer keyboard"    :    "clavier d'ordinateur"    ,
        "typewriter keyboard†"    :    "clavier de machine ‡ Ècrire"    ,
        "crane†"    :    "grue"    ,
        "lighter"    :    "plus lÈger"    ,
        "abacus†"    :    "abaque"    ,
        "cash machine"    :    "distributeur de billets"    ,
        "slide rule"    :    "rËgle ‡ calcul"    ,
        "desktop computer†"    :    "ordinateur de bureau"    ,
        "hand-held computer"    :    "ordinateur portatif"    ,
        "notebook"    :    "carnet"    ,
        "padlock†"    :    "cadenas"    ,
        "harvester"    :    "moissonneuse"    ,
        "thresher"    :    "batteuse"    ,
        "printer†"    :    "imprimante"    ,
        "slot"    :    "fente"    ,
        "vending machine†"    :    "distributeur automatique"    ,
        "sewing machine†"    :    "machine ‡ coudre"    ,
        "joystick†"    :    "manette"    ,
        "switch"    :    "commutateur"    ,
        "hook"    :    "crochet"    ,
        "car wheel†"    :    "roue de voiture"    ,
        "paddlewheel"    :    "roue ‡ aubes"    ,
        "pinwheel†"    :    "pinwheel"    ,
        "potter's wheel†"    :    "tour de potier"    ,
        "gas pump"    :    "pompe ‡ essence"    ,
        "carousel"    :    "carrousel"    ,
        "swing†"    :    "balanÁoire"    ,
        "reel†"    :    "bobine"    ,
        "radiator†"    :    "radiateur"    ,
        "puck"    :    "palet"    ,
        "hard disc"    :    "le disque dur"    ,
        "sunglass†"    :    "lunettes de soleil"    ,
        "pick"    :    "choisir"    ,
        "car mirror†"    :    "miroir de voiture"    ,
        "solar dish"    :    "plat solaire"    ,
        "remote control"    :    "tÈlÈcommande"    ,
        "disk brake"    :    "Frein ‡ disque"    ,
        "buckle†"    :    "Boucle"    ,
        "hair slide†"    :    "barrette"    ,
        "knot†"    :    "núud"    ,
        "combination lock†"    :    "Serrure ‡ combinaison"    ,
        "web site"    :    "site Internet"    ,
        "nail†"    :    "clou"    ,
        "safety pin†"    :    "Èpingle de s˚retÈ"    ,
        "screw†"    :    "vis"    ,
        "muzzle†"    :    "museau"    ,
        "seat belt"    :    "ceinture de sÈcuritÈ"    ,
        "ski†"    :    "ski"    ,
        "candle"    :    "bougie"    ,
        "jack-o'-lantern†"    :    "citrouille d'Halloween"    ,
        "spotlight"    :    "projecteur"    ,
        "torch†"    :    "torche"    ,
        "neck brace†"    :    "Minerve"    ,
        "pier†"    :    "jetÈe"    ,
        "tripod†"    :    "trÈpied"    ,
        "maypole†"    :    "m‚t enrubannÈ"    ,
        "hand blower"    :    "souffleur ‡ main"    ,
        "mousetrap†"    :    "piege a souris"    ,
        "spider web"    :    "toile d'araignÈe"    ,
        "trilobite†"    :    "trilobite"    ,
        "harvestman"    :    "moissonneur"    ,
        "scorpion†"    :    "Scorpion"    ,
        "black and gold garden spider"    :    "araignÈe de jardin noir et or"    ,
        "barn spider"    :    "araignÈe de grange"    ,
        "garden spider"    :    "araignÈe de jardin"    ,
        "black widow"    :    "veuve noire"    ,
        "tarantula†"    :    "tarentule"    ,
        "wolf spider"    :    "araignÈe de loup"    ,
        "tick†"    :    "cocher"    ,
        "centipede†"    :    "mille pattes"    ,
        "isopod†"    :    "isopode"    ,
        "Dungeness crab"    :    "Crabe dormeur"    ,
        "rock crab"    :    "crabe commun"    ,
        "fiddler crab†"    :    "crabe violoniste"    ,
        "king crab"    :    "crabe royal"    ,
        "American lobster"    :    "Homard amÈricain"    ,
        "spiny lobster"    :    "homard Èpineux"    ,
        "crayfish"    :    "Ècrevisse"    ,
        "hermit crab†"    :    "bernard-l'ermite"    ,
        "tiger beetle†"    :    "cicindËle du tigre"    ,
        "ladybug"    :    "coccinelle"    ,
        "ground beetle"    :    "dendroctone du sol"    ,
        "long-horned beetle"    :    "longicorne"    ,
        "leaf beetle"    :    "dendroctone"    ,
        "dung beetle†"    :    "bousier"    ,
        "rhinoceros beetle†"    :    "scarabÈe de rhinocÈros"    ,
        "weevil†"    :    "charanÁon"    ,
        "fly†"    :    "mouche"    ,
        "bee†"    :    "abeille"    ,
        "grasshopper"    :    "sauterelle"    ,
        "cricket†"    :    "criquet"    ,
        "walking stick"    :    "b‚ton de marche"    ,
        "cockroach"    :    "cafard"    ,
        "mantis"    :    "mante"    ,
        "cicada"    :    "cigale"    ,
        "leafhopper†"    :    "cicadelle"    ,
        "lacewing"    :    "chrysope"    ,
        "dragonfly"    :    "libellule"    ,
        "damselfly†"    :    "demoiselle"    ,
        "admiral†"    :    "amiral"    ,
        "ringlet"    :    "anglaise"    ,
        "monarch"    :    "monarque"    ,
        "cabbage butterfly†"    :    "papillon de chou"    ,
        "sulphur butterfly"    :    "papillon de soufre"    ,
        "lycaenid"    :    "lycaenid"    ,
        "jellyfish†"    :    "mÈduse"    ,
        "sea anemone"    :    "AnÈmone de mer"    ,
        "brain coral†"    :    "corail cÈrÈbral"    ,
        "flatworm"    :    "ver plat"    ,
        "nematode"    :    "nÈmatode"    ,
        "conch†"    :    "conque"    ,
        "snail†"    :    "escargot"    ,
        "slug†"    :    "limace"    ,
        "sea slug"    :    "Limace de mer"    ,
        "chiton"    :    "chiton"    ,
        "sea urchin†"    :    "oursin"    ,
        "sea cucumber"    :    "concombre de mer"    ,
        "iron"    :    "le fer"    ,
        "espresso maker†"    :    "machine ‡ expresso"    ,
        "microwave"    :    "four micro onde"    ,
        "Dutch oven†"    :    "Four nÈerlandais"    ,
        "rotisserie†"    :    "rÙtissoire"    ,
        "toaster†"    :    "toaster"    ,
        "waffle iron†"    :    "gaufrier"    ,
        "vacuum"    :    "vide"    ,
        "dishwasher"    :    "Lave-vaisselle"    ,
        "refrigerator"    :    "rÈfrigÈrateur"    ,
        "washer"    :    "machine ‡ laver"    ,
        "Crock Pot†"    :    "Crock Pot"    ,
        "frying pan"    :    "poÍle ‡ frire"    ,
        "wok†"    :    "wok"    ,
        "caldron"    :    "chaudron"    ,
        "coffeepot†"    :    "cafetiËre"    ,
        "teapot†"    :    "thÈiËre"    ,
        "spatula†"    :    "spatule"    ,
        "altar†"    :    "autel"    ,
        "triumphal arch†"    :    "arc de Triomphe"    ,
        "patio"    :    "patio"    ,
        "steel arch bridge†"    :    "pont en arc en acier"    ,
        "suspension bridge†"    :    "pont suspendu"    ,
        "viaduct†"    :    "viaduc"    ,
        "barn†"    :    "Grange"    ,
        "greenhouse"    :    "serre"    ,
        "palace†"    :    "palais"    ,
        "monastery†"    :    "monastËre"    ,
        "library†"    :    "bibliothËque"    ,
        "apiary"    :    "rucher"    ,
        "boathouse†"    :    "hangar ‡ bateaux"    ,
        "church"    :    "Èglise"    ,
        "mosque†"    :    "mosquÈe"    ,
        "stupa"    :    "stupa"    ,
        "planetarium†"    :    "planÈtarium"    ,
        "restaurant"    :    "restaurant"    ,
        "cinema"    :    "cinÈma"    ,
        "home theater"    :    "cinÈma maison"    ,
        "lumbermill"    :    "scierie"    ,
        "coil"    :    "bobine"    ,
        "obelisk†"    :    "obÈlisque"    ,
        "totem pole†"    :    "totem"    ,
        "castle†"    :    "Ch‚teau"    ,
        "prison"    :    "prison"    ,
        "grocery store"    :    "Èpicerie"    ,
        "bakery"    :    "boulangerie"    ,
        "barbershop†"    :    "salon de coiffure"    ,
        "bookshop"    :    "librairie"    ,
        "butcher shop"    :    "boucherie"    ,
        "confectionery"    :    "confiserie"    ,
        "shoe shop"    :    "magasin de chaussures"    ,
        "tobacco shop"    :    "boutique de tabac"    ,
        "toyshop†"    :    "Magasin de jouets"    ,
        "fountain†"    :    "Fontaine"    ,
        "cliff dwelling†"    :    "habitation de la falaise"    ,
        "yurt†"    :    "yourte"    ,
        "dock"    :    "Dock"    ,
        "brass"    :    "laiton"    ,
        "megalith"    :    "mÈgalithe"    ,
        "bannister"    :    "rampe"    ,
        "breakwater"    :    "digue"    ,
        "dam"    :    "barrage"    ,
        "chainlink fence†"    :    "grillage"    ,
        "picket fence"    :    "palissade"    ,
        "worm fence"    :    "clÙture de ver"    ,
        "diamondback"    :    "Diamondback"    ,
        "grille"    :    "grille"    ,
        "sliding door†"    :    "porte coulissante"    ,
        "turnstile†"    :    "tourniquet"    ,
        "mountain tent†"    :    "tente de montagne"    ,
        "scoreboard†"    :    "tableau de bord"    ,
        "honeycomb†"    :    "rayon de miel"    ,
        "plate rack†"    :    "Ègouttoir"    ,
        "pedestal"    :    "piÈdestal"    ,
        "beacon"    :    "balise"    ,
        "leatherback turtle"    :    "tortue luth"    ,
        "mashed potato†"    :    "purÈe"    ,
        "bell pepper†"    :    "poivron"    ,
        "head cabbage†"    :    "chou tÍte"    ,
        "broccoli†"    :    "brocoli"    ,
        "cauliflower†"    :    "choufleur"    ,
        "zucchini"    :    "Zucchini"    ,
        "spaghetti squash†"    :    "courge spaghetti"    ,
        "acorn squash†"    :    "courge poivrÈe"    ,
        "butternut squash†"    :    "courge butternut"    ,
        "cucumber"    :    "concombre"    ,
        "artichoke"    :    "artichaut"    ,
        "cardoon†"    :    "cardon"    ,
        "mushroom†"    :    "champignon"    ,
        "shower curtain†"    :    "rideau de douche"    ,
        "jean"    :    "jean"    ,
        "carton†"    :    "carton"    ,
        "handkerchief"    :    "mouchoir"    ,
        "sandal†"    :    "sandale"    ,
        "ashcan"    :    "cendrier"    ,
        "safe†"    :    "s˚r"    ,
        "plate†"    :    "assiette"    ,
        "necklace†"    :    "Collier"    ,
        "croquet ball†"    :    "boule de croquet"    ,
        "fur coat†"    :    "manteau de fourrure"    ,
        "thimble†"    :    "dÈ"    ,
        "pajama"    :    "pyjama"    ,
        "running shoe†"    :    "chaussure de course"    ,
        "oboe"    :    "hautbois"    ,
        "cocktail shaker†"    :    "shaker ‡ cocktail"    ,
        "chest†"    :    "poitrine"    ,
        "manhole cover†"    :    "plaque d'Ègout"    ,
        "modem†"    :    "modem"    ,
        "tub"    :    "cuve"    ,
        "tray†"    :    "plateau"    ,
        "balance beam"    :    "poutre d'Èquilibre"    ,
        "bagel"    :    "beignet"    ,
        "violin"    :    "violon"    ,
        "prayer rug"    :    "tapis de priËre"    ,
        "kimono†"    :    "kimono"    ,
        "hot pot"    :    "pot chaud"    ,
        "whiskey jug†"    :    "pichet ‡ whisky"    ,
        "knee pad†"    :    "genouillËre"    ,
        "book jacket"    :    "Couverture de livre"    ,
        "spindle†"    :    "broche"    ,
        "ski mask†"    :    "masque de ski"    ,
        "beer bottle†"    :    "bouteille de biËre"    ,
        "crash helmet†"    :    "casque de protection"    ,
        "bottlecap†"    :    "bouchon de la bouteille"    ,
        "tile roof†"    :    "Toit en tuiles"    ,
        "mask†"    :    "masque"    ,
        "maillot†"    :    "maillot"    ,
        "Petri dish†"    :    "BoÓte de PÈtri"    ,
        "football helmet†"    :    "casque de football amÈricain"    ,
        "bathing cap"    :    "Bonnet de bain"    ,
        "teddy"    :    "nounours"    ,
        "holster†"    :    "Ètui"    ,
        "pop bottle"    :    "bouteille de pop"    ,
        "photocopier†"    :    "photocopieur"    ,
        "vestment†"    :    "vÍtement"    ,
        "crossword puzzle"    :    "mots croisÈs"    ,
        "golf ball†"    :    "balle de golf"    ,
        "trifle†"    :    "bagatelle"    ,
        "suit"    :    "costume"    ,
        "water tower†"    :    "ch‚teau d'eau"    ,
        "feather boa"    :    "Boa de plumes"    ,
        "cloak†"    :    "manteau"    ,
        "red wine†"    :    "vin rouge"    ,
        "drumstick†"    :    "pilon"    ,
        "shield"    :    "bouclier"    ,
        "Christmas stocking†"    :    "Bas de NoÎl"    ,
        "hoopskirt"    :    "cerceau"    ,
        "menu†"    :    "menu"    ,
        "stage†"    :    "Ètape"    ,
        "bonnet"    :    "bonnet"    ,
        "meat loaf"    :    "Pain de viande"    ,
        "baseball†"    :    "base-ball"    ,
        "face powder†"    :    "poudre pour le visage"    ,
        "scabbard†"    :    "fourreau"    ,
        "sunscreen"    :    "crËme solaire"    ,
        "beer glass†"    :    "Verre ‡ biËre"    ,
        "hen-of-the-woods"    :    "poule des bois"    ,
        "guacamole†"    :    "guacamole"    ,
        "wool"    :    "la laine"    ,
        "hay†"    :    "foins"    ,
        "bow tie"    :    "núud papillon"    ,
        "mailbag"    :    "sac postal"    ,
        "water jug†"    :    "pot ‡ eau"    ,
        "bucket"    :    "seau"    ,
        "dishrag"    :    "dÈcrypter"    ,
        "soup bowl†"    :    "bol de soupe"    ,
        "eggnog†"    :    "Lait de poule"    ,
        "mortar†"    :    "mortier"    ,
        "trench coat†"    :    "trench-coat"    ,
        "paddle"    :    "pagayer"    ,
        "chain†"    :    "chaÓne"    ,
        "swab"    :    "Ècouvillon"    ,
        "mixing bowl†"    :    "bol de mÈlange"    ,
        "potpie†"    :    "pot-pourri"    ,
        "wine bottle†"    :    "bouteille de vin"    ,
        "shoji†"    :    "shoji"    ,
        "bulletproof vest†"    :    "gilet pare-balles"    ,
        "drilling platform"    :    "plateforme de forage"    ,
        "binder"    :    "classeur"    ,
        "cardigan†"    :    "cardigan"    ,
        "sweatshirt†"    :    "sweat-shirt"    ,
        "pot"    :    "pot"    ,
        "birdhouse†"    :    "nichoir"    ,
        "jinrikisha"    :    "jinrikisha"    ,
        "hamper†"    :    "entraver"    ,
        "ping-pong ball†"    :    "balle de ping pong"    ,
        "pencil box"    :    "boÓte ‡ crayons"    ,
        "consomme†"    :    "consommÈ"    ,
        "apron†"    :    "tablier"    ,
        "punching bag"    :    "sac de boxe"    ,
        "backpack"    :    "sac ‡ dos"    ,
        "groom"    :    "jeune mariÈ"    ,
        "bearskin"    :    "bonnet ‡ poil"    ,
        "pencil sharpener†"    :    "taille-crayon"    ,
        "broom†"    :    "balai"    ,
        "abaya†"    :    "Abaya"    ,
        "mortarboard†"    :    "mortier"    ,
        "poncho†"    :    "poncho"    ,
        "crutch†"    :    "bÈquille"    ,
        "Polaroid camera"    :    "appareil PolaroÔd"    ,
        "space bar†"    :    "barre d'espace"    ,
        "cup†"    :    "Coupe"    ,
        "racket"    :    "raquette"    ,
        "traffic light"    :    "feu de circulation"    ,
        "quill"    :    "penne"    ,
        "radio"    :    "radio"    ,
        "snow leopard"    :    "lÈopard des neiges"    ,
        "dough†"    :    "p‚te"    ,
        "cuirass†"    :    "cuirasse"    ,
        "military uniform†"    :    "uniforme militaire"    ,
        "lipstick"    :    "rouge ‡ lËvres"    ,
        "shower cap†"    :    "Bonnet de bain"    ,
        "monitor†"    :    "moniteur"    ,
        "oscilloscope"    :    "oscilloscope"    ,
        "mitten†"    :    "mitaine"    ,
        "brassiere"    :    "soutien-gorge"    ,
        "French loaf†"    :    "Pain franÁais"    ,
        "vase†"    :    "vase"    ,
        "milk can†"    :    "bidon de lait"    ,
        "rugby ball†"    :    "ballon de rugby"    ,
        "paper towel†"    :    "essuie-tout"    ,
        "earthstar†"    :    "earthstar"    ,
        "envelope†"    :    "enveloppe"    ,
        "miniskirt"    :    "mini-jupe"    ,
        "cowboy hat"    :    "chapeau de cowboy"    ,
        "trolleybus"    :    "trolleybus"    ,
        "perfume"    :    "parfum"    ,
        "bathtub"    :    "baignoire"    ,
        "hotdog"    :    "Hot-dog"    ,
        "coral fungus†"    :    "champignon de corail"    ,
        "bullet train"    :    "train ‡ grande vitesse"    ,
        "pillow†"    :    "oreiller"    ,
        "toilet tissue"    :    "papier toilette"    ,
        "cassette†"    :    "cassette"    ,
        "carpenter's kit"    :    "kit de menuisier"    ,
        "ladle†"    :    "louche"    ,
        "stinkhorn"    :    "Stinkhorn"    ,
        "lotion†"    :    "lotion"    ,
        "hair spray†"    :    "Laque pour les cheveux"    ,
        "academic gown"    :    "robe acadÈmique"    ,
        "dome†"    :    "dÙme"    ,
        "crate†"    :    "Caisse"    ,
        "wig†"    :    "perruque"    ,
        "burrito†"    :    "burrito"    ,
        "pill bottle†"    :    "bouteille de pilules"    ,
        "chain mail"    :    "courrier de la chaÓne"    ,
        "theater curtain"    :    "rideau de thÈ‚tre"    ,
        "window shade†"    :    "fenÍtre"    ,
        "barrel"    :    "baril"    ,
        "washbasin"    :    "lavabo"    ,
        "ballpoint"    :    "‡ bille"    ,
        "basketball†"    :    "basketball"    ,
        "bath towel†"    :    "serviette de bain"    ,
        "cowboy boot†"    :    "botte de cow-boy"    ,
        "gown†"    :    "robe"    ,
        "window screen†"    :    "fenÍtre"    ,
        "agaric†"    :    "agaric"    ,
        "standard poodle†"    :    "caniche standard"    ,
        "cellular telephone"    :    "tÈlÈphone portable"    ,
        "nipple†"    :    "mamelon"    ,
        "barbell†"    :    "haltËre"    ,
        "mailbox"    :    "boites aux lettres"    ,
        "lab coat"    :    "blouse de laboratoire"    ,
        "fire screen"    :    "Ècran de feu"    ,
        "minibus†"    :    "minibus"    ,
        "packet†"    :    "paquet"    ,
        "brown bear"    :    "ours brun"    ,
        "pole†"    :    "pÙle"    ,
        "horizontal bar"    :    "barre horizontale"    ,
        "sombrero†"    :    "sombrero"    ,
        "pickelhaube†"    :    "pickelhaube"    ,
        "rain barrel†"    :    "baril de pluie"    ,
        "wallet"    :    "portefeuille"    ,
        "cassette player†"    :    "lecteur de cassettes"    ,
        "comic book†"    :    "BD"    ,
        "piggy bank"    :    "tirelire"    ,
        "street sign†"    :    "Panneau de signalisation"    ,
        "bell cote"    :    "bell cote"    ,
        "fountain pen†"    :    "stylo-plume"    ,
        "Windsor tie†"    :    "Cravate Windsor"    ,
        "volleyball†"    :    "volley-ball"    ,
        "overskirt†"    :    "jupe"    ,
        "sarong†"    :    "sarong"    ,
        "purse†"    :    "bourse"    ,
        "bolo tie"    :    "cravate bolo"    ,
        "bib†"    :    "bavoir"    ,
        "parachute"    :    "parachute"    ,
        "sleeping bag†"    :    "sac de couchage"    ,
        "television"    :    "tÈlÈvision"    ,
        "swimming trunks"    :    "maillot de bain"    ,
        "measuring cup†"    :    "Tasse ‡ mesurer"    ,
        "espresso†"    :    "Expresso"    ,
        "pizza"    :    "Pizza"    ,
        "breastplate"    :    "pectoral"    ,
        "shopping basket†"    :    "panier"    ,
        "wooden spoon†"    :    "cuillËre en bois"    ,
        "saltshaker"    :    "saliËre"    ,
        "chocolate sauce"    :    "sauce au chocolat"    ,
        "ballplayer"    :    "joueur de balle"    ,
        "goblet†"    :    "gobelet"    ,
        "gyromitra†"    :    "gyromitra"    ,
        "stretcher†"    :    "tendeur"    ,
        "water bottle†"    :    "bouteille d'eau"    ,
        "skunk"    :    "moufette"    ,
        "soap dispenser†"    :    "distributeur de savon"    ,
        "jersey"    :    "Jersey"    ,
        "school bus†"    :    "bus scolaire"    ,
        "jigsaw puzzle†"    :    "puzzle"    ,
        "plastic bag†"    :    "sac plastique"    ,
        "reflex camera†"    :    "appareil photo reflex"    ,
        "diaper"    :    "couche"    ,
        "Band Aid†"    :    "Pansement"    ,
        "ice lolly"    :    "sucette glacÈe"    ,
        "velvet†"    :    "velours"    ,
        "tennis ball†"    :    "balle de tennis"    ,
        "gasmask"    :    "masque ‡ gaz"    ,
        "doormat"    :    "paillasson"    ,
        "Loafer†"    :    "Fl‚neur"    ,
        "ice cream"    :    "crËme glacÈe"    ,
        "pretzel†"    :    "bretzel"    ,
        "quilt"    :    "courtepointe"    ,
        "maillot"    :    "maillot"    ,
        "tape player†"    :    "lecteur de cassettes"    ,
        "clog"    :    "sabot"    ,
        "iPod†"    :    "iPod"    ,
        "bolete†"    :    "bolete"    ,
        "meerkat"    :    "suricate"    ,
        "scuba diver†"    :    "plongeur"    ,
        "pitcher"    :    "lanceur"    ,
        "matchstick†"    :    "allumette"    ,
        "bikini"    :    "bikini"    ,
        "sock†"    :    "chaussette"    ,
        "CD player†"    :    "lecteur CD"    ,
        "lens cap"    :    "protËge-objectif"    ,
        "thatch"    :    "chaume"    ,
        "vault†"    :    "vo˚te"    ,
        "beaker†"    :    "gobelet"    ,
        "bubble†"    :    "bulle"    ,
        "cheeseburger†"    :    "cheeseburger"    ,
        "parallel bars"    :    "barres parallËles"    ,
        "flagpole"    :    "m‚t"    ,
        "coffee mug†"    :    "tasse de cafÈ"    ,
        "rubber eraser"    :    "gomme"    ,
        "stole†"    :    "a volÈ"    ,
        "carbonara"    :    "carbonara"    ,
        "dumbbell"    :    "haltËre"
]
