//
//  german.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-28.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let german = [
"person"    :    "Person"    ,
"bicycle"    :    "Fahrrad"    ,
"car"    :    "Auto"    ,
"motorcycle"    :    "Motorrad"    ,
"bird"    :    "Vogel"    ,
"cat"    :    "Katze"    ,
"dog"    :    "Hund"    ,
"horse"    :    "Pferd"    ,
"sheep"    :    "Schaf"    ,
"bottle"    :    "Flasche"    ,
"chair"    :    "Stuhl"    ,
"couch"    :    "Couch"    ,
"potted plant"    :    "Topfpflanze"    ,
"tv"    :    "Fernseher"    ,
"cow"    :    "Kuh"    ,
"airplane"    :    "Flugzeug"    ,
"hat"    :    "Hut"    ,
"license plate"    :    "Nummernschild"    ,
"bed"    :    "Bett"    ,
"laptop"    :    "Laptop"    ,
"fridge"    :    "Kühlschrank"    ,
"microwave"    :    "Mikrowelle"    ,
"sink"    :    "sinken"    ,
"oven"    :    "Ofen"    ,
"toaster"    :    "Toaster"    ,
"bus"    :    "Bus"    ,
"train"    :    "Zug"    ,
"mirror"    :    "Spiegel"    ,
"dining table"    :    "Esstisch"    ,
"elephant"    :    "Elefant"    ,
"banana"    :    "Banane"    ,
"bread"    :    "Brot"    ,
"toilet"    :    "Toilette"    ,
"book"    :    "Buch"    ,
"boat"    :    "Boot"    ,
"plate"    :    "Teller"    ,
"cellphone"    :    "Handy"    ,
"mouse"    :    "Maus"    ,
"remote"    :    "Fernbedienung"    ,
"clock"    :    "Uhr"    ,
"face"    :    "Gesicht"    ,
"hand"    :    "Hand"    ,
"apple"    :    "Apfel"    ,
"keyboard"    :    "Tastatur"    ,
"backpack"    :    "Rucksack"    ,
"steering wheel"    :    "Lenkrad"    ,
"wineglass"    :    "Weinglas"    ,
"chicken"    :    "Hähnchen"    ,
"zebra"    :    "Zebra"    ,
"shoe"    :    "Schuh"    ,
"eye"    :    "Auge"    ,
"mouth"    :    "Mund"    ,
"scissors"    :    "Schere"    ,
"truck"    :    "LKW"    ,
"traffic light"    :    "Ampel"    ,
"eyeglasses"    :    "Brille"    ,
"cup"    :    "Tasse"    ,
"blender"    :    "Mixer"    ,
"hairdrier"    :    "Fön"    ,
"wheel"    :    "Rad"    ,
"streetsign"    :    "Straßenschild"    ,
"umbrella"    :    "Regenschirm"    ,
"door"    :    "Tür"    ,
"firehydrant"    :    "Feuerhydrant"    ,
"bowl"    :    "Schüssel"    ,
"teapot"    :    "Teekanne"    ,
"fork"    :    "Gabel"    ,
"knife"    :    "Messer"    ,
"spoon"    :    "Löffel"    ,
"bear"    :    "Bär"    ,
"headlights"    :    "Scheinwerfer"    ,
"window"    :    "Fenster"    ,
"desk"    :    "Schreibtisch"    ,
"computer"    :    "Computer"    ,
"refrigerator"    :    "Kühlschrank"    ,
"pizza"    :    "Pizza"    ,
"squirrel"    :    "Eichhörnchen"    ,
"duck"    :    "Ente"    ,
"frisbee"    :    "Frisbeescheibe"    ,
"guitar"    :    "Gitarre"    ,
"nose"    :    "Nase"    ,
"teddybear"    :    "Teddybär"    ,
"tie"    :    "Krawatte"    ,
"stopsign"    :    "Stoppschild"    ,
"surfboard"    :    "Surfbrett"    ,
"sandwich"    :    "Sandwich"    ,
"pen/pencil"    :    "Kugelschreiber Bleistift"    ,
"kite"    :    "Drachen"    ,
"orange"    :    "Orange"    ,
"toothbrush"    :    "Zahnbürste"    ,
"printer"    :    "Drucker"    ,
"pans"    :    "Pfannen"    ,
"head"    :    "Kopf"    ,
"sports ball"    :    "Sportball"    ,
"broccoli"    :    "Brokkoli"    ,
"suitcase"    :    "Koffer"    ,
"carrot"    :    "Karotte"    ,
"chandelier"    :    "Leuchter"    ,
"parking meter"    :    "Parkuhr"    ,
"fish"    :    "Fisch"    ,
"handbag"    :    "Handtasche"    ,
"hotdog"    :    "Hotdog"    ,
"stapler"    :    "Hefter"    ,
"basketball hoop"    :    "Basketballkorb"    ,
"donut"    :    "Krapfen"    ,
"vase"    :    "Vase"    ,
"baseball bat"    :    "Baseballschläger"    ,
"baseball glove"    :    "Baseballhandschuh"    ,
"giraffe"    :    "Giraffe"    ,
"jacket"    :    "Jacke"    ,
"skis"    :    "Ski"    ,
"snowboard"    :    "Snowboard"    ,
"tablelamp"    :    "Tischlampe"    ,
"egg"    :    "Ei"    ,
"door handle"    :    "Türschnalle"    ,
"power outlet"    :    "Steckdose"    ,
"hair"    :    "Haar"    ,
"tiger"    :    "Tiger"    ,
"table"    :    "Tabelle"    ,
"coffee table"    :    "Kaffetisch"    ,
"skate board"    :    "Skateboard"    ,
"helicopter"    :    "Hubschrauber"    ,
"tomato"    :    "Tomate"    ,
"tree"    :    "Baum"    ,
"bunny"    :    "Hase"    ,
"pillow"    :    "Kissen"    ,
"tennis racket"    :    "Tennisschläger"    ,
"cake"    :    "Kuchen"    ,
"feet"    :    "Füße"    ,
"bench"    :    "Bank"    ,
"chopping board"    :    "Hackbrett"    ,
"washer"    :    "Unterlegscheibe"    ,
"lion"    :    "Löwe"    ,
"monkey"    :    "Affe"    ,
"hairbrush"    :    "Haarbürste"    ,
"light switch"    :    "Lichtschalter"    ,
"arms"    :    "Waffen"    ,
"legs"    :    "Beine"    ,
"house"    :    "Haus"    ,
"cheese"    :    "Käse"    ,
"goat"    :    "Ziege"    ,
"magazine"    :    "Zeitschrift"    ,
"key"    :    "Schlüssel"    ,
"picture"    :    "Bild"    ,
"frame"    :    "Rahmen"    ,
"cupcake"    :    "Cupcake"    ,
"fan(ceil/floor)"    :    "Ventilator (Decke / Boden)"    ,
"frogs"    :    "Frösche"    ,
"rabbit"    :    "Hase"    ,
"owl"    :    "Eule"    ,
"scarf"    :    "Schal"    ,
"ears"    :    "Ohren"    ,
"homephone"    :    "Festnetztelefon"    ,
"pig"    :    "Schwein"    ,
"strawberries"    :    "Erdbeeren"    ,
"pumpkin"    :    "Kürbis"    ,
"van"    :    "van"    ,
"kangaroo"    :    "Känguru"    ,
"rhinoceros"    :    "Nashorn"    ,
"sailboat"    :    "Segelboot"    ,
"deer"    :    "Hirsch"    ,
"playing cards"    :    "Kartenspielen"    ,
"towel"    :    "Handtuch"    ,
"hyppo hyppo"    :    "Hypo Hypo"    ,
"can"    :    "kann"    ,
"dollar bill"    :    "Dollar-Note"    ,
"doll"    :    "Puppe"    ,
"soup"    :    "Suppe"    ,
"meat"    :    "Fleisch"    ,
"muffins"    :    "Muffins"    ,
"tire"    :    "Reifen"    ,
"necklace"    :    "Halskette"    ,
"tablet"    :    "Tablette"    ,
"corn"    :    "Mais"    ,
"ladder"    :    "Leiter"    ,
"pineapple"    :    "Ananas"    ,
"candle"    :    "Kerze"    ,
"desktop"    :    "Desktop"    ,
"carpet"    :    "Teppich"    ,
"cookie"    :    "Plätzchen"    ,
"toycars"    :    "Spielzeugautos"    ,
"bracelet"    :    "Armband"    ,
"bat"    :    "Fledermaus"    ,
"balloon"    :    "Ballon"    ,
"gloves"    :    "Handschuhe"    ,
"milk"    :    "Milch"    ,
"pants"    :    "Hose"    ,
"wheelchair"    :    "Rollstuhl"    ,
"building"    :    "Gebäude"    ,
"bacon"    :    "Speck"    ,
"box"    :    "Box"    ,
"platypus"    :    "Schnabeltier"    ,
"pancake"    :    "Pfannkuchen"    ,
"cabinet"    :    "Kabinett"    ,
"whale"    :    "Wal"    ,
"dryer"    :    "Trockner"    ,
"torso"    :    "Torso"    ,
"lizard"    :    "Eidechse"    ,
"shirt"    :    "Hemd"    ,
"shorts"    :    "kurze Hose"    ,
"pasta"    :    "Pasta"    ,
"grapes"    :    "Trauben"    ,
"shark"    :    "Hai"    ,
"swan"    :    "Schwan"    ,
"fingers"    :    "Finger"    ,
"sidetable"    :    "Beistelltisch"    ,
"gate"    :    "Tor"    ,
"beans"    :    "Bohnen"    ,
"flip flops"    :    "Flip Flops"    ,
"moon"    :    "Mond"    ,
"road/street/"    :    "Straße/"    ,
"fountain"    :    "Brunnen"    ,
"faxmachine"    :    "Faxgerät"    ,
"hotair balloon"    :    "Heißluftballon"    ,
"cereal"    :    "Müsli"    ,
"seahorse"    :    "Seepferdchen"    ,
"rocket"    :    "Rakete"    ,
"cabinets"    :    "Schränke"    ,
"basketball"    :    "Basketball"    ,
"telephone"    :    "Telefon"    ,
"movie(disc)"    :    "Film (Scheibe)"    ,
"football"    :    "Fußball"    ,
"goose"    :    "Gans"    ,
"long-sleeve shirt"    :    "Langarm-Shirt"    ,
"short-sleeve shirt"    :    "Kurzarm-Shirt"    ,
"raft"    :    "Floß"    ,
"rooster"    :    "Hahn"    ,
"copier"    :    "Kopierer"    ,
"radio"    :    "Radio"    ,
"fences"    :    "Zäune"    ,
"goalnet"    :    "Tornetz"    ,
"toys"    :    "Spielzeuge"    ,
"engine"    :    "Motor"    ,
"soccerball"    :    "Fußball"    ,
"fieldgoal posts"    :    "Feldbeiträge"    ,
"socks"    :    "Socken"    ,
"tennisnet"    :    "Tennisnetz"    ,
"seats"    :    "Sitze"    ,
"elbows"    :    "Ellbogen"    ,
"aardvark"    :    "Erdferkel"    ,
"dinosaur"    :    "Dinosaurier"    ,
"unicycle"    :    "Einrad"    ,
"honey"    :    "Honig"    ,
"legos"    :    "Legos"    ,
"fly"    :    "Fliege"    ,
"roof"    :    "Dach"    ,
"baseball"    :    "Baseball"    ,
"mat"    :    "Matte"    ,
"ipad"    :    "iPad"    ,
"iphone"    :    "iphone"    ,
"hoop"    :    "Band"    ,
"hen"    :    "Henne"    ,
"back"    :    "zurück"    ,
"table cloth"    :    "Tischdecke"    ,
"soccer nets"    :    "Fußballnetze"    ,
"turkey"    :    "Truthahn"    ,
"pajamas"    :    "Pyjama"    ,
"underpants"    :    "Unterhose"    ,
"goldfish"    :    "Goldfisch"    ,
"robot"    :    "Roboter"    ,
"crusher"    :    "Brecher"    ,
"animal crackers"    :    "Tiercracker"    ,
"basketball court"    :    "Basketball Platz"    ,
"horn"    :    "Horn"    ,
"firefly"    :    "Glühwürmchen"    ,
"armpits"    :    "Achselhöhlen"    ,
"nectar"    :    "Nektar"    ,
"superhero costume"    :    "Superhelden-Kostüm"    ,
"jetpack"    :    "Jetpack"    ,
"robots"    :    "Roboter"
]
