//
//  greek.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-28.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let greek = [
    "person"    :    "πρόσωπο"    ,
    "bicycle"    :    "ποδήλατο"    ,
    "car"    :    "αυτοκίνητο"    ,
    "motorcycle"    :    "μοτοσυκλέτα"    ,
    "bird"    :    "πουλί"    ,
    "cat"    :    "Γάτα"    ,
    "dog"    :    "σκύλος"    ,
    "horse"    :    "άλογο"    ,
    "sheep"    :    "πρόβατο"    ,
    "bottle"    :    "μπουκάλι"    ,
    "chair"    :    "καρέκλα"    ,
    "couch"    :    "καναπές"    ,
    "potted plant"    :    "φυτό σε γλάστρα"    ,
    "tv"    :    "τηλεόραση"    ,
    "cow"    :    "αγελάδα"    ,
    "airplane"    :    "αεροπλάνο"    ,
    "hat"    :    "καπέλο"    ,
    "license plate"    :    "πινακίδα κυκλοφορίας"    ,
    "bed"    :    "κρεβάτι"    ,
    "laptop"    :    "ΦΟΡΗΤΟΣ ΥΠΟΛΟΓΙΣΤΗΣ"    ,
    "fridge"    :    "ψυγείο"    ,
    "microwave"    :    "ΦΟΥΡΝΟΣ ΜΙΚΡΟΚΥΜΑΤΩΝ"    ,
    "sink"    :    "νεροχύτης"    ,
    "oven"    :    "φούρνος"    ,
    "toaster"    :    "φρυγανιέρα"    ,
    "bus"    :    "λεωφορείο"    ,
    "train"    :    "τρένο"    ,
    "mirror"    :    "καθρέφτης"    ,
    "dining table"    :    "τραπέζι δείπνου"    ,
    "elephant"    :    "ελέφαντας"    ,
    "banana"    :    "μπανάνα"    ,
    "bread"    :    "ψωμί"    ,
    "toilet"    :    "τουαλέτα"    ,
    "book"    :    "Βιβλίο"    ,
    "boat"    :    "σκάφος"    ,
    "plate"    :    "πλάκα"    ,
    "cellphone"    :    "κινητό τηλέφωνο"    ,
    "mouse"    :    "ποντίκι"    ,
    "remote"    :    "μακρινός"    ,
    "clock"    :    "ρολόι"    ,
    "face"    :    "πρόσωπο"    ,
    "hand"    :    "χέρι"    ,
    "apple"    :    "μήλο"    ,
    "keyboard"    :    "πληκτρολόγιο"    ,
    "backpack"    :    "ΣΑΚΙΔΙΟ ΠΛΑΤΗΣ"    ,
    "steering wheel"    :    "τιμόνι"    ,
    "wineglass"    :    "κρασοπότηρο"    ,
    "chicken"    :    "κοτόπουλο"    ,
    "zebra"    :    "ζέβρα"    ,
    "shoe"    :    "παπούτσι"    ,
    "eye"    :    "μάτι"    ,
    "mouth"    :    "στόμα"    ,
    "scissors"    :    "ψαλίδι"    ,
    "truck"    :    "φορτηγό"    ,
    "traffic light"    :    "φανάρι"    ,
    "eyeglasses"    :    "γυαλιά"    ,
    "cup"    :    "φλιτζάνι"    ,
    "blender"    :    "μίξερ"    ,
    "hairdrier"    :    "πιστολάκι"    ,
    "wheel"    :    "ΡΟΔΑ"    ,
    "streetsign"    :    "πινακίδα"    ,
    "umbrella"    :    "ομπρέλα"    ,
    "door"    :    "θύρα"    ,
    "firehydrant"    :    "φωσφορικό"    ,
    "bowl"    :    "γαβάθα"    ,
    "teapot"    :    "τσαγιέρα"    ,
    "fork"    :    "πιρούνι"    ,
    "knife"    :    "μαχαίρι"    ,
    "spoon"    :    "κουτάλι"    ,
    "bear"    :    "αρκούδα"    ,
    "headlights"    :    "προβολείς"    ,
    "window"    :    "παράθυρο"    ,
    "desk"    :    "γραφείο"    ,
    "computer"    :    "υπολογιστή"    ,
    "refrigerator"    :    "ψυγείο"    ,
    "pizza"    :    "πίτσα"    ,
    "squirrel"    :    "σκίουρος"    ,
    "duck"    :    "πάπια"    ,
    "frisbee"    :    "frisbee"    ,
    "guitar"    :    "κιθάρα"    ,
    "nose"    :    "μύτη"    ,
    "teddybear"    :    "αρκουδάκι"    ,
    "tie"    :    "γραβάτα"    ,
    "stopsign"    :    "σήμα στοπ"    ,
    "surfboard"    :    "σανίδα του σέρφιν"    ,
    "sandwich"    :    "σάντουιτς"    ,
    "pen/pencil"    :    "στυλό μολύβι"    ,
    "kite"    :    "χαρταετός"    ,
    "orange"    :    "πορτοκάλι"    ,
    "toothbrush"    :    "οδοντόβουρτσα"    ,
    "printer"    :    "εκτυπωτής"    ,
    "pans"    :    "τα ταψιά"    ,
    "head"    :    "κεφάλι"    ,
    "sports ball"    :    "σπορ μπάλα"    ,
    "broccoli"    :    "μπρόκολο"    ,
    "suitcase"    :    "βαλίτσα"    ,
    "carrot"    :    "καρότο"    ,
    "chandelier"    :    "πολυέλαιος"    ,
    "parking meter"    :    "παρκόμετρο"    ,
    "fish"    :    "ψάρι"    ,
    "handbag"    :    "τσάντα"    ,
    "hotdog"    :    "λουκάνικο"    ,
    "stapler"    :    "συρραπτικο"    ,
    "basketball hoop"    :    "μπάσκετ στεφάνι"    ,
    "donut"    :    "ντόνατ"    ,
    "vase"    :    "βάζο"    ,
    "baseball bat"    :    "ρόπαλο του μπέιζμπολ"    ,
    "baseball glove"    :    "γάντι του μπέιζμπολ"    ,
    "giraffe"    :    "καμηλοπάρδαλη"    ,
    "jacket"    :    "σακάκι"    ,
    "skis"    :    "σκι"    ,
    "snowboard"    :    "snowboard"    ,
    "tablelamp"    :    "επιτραπέζιο φωτιστικό"    ,
    "egg"    :    "αυγό"    ,
    "door handle"    :    "χερούλι πόρτας"    ,
    "power outlet"    :    "πρίζα ρεύματος"    ,
    "hair"    :    "μαλλιά"    ,
    "tiger"    :    "τίγρη"    ,
    "table"    :    "τραπέζι"    ,
    "coffee table"    :    "τραπεζάκι του καφέ"    ,
    "skate board"    :    "skate board"    ,
    "helicopter"    :    "ελικόπτερο"    ,
    "tomato"    :    "ντομάτα"    ,
    "tree"    :    "δέντρο"    ,
    "bunny"    :    "λαγουδάκι"    ,
    "pillow"    :    "μαξιλάρι"    ,
    "tennis racket"    :    "ρακέτα του τένις"    ,
    "cake"    :    "κέικ"    ,
    "feet"    :    "πόδια"    ,
    "bench"    :    "παγκάκι"    ,
    "chopping board"    :    "ξύλο κοπής"    ,
    "washer"    :    "ροδέλα"    ,
    "lion"    :    "λιοντάρι"    ,
    "monkey"    :    "Πίθηκος"    ,
    "hairbrush"    :    "βούρτσα μαλλιών"    ,
    "light switch"    :    "διακόπτης φωτός"    ,
    "arms"    :    "όπλα"    ,
    "legs"    :    "πόδια"    ,
    "house"    :    "σπίτι"    ,
    "cheese"    :    "τυρί"    ,
    "goat"    :    "γίδα"    ,
    "magazine"    :    "περιοδικό"    ,
    "key"    :    "κλειδί"    ,
    "picture"    :    "εικόνα"    ,
    "frame"    :    "πλαίσιο"    ,
    "cupcake"    :    "κεκάκι"    ,
    "fan(ceil/floor)"    :    "ανεμιστήρας (οροφή / πάτωμα)"    ,
    "frogs"    :    "βατράχια"    ,
    "rabbit"    :    "κουνέλι"    ,
    "owl"    :    "κουκουβάγια"    ,
    "scarf"    :    "κασκόλ"    ,
    "ears"    :    "αυτιά"    ,
    "homephone"    :    "το τηλέφωνο του σπιτιού"    ,
    "pig"    :    "Χοίρος"    ,
    "strawberries"    :    "φράουλες"    ,
    "pumpkin"    :    "κολοκύθι"    ,
    "van"    :    "βαν"    ,
    "kangaroo"    :    "καγκουρώ"    ,
    "rhinoceros"    :    "ρινόκερως"    ,
    "sailboat"    :    "ιστιοφόρο"    ,
    "deer"    :    "ελάφι"    ,
    "playing cards"    :    "παίζοντας κάρτες"    ,
    "towel"    :    "πετσέτα"    ,
    "hyppo hyppo"    :    "hypp ippo"    ,
    "can"    :    "μπορώ"    ,
    "dollar bill"    :    "χαρτονόμισμα δολλαρίου"    ,
    "doll"    :    "κούκλα"    ,
    "soup"    :    "σούπα"    ,
    "meat"    :    "κρέας"    ,
    "muffins"    :    "muffins"    ,
    "tire"    :    "λάστιχο"    ,
    "necklace"    :    "κολιέ"    ,
    "tablet"    :    "δισκίο"    ,
    "corn"    :    "καλαμπόκι"    ,
    "ladder"    :    "σκάλα"    ,
    "pineapple"    :    "ανανάς"    ,
    "candle"    :    "κερί"    ,
    "desktop"    :    "επιφάνεια εργασίας"    ,
    "carpet"    :    "χαλί"    ,
    "cookie"    :    "κουλουράκι"    ,
    "toycars"    :    "αυτοκινητάκια"    ,
    "bracelet"    :    "βραχιόλι"    ,
    "bat"    :    "νυχτερίδα"    ,
    "balloon"    :    "μπαλόνι"    ,
    "gloves"    :    "γάντια"    ,
    "milk"    :    "γάλα"    ,
    "pants"    :    "παντελόνι"    ,
    "wheelchair"    :    "ΑΝΑΠΗΡΙΚΟ ΚΑΡΟΤΣΑΚΙ"    ,
    "building"    :    "Κτίριο"    ,
    "bacon"    :    "μπέικον"    ,
    "box"    :    "κουτί"    ,
    "platypus"    :    "πλατύπους"    ,
    "pancake"    :    "τηγανίτα"    ,
    "cabinet"    :    "υπουργικό συμβούλιο"    ,
    "whale"    :    "φάλαινα"    ,
    "dryer"    :    "στεγνωτήριο"    ,
    "torso"    :    "κορμός σώματος"    ,
    "lizard"    :    "σαύρα"    ,
    "shirt"    :    "πουκάμισο"    ,
    "shorts"    :    "σορτς"    ,
    "pasta"    :    "ζυμαρικά"    ,
    "grapes"    :    "σταφύλια"    ,
    "shark"    :    "καρχαρίας"    ,
    "swan"    :    "κύκνος"    ,
    "fingers"    :    "δάχτυλα"    ,
    "sidetable"    :    "αναπόσπαστο"    ,
    "gate"    :    "πύλη"    ,
    "beans"    :    "φασόλια"    ,
    "flip flops"    :    "σαγιονάρες"    ,
    "moon"    :    "φεγγάρι"    ,
    "road/street/"    :    "δρόμος / δρόμος /"    ,
    "fountain"    :    "κρήνη"    ,
    "faxmachine"    :    "συσκευή φαξ"    ,
    "hotair balloon"    :    "ζεστό μπαλόνι"    ,
    "cereal"    :    "δημητριακό"    ,
    "seahorse"    :    "seahorse"    ,
    "rocket"    :    "ρουκέτα"    ,
    "cabinets"    :    "ντουλάπια"    ,
    "basketball"    :    "μπάσκετ"    ,
    "telephone"    :    "τηλέφωνο"    ,
    "movie(disc)"    :    "ταινία (δίσκος)"    ,
    "football"    :    "ποδόσφαιρο"    ,
    "goose"    :    "χήνα"    ,
    "long-sleeve shirt"    :    "μακρυμάνικο πουκάμισο"    ,
    "short-sleeve shirt"    :    "κοντομάνικο μπλουζάκι"    ,
    "raft"    :    "σχεδία"    ,
    "rooster"    :    "πετεινός"    ,
    "copier"    :    "αντιγραφέας"    ,
    "radio"    :    "ραδιόφωνο"    ,
    "fences"    :    "φράχτες"    ,
    "goalnet"    :    "goalnet"    ,
    "toys"    :    "παιχνίδια"    ,
    "engine"    :    "κινητήρας"    ,
    "soccerball"    :    "μπάλα ποδοσφαίρου"    ,
    "fieldgoal posts"    :    "Θέσεις στο πεδίο του αγώνα"    ,
    "socks"    :    "κάλτσες"    ,
    "tennisnet"    :    "tennisnet"    ,
    "seats"    :    "καθίσματα"    ,
    "elbows"    :    "αγκώνες"    ,
    "aardvark"    :    "μυρμηγκοφάγο θηλαστικό"    ,
    "dinosaur"    :    "δεινόσαυρος"    ,
    "unicycle"    :    "unicycle"    ,
    "honey"    :    "μέλι"    ,
    "legos"    :    "legos"    ,
    "fly"    :    "πετώ"    ,
    "roof"    :    "στέγη"    ,
    "baseball"    :    "μπέιζμπολ"    ,
    "mat"    :    "χαλάκι"    ,
    "ipad"    :    "ipad"    ,
    "iphone"    :    "iphone"    ,
    "hoop"    :    "κρίκος"    ,
    "hen"    :    "κότα"    ,
    "back"    :    "πίσω"    ,
    "table cloth"    :    "τραπεζομάντιλο"    ,
    "soccer nets"    :    "δίχτυα ποδοσφαίρου"    ,
    "turkey"    :    "Τουρκία"    ,
    "pajamas"    :    "πιζάμες"    ,
    "underpants"    :    "σώβρακο"    ,
    "goldfish"    :    "χρυσόψαρο"    ,
    "robot"    :    "ρομπότ"    ,
    "crusher"    :    "συντρίβων"    ,
    "animal crackers"    :    "κροτίδες ζώων"    ,
    "basketball court"    :    "γήπεδο του μπάσκετ"    ,
    "horn"    :    "κέρατο"    ,
    "firefly"    :    "πυγολαμπίδα"    ,
    "armpits"    :    "μασχάλες"    ,
    "nectar"    :    "νέκταρ"    ,
    "superhero costume"    :    "κοστούμι υπερήρωα"    ,
    "jetpack"    :    "jetpack"    ,
    "robots"    :    "ρομπότ"
]
