//
//  italian.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-28.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let italian = [
    "person"    :    "persona"    ,
    "bicycle"    :    "bicicletta"    ,
    "car"    :    "auto"    ,
    "motorcycle"    :    "motociclo"    ,
    "bird"    :    "uccello"    ,
    "cat"    :    "gatto"    ,
    "dog"    :    "cane"    ,
    "horse"    :    "cavallo"    ,
    "sheep"    :    "pecora"    ,
    "bottle"    :    "bottiglia"    ,
    "chair"    :    "sedia"    ,
    "couch"    :    "divano"    ,
    "potted plant"    :    "pianta in vaso"    ,
    "tv"    :    "tv"    ,
    "cow"    :    "mucca"    ,
    "airplane"    :    "aereo"    ,
    "hat"    :    "cappello"    ,
    "license plate"    :    "targa"    ,
    "bed"    :    "letto"    ,
    "laptop"    :    "il computer portatile"    ,
    "fridge"    :    "frigo"    ,
    "microwave"    :    "microonde"    ,
    "sink"    :    "Lavello"    ,
    "oven"    :    "forno"    ,
    "toaster"    :    "tostapane"    ,
    "bus"    :    "autobus"    ,
    "train"    :    "treno"    ,
    "mirror"    :    "specchio"    ,
    "dining table"    :    "tavolo da pranzo"    ,
    "elephant"    :    "elefante"    ,
    "banana"    :    "Banana"    ,
    "bread"    :    "pane"    ,
    "toilet"    :    "gabinetto"    ,
    "book"    :    "libro"    ,
    "boat"    :    "barca"    ,
    "plate"    :    "piatto"    ,
    "cellphone"    :    "cellulare"    ,
    "mouse"    :    "topo"    ,
    "remote"    :    "a distanza"    ,
    "clock"    :    "orologio"    ,
    "face"    :    "viso"    ,
    "hand"    :    "mano"    ,
    "apple"    :    "Mela"    ,
    "keyboard"    :    "tastiera"    ,
    "backpack"    :    "zaino"    ,
    "steering wheel"    :    "volante"    ,
    "wineglass"    :    "bicchiere di vino"    ,
    "chicken"    :    "pollo"    ,
    "zebra"    :    "zebra"    ,
    "shoe"    :    "scarpa"    ,
    "eye"    :    "occhio"    ,
    "mouth"    :    "bocca"    ,
    "scissors"    :    "forbici"    ,
    "truck"    :    "camion"    ,
    "traffic light"    :    "semaforo"    ,
    "eyeglasses"    :    "occhiali"    ,
    "cup"    :    "tazza"    ,
    "blender"    :    "miscelatore"    ,
    "hairdrier"    :    "asciugacapelli"    ,
    "wheel"    :    "ruota"    ,
    "streetsign"    :    "segnale stradale"    ,
    "umbrella"    :    "ombrello"    ,
    "door"    :    "porta"    ,
    "firehydrant"    :    "idrante"    ,
    "bowl"    :    "ciotola"    ,
    "teapot"    :    "teiera"    ,
    "fork"    :    "forchetta"    ,
    "knife"    :    "coltello"    ,
    "spoon"    :    "cucchiaio"    ,
    "bear"    :    "orso"    ,
    "headlights"    :    "fari"    ,
    "window"    :    "finestra"    ,
    "desk"    :    "scrivania"    ,
    "computer"    :    "computer"    ,
    "refrigerator"    :    "frigorifero"    ,
    "pizza"    :    "Pizza"    ,
    "squirrel"    :    "scoiattolo"    ,
    "duck"    :    "anatra"    ,
    "frisbee"    :    "frisbee"    ,
    "guitar"    :    "chitarra"    ,
    "nose"    :    "naso"    ,
    "teddybear"    :    "orsacchiotto di peluche"    ,
    "tie"    :    "cravatta"    ,
    "stopsign"    :    "segnale di stop"    ,
    "surfboard"    :    "tavola da surf"    ,
    "sandwich"    :    "Sandwich"    ,
    "pen/pencil"    :    "penna matita"    ,
    "kite"    :    "aquilone"    ,
    "orange"    :    "arancia"    ,
    "toothbrush"    :    "spazzolino da denti"    ,
    "printer"    :    "stampante"    ,
    "pans"    :    "padelle"    ,
    "head"    :    "capo"    ,
    "sports ball"    :    "palla sportiva"    ,
    "broccoli"    :    "broccoli"    ,
    "suitcase"    :    "valigia"    ,
    "carrot"    :    "carota"    ,
    "chandelier"    :    "lampadario"    ,
    "parking meter"    :    "parchimetro"    ,
    "fish"    :    "pesce"    ,
    "handbag"    :    "borsetta"    ,
    "hotdog"    :    "hot dog"    ,
    "stapler"    :    "cucitrice"    ,
    "basketball hoop"    :    "canestro"    ,
    "donut"    :    "ciambella"    ,
    "vase"    :    "vaso"    ,
    "baseball bat"    :    "Mazza da baseball"    ,
    "baseball glove"    :    "guanto da baseball"    ,
    "giraffe"    :    "giraffa"    ,
    "jacket"    :    "giacca"    ,
    "skis"    :    "sci"    ,
    "snowboard"    :    "Snowboard"    ,
    "tablelamp"    :    "lampada da tavolo"    ,
    "egg"    :    "uovo"    ,
    "door handle"    :    "maniglia"    ,
    "power outlet"    :    "presa di corrente"    ,
    "hair"    :    "capelli"    ,
    "tiger"    :    "tigre"    ,
    "table"    :    "tavolo"    ,
    "coffee table"    :    "tavolino da caffè"    ,
    "skate board"    :    "skate board"    ,
    "helicopter"    :    "elicottero"    ,
    "tomato"    :    "pomodoro"    ,
    "tree"    :    "albero"    ,
    "bunny"    :    "coniglietto"    ,
    "pillow"    :    "cuscino"    ,
    "tennis racket"    :    "racchetta da tennis"    ,
    "cake"    :    "torta"    ,
    "feet"    :    "piedi"    ,
    "bench"    :    "panchina"    ,
    "chopping board"    :    "tagliere"    ,
    "washer"    :    "rondella"    ,
    "lion"    :    "Leone"    ,
    "monkey"    :    "scimmia"    ,
    "hairbrush"    :    "spazzola per capelli"    ,
    "light switch"    :    "interruttore della luce"    ,
    "arms"    :    "braccia"    ,
    "legs"    :    "gambe"    ,
    "house"    :    "Casa"    ,
    "cheese"    :    "formaggio"    ,
    "goat"    :    "capra"    ,
    "magazine"    :    "rivista"    ,
    "key"    :    "chiave"    ,
    "picture"    :    "immagine"    ,
    "frame"    :    "telaio"    ,
    "cupcake"    :    "Cupcake"    ,
    "fan(ceil/floor)"    :    "ventilatore (ceil / piano)"    ,
    "frogs"    :    "rane"    ,
    "rabbit"    :    "coniglio"    ,
    "owl"    :    "gufo"    ,
    "scarf"    :    "sciarpa"    ,
    "ears"    :    "orecchie"    ,
    "homephone"    :    "telefono di casa"    ,
    "pig"    :    "maiale"    ,
    "strawberries"    :    "fragole"    ,
    "pumpkin"    :    "zucca"    ,
    "van"    :    "furgone"    ,
    "kangaroo"    :    "canguro"    ,
    "rhinoceros"    :    "rinoceronte"    ,
    "sailboat"    :    "barca a vela"    ,
    "deer"    :    "cervo"    ,
    "playing cards"    :    "giocando a carte"    ,
    "towel"    :    "asciugamano"    ,
    "hyppo hyppo"    :    "hyppo hyppo"    ,
    "can"    :    "può"    ,
    "dollar bill"    :    "banconota da un dollaro"    ,
    "doll"    :    "Bambola"    ,
    "soup"    :    "la minestra"    ,
    "meat"    :    "carne"    ,
    "muffins"    :    "muffin"    ,
    "tire"    :    "pneumatico"    ,
    "necklace"    :    "collana"    ,
    "tablet"    :    "tavoletta"    ,
    "corn"    :    "Mais"    ,
    "ladder"    :    "scala"    ,
    "pineapple"    :    "ananas"    ,
    "candle"    :    "candela"    ,
    "desktop"    :    "del desktop"    ,
    "carpet"    :    "tappeto"    ,
    "cookie"    :    "biscotto"    ,
    "toycars"    :    "macchine giocattolo"    ,
    "bracelet"    :    "braccialetto"    ,
    "bat"    :    "pipistrello"    ,
    "balloon"    :    "Palloncino"    ,
    "gloves"    :    "guanti"    ,
    "milk"    :    "latte"    ,
    "pants"    :    "pantaloni"    ,
    "wheelchair"    :    "sedia a rotelle"    ,
    "building"    :    "costruzione"    ,
    "bacon"    :    "Bacon"    ,
    "box"    :    "scatola"    ,
    "platypus"    :    "ornitorinco"    ,
    "pancake"    :    "pancake"    ,
    "cabinet"    :    "Consiglio dei ministri"    ,
    "whale"    :    "balena"    ,
    "dryer"    :    "asciugatrice"    ,
    "torso"    :    "torso"    ,
    "lizard"    :    "lucertola"    ,
    "shirt"    :    "camicia"    ,
    "shorts"    :    "pantaloncini"    ,
    "pasta"    :    "pasta"    ,
    "grapes"    :    "uva"    ,
    "shark"    :    "squalo"    ,
    "swan"    :    "cigno"    ,
    "fingers"    :    "dita"    ,
    "sidetable"    :    "tavolino"    ,
    "gate"    :    "cancello"    ,
    "beans"    :    "fagioli"    ,
    "flip flops"    :    "infradito"    ,
    "moon"    :    "Luna"    ,
    "road/street/"    :    "strada / via /"    ,
    "fountain"    :    "Fontana"    ,
    "faxmachine"    :    "fax"    ,
    "hotair balloon"    :    "mongolfiera"    ,
    "cereal"    :    "cereale"    ,
    "seahorse"    :    "cavalluccio marino"    ,
    "rocket"    :    "razzo"    ,
    "cabinets"    :    "armadietti"    ,
    "basketball"    :    "pallacanestro"    ,
    "telephone"    :    "telefono"    ,
    "movie(disc)"    :    "film (disco)"    ,
    "football"    :    "calcio"    ,
    "goose"    :    "Oca"    ,
    "long-sleeve shirt"    :    "maglia a maniche lunghe"    ,
    "short-sleeve shirt"    :    "Maglietta a maniche corte"    ,
    "raft"    :    "zattera"    ,
    "rooster"    :    "Gallo"    ,
    "copier"    :    "copista"    ,
    "radio"    :    "Radio"    ,
    "fences"    :    "recinzioni"    ,
    "goalnet"    :    "goalnet"    ,
    "toys"    :    "giocattoli"    ,
    "engine"    :    "motore"    ,
    "soccerball"    :    "palla da calcio"    ,
    "fieldgoal posts"    :    "messaggi fieldgoal"    ,
    "socks"    :    "calzini"    ,
    "tennisnet"    :    "tennisnet"    ,
    "seats"    :    "posti a sedere"    ,
    "elbows"    :    "gomiti"    ,
    "aardvark"    :    "aardvark"    ,
    "dinosaur"    :    "dinosauro"    ,
    "unicycle"    :    "monociclo"    ,
    "honey"    :    "miele"    ,
    "legos"    :    "legos"    ,
    "fly"    :    "volare"    ,
    "roof"    :    "tetto"    ,
    "baseball"    :    "baseball"    ,
    "mat"    :    "stuoia"    ,
    "ipad"    :    "ipad"    ,
    "iphone"    :    "i phone"    ,
    "hoop"    :    "cerchio"    ,
    "hen"    :    "gallina"    ,
    "back"    :    "indietro"    ,
    "table cloth"    :    "tovaglia"    ,
    "soccer nets"    :    "reti da calcio"    ,
    "turkey"    :    "tacchino"    ,
    "pajamas"    :    "pigiama"    ,
    "underpants"    :    "mutande"    ,
    "goldfish"    :    "pesce rosso"    ,
    "robot"    :    "robot"    ,
    "crusher"    :    "frantoio"    ,
    "animal crackers"    :    "cracker animali"    ,
    "basketball court"    :    "campo da basket"    ,
    "horn"    :    "corno"    ,
    "firefly"    :    "lucciola"    ,
    "armpits"    :    "ascelle"    ,
    "nectar"    :    "nettare"    ,
    "superhero costume"    :    "costume da supereroe"    ,
    "jetpack"    :    "jetpack"    ,
    "robots"    :    "robot"
]
