//
//  japanese.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-12.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let japanese = [
    "person"    :    "人"    ,
    "bicycle"    :    "自転車"    ,
    "car"    :    "車"    ,
    "motorcycle"    :    "オートバイ"    ,
    "bird"    :    "鳥"    ,
    "cat"    :    "ネコ"    ,
    "dog"    :    "犬"    ,
    "horse"    :    "うま"    ,
    "sheep"    :    "羊"    ,
    "bottle"    :    "ボトル"    ,
    "chair"    :    "椅子"    ,
    "couch"    :    "ソファー"    ,
    "potted plant"    :    "鉢植え"    ,
    "tv"    :    "テレビ"    ,
    "cow"    :    "牛"    ,
    "airplane"    :    "飛行機"    ,
    "hat"    :    "帽子"    ,
    "license plate"    :    "ナンバープレート"    ,
    "bed"    :    "ベッド"    ,
    "laptop"    :    "ラップトップ"    ,
    "fridge"    :    "冷蔵庫"    ,
    "microwave"    :    "マイクロ波"    ,
    "sink"    :    "シンク"    ,
    "oven"    :    "オーブン"    ,
    "toaster"    :    "トースター"    ,
    "bus"    :    "バス"    ,
    "train"    :    "列車"    ,
    "mirror"    :    "鏡"    ,
    "dining table"    :    "ダイニングテーブル"    ,
    "elephant"    :    "象"    ,
    "banana"    :    "バナナ"    ,
    "bread"    :    "パン"    ,
    "toilet"    :    "トイレ"    ,
    "book"    :    "本"    ,
    "boat"    :    "ボート"    ,
    "plate"    :    "プレート"    ,
    "cellphone"    :    "携帯電話"    ,
    "mouse"    :    "マウス"    ,
    "remote"    :    "遠隔の"    ,
    "clock"    :    "クロック"    ,
    "face"    :    "面"    ,
    "hand"    :    "ハンド"    ,
    "apple"    :    "林檎"    ,
    "keyboard"    :    "キーボード"    ,
    "backpack"    :    "バックパック"    ,
    "steering wheel"    :    "ハンドル"    ,
    "wineglass"    :    "ワイングラス"    ,
    "chicken"    :    "チキン"    ,
    "zebra"    :    "シマウマ"    ,
    "shoe"    :    "靴"    ,
    "eye"    :    "眼"    ,
    "mouth"    :    "口"    ,
    "scissors"    :    "はさみ"    ,
    "truck"    :    "トラック"    ,
    "traffic light"    :    "信号機"    ,
    "eyeglasses"    :    "眼鏡"    ,
    "cup"    :    "カップ"    ,
    "blender"    :    "ブレンダー"    ,
    "hairdrier"    :    "ヘアドライヤー"    ,
    "wheel"    :    "ホイール"    ,
    "streetsign"    :    "ストリートサイン"    ,
    "umbrella"    :    "傘"    ,
    "door"    :    "ドア"    ,
    "firehydrant"    :    "消火栓"    ,
    "bowl"    :    "ボウル"    ,
    "teapot"    :    "ティーポット"    ,
    "fork"    :    "フォーク"    ,
    "knife"    :    "ナイフ"    ,
    "spoon"    :    "スプーン"    ,
    "bear"    :    "くま"    ,
    "headlights"    :    "ヘッドライト"    ,
    "window"    :    "窓"    ,
    "desk"    :    "机"    ,
    "computer"    :    "コンピューター"    ,
    "refrigerator"    :    "冷蔵庫"    ,
    "pizza"    :    "ピザ"    ,
    "squirrel"    :    "リス"    ,
    "duck"    :    "アヒル"    ,
    "frisbee"    :    "フリスビー"    ,
    "guitar"    :    "ギター"    ,
    "nose"    :    "鼻"    ,
    "teddybear"    :    "テディベア"    ,
    "tie"    :    "ネクタイ"    ,
    "stopsign"    :    "一時停止標識"    ,
    "surfboard"    :    "サーフボード"    ,
    "sandwich"    :    "サンドイッチ"    ,
    "pen/pencil"    :    "ペン/鉛筆"    ,
    "kite"    :    "凧"    ,
    "orange"    :    "オレンジ"    ,
    "toothbrush"    :    "歯ブラシ"    ,
    "printer"    :    "プリンタ"    ,
    "pans"    :    "パン"    ,
    "head"    :    "頭"    ,
    "sports ball"    :    "スポーツボール"    ,
    "broccoli"    :    "ブロッコリ"    ,
    "suitcase"    :    "スーツケース"    ,
    "carrot"    :    "にんじん"    ,
    "chandelier"    :    "シャンデリア"    ,
    "parking meter"    :    "パーキングメーター"    ,
    "fish"    :    "魚"    ,
    "handbag"    :    "ハンドバッグ"    ,
    "hotdog"    :    "ホットドッグ"    ,
    "stapler"    :    "ステープラー"    ,
    "basketball hoop"    :    "バスケットボールフープ"    ,
    "donut"    :    "ドーナツ"    ,
    "vase"    :    "花瓶"    ,
    "baseball bat"    :    "野球用バット"    ,
    "baseball glove"    :    "野球手袋"    ,
    "giraffe"    :    "キリン"    ,
    "jacket"    :    "ジャケット"    ,
    "skis"    :    "スキー"    ,
    "snowboard"    :    "スノーボード"    ,
    "tablelamp"    :    "電気スタンド"    ,
    "egg"    :    "卵"    ,
    "door handle"    :    "ドアハンドル"    ,
    "power outlet"    :    "電源コンセント"    ,
    "hair"    :    "ヘア"    ,
    "tiger"    :    "虎"    ,
    "table"    :    "表"    ,
    "coffee table"    :    "コー​​ヒーテーブル"    ,
    "skate board"    :    "スケートボード"    ,
    "helicopter"    :    "ヘリコプター"    ,
    "tomato"    :    "トマト"    ,
    "tree"    :    "木"    ,
    "bunny"    :    "バニー"    ,
    "pillow"    :    "枕"    ,
    "tennis racket"    :    "テニスラケット"    ,
    "cake"    :    "ケーキ"    ,
    "feet"    :    "フィート"    ,
    "bench"    :    "ベンチ"    ,
    "chopping board"    :    "まな板"    ,
    "washer"    :    "洗濯機"    ,
    "lion"    :    "ライオン"    ,
    "monkey"    :    "モンキー"    ,
    "hairbrush"    :    "ヘアブラシ"    ,
    "light switch"    :    "電気のスイッチ"    ,
    "arms"    :    "武器"    ,
    "legs"    :    "足"    ,
    "house"    :    "家"    ,
    "cheese"    :    "チーズ"    ,
    "goat"    :    "ヤギ"    ,
    "magazine"    :    "マガジン"    ,
    "key"    :    "キー"    ,
    "picture"    :    "画像"    ,
    "frame"    :    "フレーム"    ,
    "cupcake"    :    "カップケーキ"    ,
    "fan(ceil/floor)"    :    "ファン（天井/床）"    ,
    "frogs"    :    "カエル"    ,
    "rabbit"    :    "ウサギ"    ,
    "owl"    :    "フクロウ"    ,
    "scarf"    :    "スカーフ"    ,
    "ears"    :    "耳"    ,
    "homephone"    :    "自宅の電話"    ,
    "pig"    :    "豚"    ,
    "strawberries"    :    "いちご"    ,
    "pumpkin"    :    "かぼちゃ"    ,
    "van"    :    "バン"    ,
    "kangaroo"    :    "カンガルー"    ,
    "rhinoceros"    :    "サイコロ"    ,
    "sailboat"    :    "ヨット"    ,
    "deer"    :    "鹿"    ,
    "playing cards"    :    "トランプ"    ,
    "towel"    :    "タオル"    ,
    "hyppo hyppo"    :    "ハッポハポ"    ,
    "can"    :    "できる"    ,
    "dollar bill"    :    "ドル紙幣"    ,
    "doll"    :    "人形"    ,
    "soup"    :    "スープ"    ,
    "meat"    :    "お肉"    ,
    "muffins"    :    "マフィン"    ,
    "tire"    :    "タイヤ"    ,
    "necklace"    :    "ネックレス"    ,
    "tablet"    :    "タブレット"    ,
    "corn"    :    "コーン"    ,
    "ladder"    :    "ラダー"    ,
    "pineapple"    :    "パイナップル"    ,
    "candle"    :    "キャンドル"    ,
    "desktop"    :    "デスクトップ"    ,
    "carpet"    :    "カーペット"    ,
    "cookie"    :    "クッキー"    ,
    "toycars"    :    "トカイ"    ,
    "bracelet"    :    "ブレスレット"    ,
    "bat"    :    "コウモリ"    ,
    "balloon"    :    "バルーン"    ,
    "gloves"    :    "手袋"    ,
    "milk"    :    "ミルク"    ,
    "pants"    :    "ズボン"    ,
    "wheelchair"    :    "車椅子"    ,
    "building"    :    "建物"    ,
    "bacon"    :    "ベーコン"    ,
    "box"    :    "ボックス"    ,
    "platypus"    :    "カモノハシ"    ,
    "pancake"    :    "パンケーキ"    ,
    "cabinet"    :    "キャビネット"    ,
    "whale"    :    "鯨"    ,
    "dryer"    :    "ドライヤー"    ,
    "torso"    :    "胴体"    ,
    "lizard"    :    "トカゲ"    ,
    "shirt"    :    "シャツ"    ,
    "shorts"    :    "ショートパンツ"    ,
    "pasta"    :    "パスタ"    ,
    "grapes"    :    "ブドウ"    ,
    "shark"    :    "鮫"    ,
    "swan"    :    "白鳥"    ,
    "fingers"    :    "指"    ,
    "sidetable"    :    "サイドテーブル"    ,
    "gate"    :    "ゲート"    ,
    "beans"    :    "豆"    ,
    "flip flops"    :    "ビーチサンダル"    ,
    "moon"    :    "月"    ,
    "road/street/"    :    "道路/通り/"    ,
    "fountain"    :    "噴水"    ,
    "faxmachine"    :    "ファクス"    ,
    "hotair balloon"    :    "熱気球"    ,
    "cereal"    :    "穀物"    ,
    "seahorse"    :    "シホルス"    ,
    "rocket"    :    "ロケット"    ,
    "cabinets"    :    "キャビネット"    ,
    "basketball"    :    "バスケットボール"    ,
    "telephone"    :    "電話"    ,
    "movie(disc)"    :    "映画（ディスク）"    ,
    "football"    :    "フットボール"    ,
    "goose"    :    "ガチョウ"    ,
    "long-sleeve shirt"    :    "長袖シャツ"    ,
    "short-sleeve shirt"    :    "半袖シャツ"    ,
    "raft"    :    "ラフト"    ,
    "rooster"    :    "雄鶏"    ,
    "copier"    :    "複写機"    ,
    "radio"    :    "無線"    ,
    "fences"    :    "フェンス"    ,
    "goalnet"    :    "ゴールネット"    ,
    "toys"    :    "おもちゃ"    ,
    "engine"    :    "エンジン"    ,
    "soccerball"    :    "サッカーボール"    ,
    "fieldgoal posts"    :    "フィールドゴールポスト"    ,
    "socks"    :    "靴下"    ,
    "tennisnet"    :    "テニスネット"    ,
    "seats"    :    "席"    ,
    "elbows"    :    "肘"    ,
    "aardvark"    :    "アードバーク"    ,
    "dinosaur"    :    "恐竜"    ,
    "unicycle"    :    "一輪車"    ,
    "honey"    :    "はちみつ"    ,
    "legos"    :    "レゴス"    ,
    "fly"    :    "飛ぶ"    ,
    "roof"    :    "ルーフ"    ,
    "baseball"    :    "野球"    ,
    "mat"    :    "マット"    ,
    "ipad"    :    "ipad"    ,
    "iphone"    :    "iPhone"    ,
    "hoop"    :    "フープ"    ,
    "hen"    :    "鶏"    ,
    "back"    :    "バック"    ,
    "table cloth"    :    "テーブルクロス"    ,
    "soccer nets"    :    "サッカーネット"    ,
    "turkey"    :    "七面鳥"    ,
    "pajamas"    :    "パジャマ"    ,
    "underpants"    :    "パンツ"    ,
    "goldfish"    :    "金魚"    ,
    "robot"    :    "ロボット"    ,
    "crusher"    :    "クラッシャー"    ,
    "animal crackers"    :    "動物のクラッカー"    ,
    "basketball court"    :    "バスケットボールのコート"    ,
    "horn"    :    "ホーン"    ,
    "firefly"    :    "ホタル"    ,
    "armpits"    :    "脇の下"    ,
    "nectar"    :    "ネクター"    ,
    "superhero costume"    :    "スーパーヒーローの衣装"    ,
    "jetpack"    :    "ジェットパック"    ,
    "robots"    :    "ロボット"
]
