//
//  japanese.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-12.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let japanese = [

"kit fox"    :    "キットキツネ"    ,
"English setter"    :    "英語セッター"    ,
"Australian terrier"    :    "オーストラリアのテリア"    ,
"grey whale"    :    "グレークジラ"    ,
"lesser panda"    :    "レッサーパンダ"    ,
"Egyptian cat"    :    "エジプト猫"    ,
"ibex"    :    "アイベックス"    ,
"Persian cat "    :    "ペルシャ猫"    ,
"cougar"    :    "クーガー"    ,
"gazelle "    :    "ガゼル"    ,
"porcupine"    :    "ポーキュパイン"    ,
"sea lion "    :    "アシカ"    ,
"badger "    :    "狸"    ,
"Great Dane "    :    "グレートデーン"    ,
"Scottish deerhound"    :    "スコットランドのディアハンド"    ,
"killer whale"    :    "シャチ"    ,
"mink "    :    "ミンク"    ,
"African elephant"    :    "アフリカゾウ"    ,
"red wolf"    :    "レッドウルフ"    ,
"jaguar"    :    "ジャガー"    ,
"hyena"    :    "ハイエナ"    ,
"titi"    :    "ティティ"    ,
"three-toed sloth"    :    "3つのつまようじ"    ,
"sorrel "    :    "栗色"    ,
"black-footed ferret"    :    "黒い足のフェレット"    ,
"dalmatian"    :    "ダルメシアン"    ,
"Staffordshire bullterrier"    :    "スタフォードシャーブルター"    ,
"Bouvier des Flandres"    :    "ブーヴィエ・デ・フランドル"    ,
"weasel "    :    "イタチ"    ,
"miniature poodle "    :    "ミニチュアプードル"    ,
"bighorn"    :    "ビッグホーン"    ,
"fox squirrel"    :    "キツネ"    ,
"colobus"    :    "コロバス"    ,
"tiger cat "    :    "トラの猫"    ,
"impala"    :    "インパラ"    ,
"coyote"    :    "コヨーテ"    ,
"Yorkshire terrier "    :    "ヨークシャーテリア"    ,
"Newfoundland"    :    "ニューファンドランド"    ,
"red fox"    :    "レッドキツネ"    ,
"hartebeest "    :    "ハートビースト"    ,
"grey fox"    :    "グレイキツネ"    ,
"Pekinese"    :    "狆"    ,
"guenon"    :    "グエノン"    ,
"mongoose "    :    "マングース"    ,
"indri"    :    "インドリ"    ,
"tiger"    :    "虎"    ,
"wild boar"    :    "イノシシ"    ,
"zebra "    :    "シマウマ"    ,
"ram"    :    "RAM"    ,
"orangutan"    :    "オランウータン"    ,
"basenji "    :    "バステンジ"    ,
"leopard"    :    "ヒョウ"    ,
"vizsla"    :    "ヴィズラ"    ,
"squirrel monkey"    :    "リスザル"    ,
"Siamese cat"    :    "シャムネコ"    ,
"chimpanzee"    :    "チンパンジー"    ,
"komondor "    :    "コモンドール"    ,
"proboscis monkey"    :    "鼻猿"    ,
"guinea pig"    :    "モルモット"    ,
"white wolf"    :    "白いオオカミ"    ,
"ice bear"    :    "アイスクマ"    ,
"gorilla"    :    "ゴリラ"    ,
"ox "    :    "牛"    ,
"Tibetan mastiff "    :    "チベタン・マスティフ"    ,
"spider monkey"    :    "クモザル"    ,
"Doberman"    :    "ドーベルマン"    ,
"warthog "    :    "ワトグ"    ,
"Arabian camel"    :    "アラビアのラクダ"    ,
"siamang"    :    "シアマン"    ,
"golden retriever "    :    "ゴールデンレトリバー"    ,
"Border collie "    :    "ボーダーコリー"    ,
"hare "    :    "野ウサギ"    ,
"boxer "    :    "ボクサー"    ,
"patas"    :    "パテ"    ,
"baboon "    :    "ヒヒ"    ,
"macaque "    :    "マカク"    ,
"capuchin"    :    "カピュチン"    ,
"flat-coated retriever "    :    "フラットコートレトリーバー"    ,
"hog"    :    "豚"    ,
"Eskimo dog"    :    "エスキモードッグ"    ,
"Brittany spaniel "    :    "ブルターニュスパニエル"    ,
"dial telephone"    :    "ダイヤル電話"    ,
"maze"    :    "迷路"    ,
"Gordon setter "    :    "ゴードンセッター"    ,
"dingo"    :    "ディンゴ"    ,
"hamster "    :    "ハムスター"    ,
"Arctic fox"    :    "ホッキョクギツネ"    ,
"water buffalo"    :    "水牛"    ,
"American black bear"    :    "アメリカ黒熊"    ,
"Angora"    :    "アンゴラ"    ,
"bison "    :    "バイソン"    ,
"howler monkey"    :    "ハウラーサル"    ,
"hippopotamus"    :    "カバ"    ,
"giant panda"    :    "ジャイアントパンダ"    ,
"tabby"    :    "タブビー"    ,
"marmoset "    :    "マーモセット"    ,
"Saint Bernard"    :    "セントバーナード"    ,
"armadillo "    :    "アルマジロ"    ,
"redbone "    :    "レッドボーン"    ,
"polecat"    :    "ポレアット"    ,
"marmot "    :    "マモット"    ,
"gibbon"    :    "テントウムシ"    ,
"llama "    :    "ラマ"    ,
"wood rabbit"    :    "ウッドウサギ"    ,
"lion"    :    "ライオン"    ,
"Irish setter"    :    "アイリッシュセッター"    ,
"dugong"    :    "ジュゴン"    ,
"Indian elephant"    :    "インドの象"    ,
"beaver "    :    "ビーバー"    ,
"Madagascar cat"    :    "マダガスカル猫"    ,
"Rhodesian ridgeback "    :    "Rhodesian ridgeback"    ,
"lynx"    :    "Lynx"    ,
"African hunting dog"    :    "アフリカの狩猟犬"    ,
"langur "    :    "ラングール"    ,
"timber wolf"    :    "木材オオカミ"    ,
"cheetah"    :    "チーター"    ,
"sloth bear"    :    "ナマケモノ"    ,
"German shepherd"    :    "ジャーマンシェパード"    ,
"otter "    :    "オッター"    ,
"koala"    :    "コアラ"    ,
"tusker "    :    "タスカー"    ,
"echidna"    :    "エキドナ"    ,
"wallaby"    :    "ワラビー"    ,
"platypus"    :    "カモノハシ"    ,
"wombat "    :    "ウォンバット"    ,
"revolver"    :    "リボルバー"    ,
"umbrella "    :    "傘"    ,
"schooner "    :    "スクーナー"    ,
"soccer ball "    :    "サッカーボール"    ,
"accordion"    :    "アコーディオン"    ,
"ant"    :    "蟻"    ,
"starfish"    :    "ヒトデ"    ,
"chambered nautilus"    :    "芝生のノーチラス"    ,
"grand piano"    :    "グランドピアノ"    ,
"laptop"    :    "ラップトップ"    ,
"strawberry "    :    "イチゴ"    ,
"airliner "    :    "旅客機"    ,
"warplane"    :    "戦闘機"    ,
"airship"    :    "飛行船"    ,
"balloon "    :    "バルーン"    ,
"space shuttle "    :    "スペースシャトル"    ,
"fireboat "    :    "消防船"    ,
"gondola "    :    "ゴンドラ"    ,
"speedboat "    :    "スピードボート"    ,
"lifeboat "    :    "救命艇"    ,
"canoe "    :    "カヌー"    ,
"yawl "    :    "ヨウル"    ,
"catamaran "    :    "カタマラン"    ,
"trimaran "    :    "トリマラン"    ,
"container ship"    :    "コンテナ船"    ,
"liner"    :    "ライナー"    ,
"pirate"    :    "海賊"    ,
"aircraft carrier"    :    "空母"    ,
"submarine"    :    "潜水艦"    ,
"wreck "    :    "難破"    ,
"half track "    :    "半トラック"    ,
"tank"    :    "タンク"    ,
"missile "    :    "ミサイル"    ,
"bobsled"    :    "ボブスレー"    ,
"dogsled"    :    "犬ぞり"    ,
"bicycle-built-for-two"    :    "二輪車用自転車"    ,
"mountain bike"    :    "マウンテンバイク"    ,
"freight car "    :    "貨車"    ,
"passenger car"    :    "乗用車"    ,
"barrow"    :    "手押し車"    ,
"shopping cart "    :    "ショッピングカート"    ,
"motor scooter"    :    "スクーター"    ,
"forklift "    :    "フォークリフト"    ,
"electric locomotive "    :    "電気機関車"    ,
"steam locomotive "    :    "蒸気機関車"    ,
"amphibian"    :    "両生類"    ,
"ambulance "    :    "救急車"    ,
"beach wagon"    :    "ビーチワゴン"    ,
"cab"    :    "タクシー"    ,
"convertible "    :    "コンバーチブル"    ,
"jeep"    :    "ジープ"    ,
"limousine"    :    "リムジン"    ,
"minivan "    :    "ミニバン"    ,
"Model T "    :    "モデルT"    ,
"racer"    :    "レーサー"    ,
"sports car"    :    "スポーツカー"    ,
"go-kart "    :    "ゴーカート"    ,
"golfcart"    :    "ゴルフカート"    ,
"moped "    :    "モペット"    ,
"snowplow"    :    "除雪機"    ,
"fire engine"    :    "消防車"    ,
"garbage truck"    :    "ごみ収集車"    ,
"pickup"    :    "拾う"    ,
"tow truck"    :    "牽引車"    ,
"trailer truck"    :    "トレーラートラック"    ,
"moving van "    :    "動いているバン"    ,
"police van"    :    "警察のバン"    ,
"recreational vehicle"    :    "RV車"    ,
"streetcar"    :    "街頭車"    ,
"snowmobile "    :    "スノーモービル"    ,
"tractor "    :    "トラクター"    ,
"mobile home"    :    "移動住宅"    ,
"tricycle"    :    "三輪車"    ,
"unicycle"    :    "一輪車"    ,
"horse cart"    :    "馬車"    ,
"mosquito net "    :    "蚊帳"    ,
"oxcart "    :    "牛車"    ,
"bassinet "    :    "バセット"    ,
"cradle "    :    "受け台"    ,
"crib"    :    "ベビーベッド"    ,
"four-poster "    :    "四柱"    ,
"bookcase "    :    "本棚"    ,
"china cabinet"    :    "中国キャビネット"    ,
"medicine chest"    :    "薬箱"    ,
"chiffonier"    :    "シフォニエ"    ,
"table lamp "    :    "電気スタンド"    ,
"file"    :    "ファイル"    ,
"pay-phone"    :    "有料電話"    ,
"park bench "    :    "公園のベンチ"    ,
"barber chair "    :    "理髪椅子"    ,
"throne "    :    "王位"    ,
"folding chair "    :    "折りたたみ椅子"    ,
"rocking chair"    :    "ロッキングチェア"    ,
"studio couch"    :    "スタジオソファ"    ,
"toilet seat "    :    "便座"    ,
"desk "    :    "机"    ,
"pool table"    :    "ビリヤード台"    ,
"dining table"    :    "ダイニングテーブル"    ,
"entertainment center "    :    "エンターテイメントセンター"    ,
"wardrobe"    :    "ワードローブ"    ,
"Granny Smith "    :    "グラニースミス"    ,
"orange "    :    "オレンジ"    ,
"lemon "    :    "レモン"    ,
"fig "    :    "イチジク"    ,
"pineapple"    :    "パイナップル"    ,
"banana "    :    "バナナ"    ,
"jackfruit"    :    "ジャックフルーツ"    ,
"custard apple "    :    "カスタードアップル"    ,
"pomegranate "    :    "ザクロ"    ,
"acorn "    :    "ドングリ"    ,
"hip"    :    "ヒップ"    ,
"ear"    :    "耳"    ,
"rapeseed "    :    "菜種"    ,
"corn "    :    "コーン"    ,
"buckeye"    :    "ブライキー"    ,
"organ"    :    "器官"    ,
"upright"    :    "直立"    ,
"chime"    :    "チャイム"    ,
"drum"    :    "ドラム"    ,
"gong"    :    "ゴング"    ,
"maraca "    :    "マラカス"    ,
"marimba"    :    "マリンバ"    ,
"steel drum "    :    "スチールドラム"    ,
"banjo "    :    "バンジョー"    ,
"cello"    :    "チェロ"    ,
"lampshade"    :    "ランプシェード"    ,
"harp "    :    "ハープ"    ,
"acoustic guitar "    :    "アコースティックギター"    ,
"electric guitar "    :    "エレキギター"    ,
"cornet"    :    "コルネット"    ,
"French horn"    :    "フレンチホルン"    ,
"trombone "    :    "トロンボーン"    ,
"harmonica"    :    "ハーモニカ"    ,
"ocarina"    :    "オカリナ"    ,
"panpipe"    :    "パンパイプ"    ,
"bassoon "    :    "ファゴット"    ,
"sax"    :    "サックス"    ,
"flute"    :    "フルート"    ,
"daisy "    :    "デイジー"    ,
"yellow lady's slipper"    :    "黄色の女性のスリッパ"    ,
"cliff"    :    "崖"    ,
"valley"    :    "谷"    ,
"alp "    :    "アルプ"    ,
"volcano "    :    "火山"    ,
"promontory"    :    "岬"    ,
"sandbar"    :    "サンドバー"    ,
"coral reef "    :    "サンゴ礁"    ,
"lakeside"    :    "湖畔"    ,
"seashore"    :    "海岸"    ,
"geyser "    :    "間欠泉"    ,
"hatchet "    :    "帽子"    ,
"cleaver"    :    "刈り取り機"    ,
"letter opener"    :    "レターオープナー"    ,
"plane"    :    "飛行機"    ,
"power drill "    :    "パワードリル"    ,
"lawn mower"    :    "芝刈り機"    ,
"hammer "    :    "ハンマー"    ,
"corkscrew"    :    "コルクスクリュー"    ,
"can opener"    :    "缶切り"    ,
"plunger"    :    "プランジャ"    ,
"screwdriver "    :    "ドライバー"    ,
"shovel "    :    "シャベル"    ,
"plow"    :    "鋤"    ,
"chain saw"    :    "チェーンソー"    ,
"cock "    :    "コック"    ,
"hen "    :    "鶏"    ,
"ostrich"    :    "ダチョウ"    ,
"brambling"    :    "喧嘩"    ,
"goldfinch"    :    "ゴールドフィンチ"    ,
"house finch"    :    "ハウスフィンチ"    ,
"junco"    :    "ジュンコ"    ,
"indigo bunting"    :    "インジゴの房"    ,
"robin"    :    "ロビン"    ,
"bulbul "    :    "バルブル"    ,
"jay "    :    "ジェイ"    ,
"magpie "    :    "カササギ"    ,
"chickadee "    :    "チョコレート"    ,
"water ouzel"    :    "ウォーターウーゼル"    ,
"kite "    :    "凧"    ,
"bald eagle"    :    "白頭ワシ"    ,
"vulture "    :    "コンドル"    ,
"great grey owl"    :    "グレイ・グレイ・フクロウ"    ,
"black grouse "    :    "黒いグラウス"    ,
"ptarmigan "    :    "雷鳥"    ,
"ruffed grouse"    :    "ラフなグラウス"    ,
"prairie chicken"    :    "プレーリーチキン"    ,
"peacock "    :    "孔雀"    ,
"quail "    :    "ウズラ"    ,
"partridge "    :    "刺青"    ,
"African grey"    :    "アフリカングレー"    ,
"macaw "    :    "マコ"    ,
"sulphur-crested cockatoo"    :    "硫黄冠のココア"    ,
"lorikeet "    :    "イチョウ"    ,
"coucal "    :    "クーカル"    ,
"bee eater "    :    "ハチ食べる人"    ,
"hornbill "    :    "ホーンビル"    ,
"hummingbird "    :    "ハチドリ"    ,
"jacamar "    :    "ジャカルタ"    ,
"toucan "    :    "トカカク"    ,
"drake "    :    "ドレーク"    ,
"red-breasted merganser"    :    "レッドブラッドマージン"    ,
"goose "    :    "ガチョウ"    ,
"black swan"    :    "黒い白鳥"    ,
"white stork"    :    "白鳥"    ,
"black stork"    :    "黒コウノトリ"    ,
"spoonbill "    :    "スプーンビル"    ,
"flamingo "    :    "フラミンゴ"    ,
"American egret"    :    "アメリカのエゴ"    ,
"little blue heron"    :    "リトルブルーヘロン"    ,
"bittern "    :    "さつき"    ,
"limpkin"    :    "リンプキン"    ,
"American coot"    :    "アメリカンコットン"    ,
"bustard "    :    "バスター"    ,
"ruddy turnstone"    :    "珍しいターンストーン"    ,
"red-backed sandpiper"    :    "赤いサンドイッチ"    ,
"redshank"    :    "赤シャンク"    ,
"dowitcher "    :    "ドーヴィッチャー"    ,
"oystercatcher"    :    "オイスターキャッチャー"    ,
"European gallinule"    :    "ヨーロッパの卒業生"    ,
"pelican "    :    "ペリカン"    ,
"king penguin"    :    "キングペンギン"    ,
"albatross"    :    "アルバトロス"    ,
"great white shark"    :    "偉大な白いサメ"    ,
"tiger shark"    :    "イタチザメ"    ,
"hammerhead"    :    "ハンマーヘッド"    ,
"electric ray"    :    "電気線"    ,
"stingray "    :    "スティングレイ"    ,
"barracouta"    :    "バラクーダ"    ,
"coho"    :    "コホ"    ,
"tench"    :    "テンチ"    ,
"goldfish"    :    "金魚"    ,
"eel "    :    "ウナギ"    ,
"rock beauty"    :    "岩の美しさ"    ,
"anemone fish "    :    "アネモネ魚"    ,
"lionfish "    :    "ライオンフィッシュ"    ,
"puffer"    :    "ふくらはぎ"    ,
"sturgeon "    :    "チョウザメ"    ,
"gar"    :    "ガー"    ,
"loggerhead"    :    "ロガーヘッド"    ,
"mud turtle "    :    "マッドタートル"    ,
"terrapin "    :    "テラピン"    ,
"box turtle"    :    "ボックスカメ"    ,
"banded gecko "    :    "帯状ゲッコ"    ,
"common iguana"    :    "一般的なイグアナ"    ,
"American chameleon"    :    "アメリカンカメレオン"    ,
"whiptail"    :    "ウィッペイル"    ,
"agama "    :    "アガマ"    ,
"frilled lizard"    :    "フライドトカゲ"    ,
"alligator lizard "    :    "ワニのトカゲ"    ,
"Gila monster"    :    "ギラモンスター"    ,
"green lizard"    :    "グリーントカゲ"    ,
"African chameleon"    :    "アフリカのカメレオン"    ,
"Komodo dragon"    :    "コモドドラゴン"    ,
"triceratops "    :    "トリケラトプス"    ,
"African crocodile"    :    "アフリカワニ"    ,
"American alligator"    :    "アメリカのワニ"    ,
"thunder snake"    :    "雷のヘビ"    ,
"ringneck snake"    :    "リングネックヘビ"    ,
"hognose snake"    :    "ホーノースヘビ"    ,
"green snake"    :    "グリーンヘビ"    ,
"king snake"    :    "キングヘビ"    ,
"garter snake"    :    "ガーターヘビ"    ,
"water snake "    :    "水スネーク"    ,
"vine snake "    :    "ブドウの蛇"    ,
"night snake"    :    "夜のヘビ"    ,
"boa constrictor"    :    "ボア収縮器"    ,
"rock python"    :    "ロックパイソン"    ,
"Indian cobra"    :    "インドのコブラ"    ,
"green mamba "    :    "グリーンマンバ"    ,
"sea snake "    :    "海の蛇"    ,
"horned viper"    :    "角笛"    ,
"stone wall "    :    "石垣"    ,
"sidewinder"    :    "サイドインダー"    ,
"European fire salamander"    :    "ヨーロッパの火災のサラマンダー"    ,
"common newt"    :    "コモン・ニュート"    ,
"eft "    :    "EFT"    ,
"spotted salamander"    :    "斑点を付けられたサラマンダー"    ,
"axolotl"    :    "アコロット"    ,
"bullfrog"    :    "ウシガエル"    ,
"tree frog"    :    "木のカエル"    ,
"tailed frog"    :    "テールカエル"    ,
"whistle "    :    "ホイッスル"    ,
"wing "    :    "翼"    ,
"paintbrush "    :    "絵筆"    ,
"oxygen mask "    :    "酸素マスク"    ,
"snorkel "    :    "スノーケル"    ,
"loudspeaker"    :    "ラウドスピーカー"    ,
"microphone"    :    "マイクロフォン"    ,
"screen"    :    "画面"    ,
"mouse"    :    "マウス"    ,
"electric fan"    :    "扇風機"    ,
"oil filter "    :    "オイルフィルター"    ,
"strainer "    :    "ストレーナー"    ,
"space heater "    :    "スペースヒーター"    ,
"stove "    :    "レンジ"    ,
"guillotine "    :    "ギロチン"    ,
"barometer "    :    "バロメーター"    ,
"rule"    :    "ルール"    ,
"odometer"    :    "オドメーター"    ,
"scale"    :    "規模"    ,
"analog clock "    :    "アナログクロック"    ,
"digital clock "    :    "デジタル時計"    ,
"wall clock "    :    "壁時計"    ,
"hourglass "    :    "砂時計"    ,
"sundial "    :    "日時計"    ,
"parking meter "    :    "パーキングメーター"    ,
"stopwatch"    :    "ストップウォッチ"    ,
"digital watch "    :    "デジタル腕時計"    ,
"stethoscope "    :    "聴診器"    ,
"syringe "    :    "シリンジ"    ,
"magnetic compass "    :    "方位磁針"    ,
"binoculars"    :    "双眼鏡"    ,
"projector "    :    "プロジェクター"    ,
"sunglasses"    :    "サングラス"    ,
"loupe"    :    "ルーペ"    ,
"radio telescope"    :    "電波望遠鏡"    ,
"bow "    :    "弓"    ,
"cannon "    :    "大砲"    ,
"assault rifle"    :    "アサルトライフル"    ,
"rifle "    :    "ライフル"    ,
"projectile"    :    "発射体"    ,
"computer keyboard"    :    "キーボード"    ,
"typewriter keyboard "    :    "タイプライターキーボード"    ,
"crane "    :    "クレーン"    ,
"lighter"    :    "ライター"    ,
"abacus "    :    "そろばん"    ,
"cash machine"    :    "現金自動販売機"    ,
"slide rule"    :    "スライドルール"    ,
"desktop computer "    :    "デスクトップコンピューター"    ,
"hand-held computer"    :    "携帯情報端末"    ,
"notebook"    :    "ノート"    ,
"padlock "    :    "南京錠"    ,
"harvester"    :    "収穫機"    ,
"thresher"    :    "脱穀機"    ,
"printer "    :    "プリンタ"    ,
"slot"    :    "スロット"    ,
"vending machine "    :    "自動販売機"    ,
"sewing machine "    :    "ミシン"    ,
"joystick "    :    "ジョイスティック"    ,
"switch"    :    "スイッチ"    ,
"hook"    :    "フック"    ,
"car wheel "    :    "車輪"    ,
"paddlewheel"    :    "パドルホイール"    ,
"pinwheel "    :    "ピンホイール"    ,
"potter's wheel "    :    "陶器の輪"    ,
"gas pump"    :    "ガスポンプ"    ,
"carousel"    :    "カルーセル"    ,
"swing "    :    "スイング"    ,
"reel "    :    "リール"    ,
"radiator "    :    "ラジエーター"    ,
"puck"    :    "パック"    ,
"hard disc"    :    "ハードディスク"    ,
"sunglass "    :    "サングラス"    ,
"pick"    :    "ピック"    ,
"car mirror "    :    "車のミラー"    ,
"solar dish"    :    "ソーラーディッシュ"    ,
"remote control"    :    "リモコン"    ,
"disk brake"    :    "ディスクブレーキ"    ,
"buckle "    :    "バックル"    ,
"hair slide "    :    "ヘアスライド"    ,
"knot "    :    "結び目"    ,
"combination lock "    :    "コンビネーションロック"    ,
"web site"    :    "ウェブサイト"    ,
"nail "    :    "ネイル"    ,
"safety pin "    :    "安全ピン"    ,
"screw "    :    "スクリュー"    ,
"muzzle "    :    "銃口"    ,
"seat belt"    :    "シートベルト"    ,
"ski "    :    "スキー"    ,
"candle"    :    "キャンドル"    ,
"jack-o'-lantern "    :    "ジャック・オ・ランタン"    ,
"spotlight"    :    "スポットライト"    ,
"torch "    :    "トーチ"    ,
"neck brace "    :    "首のブレース"    ,
"pier "    :    "桟橋"    ,
"tripod "    :    "三脚"    ,
"maypole "    :    "メイポール"    ,
"hand blower"    :    "ハンドブロアー"    ,
"mousetrap "    :    "マウストラップ"    ,
"spider web"    :    "スパイダーウェブ"    ,
"trilobite "    :    "三葉虫"    ,
"harvestman"    :    "ハーベストマン"    ,
"scorpion "    :    "サソリ"    ,
"black and gold garden spider"    :    "黒とゴールドガーデンスパイダー"    ,
"barn spider"    :    "納屋の蜘蛛"    ,
"garden spider"    :    "ガーデンスパイダー"    ,
"black widow"    :    "黒未亡人"    ,
"tarantula "    :    "タランチュラ"    ,
"wolf spider"    :    "オオカミクモ"    ,
"tick "    :    "ダニ"    ,
"centipede "    :    "ムカデ"    ,
"isopod "    :    "アイソポッド"    ,
"Dungeness crab"    :    "ダンゲネスカニ"    ,
"rock crab"    :    "ロックカニ"    ,
"fiddler crab "    :    "フィドラーカニ"    ,
"king crab"    :    "キングダム"    ,
"American lobster"    :    "アメリカンロブスター"    ,
"spiny lobster"    :    "スパイロブスター"    ,
"crayfish"    :    "ザリガニ"    ,
"hermit crab "    :    "ヤドカリ"    ,
"tiger beetle "    :    "タイガービートル"    ,
"ladybug"    :    "ミツバチ"    ,
"ground beetle"    :    "甲虫"    ,
"long-horned beetle"    :    "長い角甲虫"    ,
"leaf beetle"    :    "リーフビートル"    ,
"dung beetle "    :    "糞便"    ,
"rhinoceros beetle "    :    "サイのカブトムシ"    ,
"weevil "    :    "ゾウムシ"    ,
"fly "    :    "飛ぶ"    ,
"bee "    :    "蜂"    ,
"grasshopper"    :    "バッタ"    ,
"cricket "    :    "クリケット"    ,
"walking stick"    :    "歩く棒"    ,
"cockroach"    :    "ゴキブリ"    ,
"mantis"    :    "マイマイ"    ,
"cicada"    :    "蝉"    ,
"leafhopper "    :    "ヨコバイ"    ,
"lacewing"    :    "猛禽"    ,
"dragonfly"    :    "トンボ"    ,
"damselfly "    :    "ダンサーリー"    ,
"admiral "    :    "提督"    ,
"ringlet"    :    "リングレット"    ,
"monarch"    :    "君主"    ,
"cabbage butterfly "    :    "キャベツ蝶"    ,
"sulphur butterfly"    :    "硫黄蝶"    ,
"lycaenid"    :    "ライセネイド"    ,
"jellyfish "    :    "クラゲ"    ,
"sea anemone"    :    "アネモネ"    ,
"brain coral "    :    "脳サンゴ"    ,
"flatworm"    :    "フラットワーム"    ,
"nematode"    :    "線虫"    ,
"conch "    :    "コーチ"    ,
"snail "    :    "カタツムリ"    ,
"slug "    :    "スラグ"    ,
"sea slug"    :    "ウミウシ"    ,
"chiton"    :    "キトン"    ,
"sea urchin "    :    "うに"    ,
"sea cucumber"    :    "ナマコ"    ,
"iron"    :    "鉄"    ,
"espresso maker "    :    "エスプレッソメーカー"    ,
"microwave"    :    "マイクロ波"    ,
"Dutch oven "    :    "オランダオーブン"    ,
"rotisserie "    :    "ロティサリー"    ,
"toaster "    :    "トースター"    ,
"waffle iron "    :    "ワッフル焼き型"    ,
"vacuum"    :    "真空"    ,
"dishwasher"    :    "食器洗い機"    ,
"refrigerator"    :    "冷蔵庫"    ,
"washer"    :    "洗濯機"    ,
"Crock Pot "    :    "クロークポット"    ,
"frying pan"    :    "フライパン"    ,
"wok "    :    "ウォック"    ,
"caldron"    :    "釜"    ,
"coffeepot "    :    "コーヒーポット"    ,
"teapot "    :    "ティーポット"    ,
"spatula "    :    "スパチュラ"    ,
"altar "    :    "祭壇"    ,
"triumphal arch "    :    "凱旋門"    ,
"patio"    :    "パティオ"    ,
"steel arch bridge "    :    "スチールアーチ橋"    ,
"suspension bridge "    :    "吊橋"    ,
"viaduct "    :    "高架橋"    ,
"barn "    :    "納屋"    ,
"greenhouse"    :    "温室"    ,
"palace "    :    "宮殿"    ,
"monastery "    :    "修道院"    ,
"library "    :    "としょうかん"    ,
"apiary"    :    "養子縁組"    ,
"boathouse "    :    "ボートハウス"    ,
"church"    :    "教会"    ,
"mosque "    :    "モスク"    ,
"stupa"    :    "ストゥパ"    ,
"planetarium "    :    "プラネタリウム"    ,
"restaurant"    :    "レストラン"    ,
"cinema"    :    "シネマ"    ,
"home theater"    :    "ホームシアター"    ,
"lumbermill"    :    "製材"    ,
"coil"    :    "コイル"    ,
"obelisk "    :    "オベリスク"    ,
"totem pole "    :    "トーテムポール"    ,
"castle "    :    "城"    ,
"prison"    :    "刑務所"    ,
"grocery store"    :    "食料品店"    ,
"bakery"    :    "ベーカリー"    ,
"barbershop "    :    "理髪店"    ,
"bookshop"    :    "書店"    ,
"butcher shop"    :    "精肉店"    ,
"confectionery"    :    "菓子"    ,
"shoe shop"    :    "靴屋"    ,
"tobacco shop"    :    "タバコショップ"    ,
"toyshop "    :    "玩具屋"    ,
"fountain "    :    "噴水"    ,
"cliff dwelling "    :    "崖の住居"    ,
"yurt "    :    "ユート"    ,
"dock"    :    "ドック"    ,
"brass"    :    "真鍮"    ,
"megalith"    :    "巨石"    ,
"bannister"    :    "ベニスター"    ,
"breakwater"    :    "防波堤"    ,
"dam"    :    "ダム"    ,
"chainlink fence "    :    "チェーンリンクフェンス"    ,
"picket fence"    :    "杭柵"    ,
"worm fence"    :    "ワームフェンス"    ,
"diamondback"    :    "ダイヤモンドバック"    ,
"grille"    :    "グリル"    ,
"sliding door "    :    "引き戸"    ,
"turnstile "    :    "改札口"    ,
"mountain tent "    :    "山のテント"    ,
"scoreboard "    :    "スコアボード"    ,
"honeycomb "    :    "ハニカム"    ,
"plate rack "    :    "プレートラック"    ,
"pedestal"    :    "台座"    ,
"beacon"    :    "ビーコン"    ,
"leatherback turtle"    :    "レザーバックカメ"    ,
"mashed potato "    :    "マッシュポテト"    ,
"bell pepper "    :    "ピーマン"    ,
"head cabbage "    :    "頭キャベツ"    ,
"broccoli "    :    "ブロッコリ"    ,
"cauliflower "    :    "カリフラワー"    ,
"zucchini"    :    "ズッキーニ"    ,
"spaghetti squash "    :    "スパゲティスカッシュ"    ,
"acorn squash "    :    "ドングリのスカッシュ"    ,
"butternut squash "    :    "バナナスカッシュ"    ,
"cucumber"    :    "きゅうり"    ,
"artichoke"    :    "アーティチョーク"    ,
"cardoon "    :    "吹奏楽"    ,
"mushroom "    :    "キノコ"    ,
"shower curtain "    :    "シャワーカーテン"    ,
"jean"    :    "ジーンズ"    ,
"carton "    :    "カートン"    ,
"handkerchief"    :    "ハンカチ"    ,
"sandal "    :    "サンダル"    ,
"ashcan"    :    "アシュカン"    ,
"safe "    :    "安全"    ,
"plate "    :    "プレート"    ,
"necklace "    :    "ネックレス"    ,
"croquet ball "    :    "クロケットボール"    ,
"fur coat "    :    "毛皮コート"    ,
"thimble "    :    "シンブル"    ,
"pajama"    :    "パジャマ"    ,
"running shoe "    :    "ランニングシューズ"    ,
"oboe"    :    "オーボエ"    ,
"cocktail shaker "    :    "カクテルシェーカー"    ,
"chest "    :    "胸"    ,
"manhole cover "    :    "マンホールカバー"    ,
"modem "    :    "モデム"    ,
"tub"    :    "浴槽"    ,
"tray "    :    "トレイ"    ,
"balance beam"    :    "平衡ビーム"    ,
"bagel"    :    "ベーグル"    ,
"violin"    :    "バイオリン"    ,
"prayer rug"    :    "祈り敷物"    ,
"kimono "    :    "着物"    ,
"hot pot"    :    "ホットポット"    ,
"whiskey jug "    :    "ウイスキー瓶"    ,
"knee pad "    :    "膝パッド"    ,
"book jacket"    :    "ブックジャケット"    ,
"spindle "    :    "スピンドル"    ,
"ski mask "    :    "目出し帽"    ,
"beer bottle "    :    "ビール瓶"    ,
"crash helmet "    :    "クラッシュヘルメット"    ,
"bottlecap "    :    "瓶のキャップ"    ,
"tile roof "    :    "タイル屋根"    ,
"mask "    :    "マスク"    ,
"maillot "    :    "メイヤー"    ,
"Petri dish "    :    "ペトリ皿"    ,
"football helmet "    :    "サッカーヘルメット"    ,
"bathing cap"    :    "入浴キャップ"    ,
"teddy"    :    "テディ"    ,
"holster "    :    "ホルスター"    ,
"pop bottle"    :    "ポップボトル"    ,
"photocopier "    :    "コピー機"    ,
"vestment "    :    "拘束"    ,
"crossword puzzle"    :    "クロスワードパズル"    ,
"golf ball "    :    "ゴルフボール"    ,
"trifle "    :    "些細な"    ,
"suit"    :    "スーツ"    ,
"water tower "    :    "給水塔"    ,
"feather boa"    :    "フェザーボア"    ,
"cloak "    :    "隠す"    ,
"red wine "    :    "赤ワイン"    ,
"drumstick "    :    "ドラムスティック"    ,
"shield"    :    "シールド"    ,
"Christmas stocking "    :    "クリスマスの靴下"    ,
"hoopskirt"    :    "フープスキート"    ,
"menu "    :    "メニュー"    ,
"stage "    :    "ステージ"    ,
"bonnet"    :    "ボンネット"    ,
"meat loaf"    :    "ミートローフ"    ,
"baseball "    :    "野球"    ,
"face powder "    :    "フェースパウダー"    ,
"scabbard "    :    "鞘"    ,
"sunscreen"    :    "日焼け止め"    ,
"beer glass "    :    "ビールグラス"    ,
"hen-of-the-woods"    :    "ヘン・オブ・ザ・ウッズ"    ,
"guacamole "    :    "グアカモーレ"    ,
"wool"    :    "ウール"    ,
"hay "    :    "乾草"    ,
"bow tie"    :    "ちょうネクタイ"    ,
"mailbag"    :    "郵袋"    ,
"water jug "    :    "水差し"    ,
"bucket"    :    "バケツ"    ,
"dishrag"    :    "食器棚"    ,
"soup bowl "    :    "スープボウル"    ,
"eggnog "    :    "エッグノッグ"    ,
"mortar "    :    "モルタル"    ,
"trench coat "    :    "トレンチコート"    ,
"paddle"    :    "パドル"    ,
"chain "    :    "鎖"    ,
"swab"    :    "スワブ"    ,
"mixing bowl "    :    "ミキシングボウル"    ,
"potpie "    :    "ポピー"    ,
"wine bottle "    :    "ワインボトル"    ,
"shoji "    :    "長尾"    ,
"bulletproof vest "    :    "防弾チョッキ"    ,
"drilling platform"    :    "掘削プラットフォーム"    ,
"binder"    :    "バインダー"    ,
"cardigan "    :    "カーディガン"    ,
"sweatshirt "    :    "トレーナー"    ,
"pot"    :    "ポット"    ,
"birdhouse "    :    "バードハウス"    ,
"jinrikisha"    :    "ジンリキシャ"    ,
"hamper "    :    "邪魔する"    ,
"ping-pong ball "    :    "ピンポンボール"    ,
"pencil box"    :    "筆箱"    ,
"consomme "    :    "コンソメ"    ,
"apron "    :    "エプロン"    ,
"punching bag"    :    "パンチングバッグ"    ,
"backpack"    :    "バックパック"    ,
"groom"    :    "新郎"    ,
"bearskin"    :    "ビースキン"    ,
"pencil sharpener "    :    "鉛筆削り"    ,
"broom "    :    "ほうき"    ,
"abaya "    :    "アバヤ"    ,
"mortarboard "    :    "モルタルボード"    ,
"poncho "    :    "ポンチョ"    ,
"crutch "    :    "松葉杖"    ,
"Polaroid camera"    :    "ポラロイドカメラ"    ,
"space bar "    :    "スペースキー"    ,
"cup "    :    "カップ"    ,
"racket"    :    "ラケット"    ,
"traffic light"    :    "信号機"    ,
"quill"    :    "羽毛"    ,
"radio"    :    "無線"    ,
"snow leopard"    :    "ユキヒョウ"    ,
"dough "    :    "生地"    ,
"cuirass "    :    "キューラス"    ,
"military uniform "    :    "軍服"    ,
"lipstick"    :    "口紅"    ,
"shower cap "    :    "シャワーキャップ"    ,
"monitor "    :    "モニター"    ,
"oscilloscope"    :    "オシロスコープ"    ,
"mitten "    :    "ミトン"    ,
"brassiere"    :    "ブラジャー"    ,
"French loaf "    :    "フレンチローフ"    ,
"vase "    :    "花瓶"    ,
"milk can "    :    "ミルク缶"    ,
"rugby ball "    :    "ラグビーボール"    ,
"paper towel "    :    "ペーパータオル"    ,
"earthstar "    :    "アーススター"    ,
"envelope "    :    "エンベロープ"    ,
"miniskirt"    :    "ミニスカート"    ,
"cowboy hat"    :    "カウボーイハット"    ,
"trolleybus"    :    "トロリーバス"    ,
"perfume"    :    "香水"    ,
"bathtub"    :    "バスタブ"    ,
"hotdog"    :    "ホットドッグ"    ,
"coral fungus "    :    "サンゴ菌"    ,
"bullet train"    :    "新幹線"    ,
"pillow "    :    "枕"    ,
"toilet tissue"    :    "トイレットペーパー"    ,
"cassette "    :    "カセット"    ,
"carpenter's kit"    :    "大工のキット"    ,
"ladle "    :    "取鍋"    ,
"stinkhorn"    :    "悪臭"    ,
"lotion "    :    "ローション"    ,
"hair spray "    :    "ヘアスプレー"    ,
"academic gown"    :    "アカデミックガウン"    ,
"dome "    :    "ドーム"    ,
"crate "    :    "クレート"    ,
"wig "    :    "かつら"    ,
"burrito "    :    "ブリトー"    ,
"pill bottle "    :    "錠剤瓶"    ,
"chain mail"    :    "チェーンメール"    ,
"theater curtain"    :    "シアターカーテン"    ,
"window shade "    :    "ウィンドウシェード"    ,
"barrel"    :    "バレル"    ,
"washbasin"    :    "洗面器"    ,
"ballpoint"    :    "ボールペン"    ,
"basketball "    :    "バスケットボール"    ,
"bath towel "    :    "バスタオル"    ,
"cowboy boot "    :    "カウボーイブーツ"    ,
"gown "    :    "ガウン"    ,
"window screen "    :    "ウインドウスクリーン"    ,
"agaric "    :    "寒天"    ,
"standard poodle "    :    "標準プードル"    ,
"cellular telephone"    :    "携帯電話"    ,
"nipple "    :    "乳首"    ,
"barbell "    :    "バーベル"    ,
"mailbox"    :    "メールボックス"    ,
"lab coat"    :    "白衣"    ,
"fire screen"    :    "火災スクリーン"    ,
"minibus "    :    "ミニバス"    ,
"packet "    :    "パケット"    ,
"brown bear"    :    "ヒグマ"    ,
"pole "    :    "ポール"    ,
"horizontal bar"    :    "水平バー"    ,
"sombrero "    :    "ソンブレロ"    ,
"pickelhaube "    :    "ピックルハウベ"    ,
"rain barrel "    :    "レインバレル"    ,
"wallet"    :    "財布"    ,
"cassette player "    :    "カセット・プレーヤー"    ,
"comic book "    :    "コミックブック"    ,
"piggy bank"    :    "貯金箱"    ,
"street sign "    :    "ストリートサイン"    ,
"bell cote"    :    "ベルコート"    ,
"fountain pen "    :    "万年筆"    ,
"Windsor tie "    :    "ウィンザーネクタイ"    ,
"volleyball "    :    "バレーボール"    ,
"overskirt "    :    "オーバースカート"    ,
"sarong "    :    "サロン"    ,
"purse "    :    "財布"    ,
"bolo tie"    :    "ボロタイ"    ,
"bib "    :    "ビブ"    ,
"parachute"    :    "パラシュート"    ,
"sleeping bag "    :    "寝袋"    ,
"television"    :    "テレビ"    ,
"swimming trunks"    :    "海パン"    ,
"measuring cup "    :    "計量カップ"    ,
"espresso "    :    "エスプレッソ"    ,
"pizza"    :    "ピザ"    ,
"breastplate"    :    "胸当て"    ,
"shopping basket "    :    "買い物かご"    ,
"wooden spoon "    :    "木製スプーン"    ,
"saltshaker"    :    "塩辛い人"    ,
"chocolate sauce"    :    "チョコレートソース"    ,
"ballplayer"    :    "ボールプレーヤー"    ,
"goblet "    :    "ゴブレット"    ,
"gyromitra "    :    "ジャイロミトラ"    ,
"stretcher "    :    "ストレッチャー"    ,
"water bottle "    :    "水ボトル"    ,
"skunk"    :    "スカンク"    ,
"soap dispenser "    :    "石鹸ディスペンサー"    ,
"jersey"    :    "ジャージー"    ,
"school bus "    :    "スクールバス"    ,
"jigsaw puzzle "    :    "ジグソーパズル"    ,
"plastic bag "    :    "ビニール袋"    ,
"reflex camera "    :    "リフレックスカメラ"    ,
"diaper"    :    "おむつ"    ,
"Band Aid "    :    "バンドエイド"    ,
"ice lolly"    :    "アイスロリー"    ,
"velvet "    :    "ベルベット"    ,
"tennis ball "    :    "テニスボール"    ,
"gasmask"    :    "ガスマスク"    ,
"doormat"    :    "ドアマン"    ,
"Loafer "    :    "ローファー"    ,
"ice cream"    :    "アイスクリーム"    ,
"pretzel "    :    "プレッツェル"    ,
"quilt"    :    "キルト"    ,
"maillot"    :    "メイヤー"    ,
"tape player "    :    "テーププレーヤー"    ,
"clog"    :    "詰まる"    ,
"iPod "    :    "iPod"    ,
"bolete "    :    "ボレテ"    ,
"meerkat"    :    "マイアカット"    ,
"scuba diver "    :    "スキューバダイバー"    ,
"pitcher"    :    "ピッチャー"    ,
"matchstick "    :    "マッチ棒"    ,
"bikini"    :    "ビキニ"    ,
"sock "    :    "靴下"    ,
"CD player "    :    "CDプレーヤー"    ,
"lens cap"    :    "レンズキャップ"    ,
"thatch"    :    "かゆみ"    ,
"vault "    :    "金庫"    ,
"beaker "    :    "ビーカー"    ,
"bubble "    :    "バブル"    ,
"cheeseburger "    :    "チーズバーガー"    ,
"parallel bars"    :    "平行棒"    ,
"flagpole"    :    "旗竿"    ,
"coffee mug "    :    "コーヒーマグカップ"    ,
"rubber eraser"    :    "ゴム製消しゴム"    ,
"stole "    :    "ストール"    ,
"carbonara"    :    "カーボナラ"    ,
"dumbbell"    :    "ダンベル"
]
