//
//  korean.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-28.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let korean = [
    "person"    :    "사람"    ,
    "bicycle"    :    "자전거"    ,
    "car"    :    "차"    ,
    "motorcycle"    :    "오토바이"    ,
    "bird"    :    "새"    ,
    "cat"    :    "고양이"    ,
    "dog"    :    "개"    ,
    "horse"    :    "말"    ,
    "sheep"    :    "양"    ,
    "bottle"    :    "병"    ,
    "chair"    :    "의자"    ,
    "couch"    :    "침상"    ,
    "potted plant"    :    "화분"    ,
    "tv"    :    "TV"    ,
    "cow"    :    "소"    ,
    "airplane"    :    "비행기"    ,
    "hat"    :    "모자"    ,
    "license plate"    :    "자동차 번호판"    ,
    "bed"    :    "침대"    ,
    "laptop"    :    "휴대용 퍼스널 컴퓨터"    ,
    "fridge"    :    "냉장고"    ,
    "microwave"    :    "마이크로파"    ,
    "sink"    :    "싱크대"    ,
    "oven"    :    "오븐"    ,
    "toaster"    :    "빵 굽는 사람"    ,
    "bus"    :    "버스"    ,
    "train"    :    "기차"    ,
    "mirror"    :    "거울"    ,
    "dining table"    :    "식탁"    ,
    "elephant"    :    "코끼리"    ,
    "banana"    :    "바나나"    ,
    "bread"    :    "빵"    ,
    "toilet"    :    "화장실"    ,
    "book"    :    "도서"    ,
    "boat"    :    "보트"    ,
    "plate"    :    "플레이트"    ,
    "cellphone"    :    "핸드폰"    ,
    "mouse"    :    "쥐"    ,
    "remote"    :    "먼"    ,
    "clock"    :    "시계"    ,
    "face"    :    "얼굴"    ,
    "hand"    :    "손"    ,
    "apple"    :    "사과"    ,
    "keyboard"    :    "건반"    ,
    "backpack"    :    "배낭"    ,
    "steering wheel"    :    "스티어링 휠"    ,
    "wineglass"    :    "와인 잔"    ,
    "chicken"    :    "치킨"    ,
    "zebra"    :    "얼룩말"    ,
    "shoe"    :    "구두"    ,
    "eye"    :    "눈"    ,
    "mouth"    :    "입"    ,
    "scissors"    :    "가위"    ,
    "truck"    :    "트럭"    ,
    "traffic light"    :    "신호등"    ,
    "eyeglasses"    :    "안경"    ,
    "cup"    :    "컵"    ,
    "blender"    :    "믹서기"    ,
    "hairdrier"    :    "헤어 드라이어"    ,
    "wheel"    :    "바퀴"    ,
    "streetsign"    :    "도로 표지판"    ,
    "umbrella"    :    "우산"    ,
    "door"    :    "문"    ,
    "firehydrant"    :    "소화전"    ,
    "bowl"    :    "사발"    ,
    "teapot"    :    "주전자"    ,
    "fork"    :    "포크"    ,
    "knife"    :    "칼"    ,
    "spoon"    :    "숟가락"    ,
    "bear"    :    "곰"    ,
    "headlights"    :    "헤드 라이트"    ,
    "window"    :    "창문"    ,
    "desk"    :    "책상"    ,
    "computer"    :    "컴퓨터"    ,
    "refrigerator"    :    "냉장고"    ,
    "pizza"    :    "피자"    ,
    "squirrel"    :    "다람쥐"    ,
    "duck"    :    "오리"    ,
    "frisbee"    :    "뚜껑 잘 간수 해"    ,
    "guitar"    :    "기타"    ,
    "nose"    :    "코"    ,
    "teddybear"    :    "테디 베어"    ,
    "tie"    :    "넥타이"    ,
    "stopsign"    :    "정지 신호"    ,
    "surfboard"    :    "서핑 보드"    ,
    "sandwich"    :    "샌드위치"    ,
    "pen/pencil"    :    "펜 / 연필"    ,
    "kite"    :    "연"    ,
    "orange"    :    "주황색"    ,
    "toothbrush"    :    "칫솔"    ,
    "printer"    :    "인쇄기"    ,
    "pans"    :    "프라이팬"    ,
    "head"    :    "머리"    ,
    "sports ball"    :    "스포츠 공"    ,
    "broccoli"    :    "브로콜리"    ,
    "suitcase"    :    "여행 가방"    ,
    "carrot"    :    "당근"    ,
    "chandelier"    :    "샹들리에"    ,
    "parking meter"    :    "주차료 징수 기"    ,
    "fish"    :    "물고기"    ,
    "handbag"    :    "핸드백"    ,
    "hotdog"    :    "핫도그"    ,
    "stapler"    :    "호치키스"    ,
    "basketball hoop"    :    "농구 골대"    ,
    "donut"    :    "도넛"    ,
    "vase"    :    "병 장식"    ,
    "baseball bat"    :    "야구 방망이"    ,
    "baseball glove"    :    "야구 글러브"    ,
    "giraffe"    :    "기린"    ,
    "jacket"    :    "재킷"    ,
    "skis"    :    "스키"    ,
    "snowboard"    :    "스노우 보드"    ,
    "tablelamp"    :    "테이블 램프"    ,
    "egg"    :    "계란"    ,
    "door handle"    :    "문 손잡이"    ,
    "power outlet"    :    "전원 콘센트"    ,
    "hair"    :    "머리"    ,
    "tiger"    :    "호랑이"    ,
    "table"    :    "표"    ,
    "coffee table"    :    "커피 테이블"    ,
    "skate board"    :    "스케이트 보드"    ,
    "helicopter"    :    "헬리콥터"    ,
    "tomato"    :    "토마토"    ,
    "tree"    :    "나무"    ,
    "bunny"    :    "토끼"    ,
    "pillow"    :    "베개"    ,
    "tennis racket"    :    "테니스 라켓"    ,
    "cake"    :    "케이크"    ,
    "feet"    :    "피트"    ,
    "bench"    :    "벤치"    ,
    "chopping board"    :    "도마"    ,
    "washer"    :    "세탁기"    ,
    "lion"    :    "사자"    ,
    "monkey"    :    "원숭이"    ,
    "hairbrush"    :    "머리 빗는 솔"    ,
    "light switch"    :    "전등 스위치"    ,
    "arms"    :    "무기"    ,
    "legs"    :    "다리"    ,
    "house"    :    "집"    ,
    "cheese"    :    "치즈"    ,
    "goat"    :    "염소"    ,
    "magazine"    :    "매거진"    ,
    "key"    :    "키"    ,
    "picture"    :    "그림"    ,
    "frame"    :    "틀"    ,
    "cupcake"    :    "컵케익"    ,
    "fan(ceil/floor)"    :    "팬 (천장 / 바닥)"    ,
    "frogs"    :    "개구리"    ,
    "rabbit"    :    "토끼"    ,
    "owl"    :    "올빼미"    ,
    "scarf"    :    "스카프"    ,
    "ears"    :    "귀"    ,
    "homephone"    :    "집 전화"    ,
    "pig"    :    "돼지"    ,
    "strawberries"    :    "딸기"    ,
    "pumpkin"    :    "호박"    ,
    "van"    :    "봉고차"    ,
    "kangaroo"    :    "캥거루"    ,
    "rhinoceros"    :    "코뿔소"    ,
    "sailboat"    :    "요트"    ,
    "deer"    :    "사슴"    ,
    "playing cards"    :    "카드 놀이"    ,
    "towel"    :    "수건"    ,
    "hyppo hyppo"    :    "하포 하포"    ,
    "can"    :    "양철통"    ,
    "dollar bill"    :    "달러 지폐"    ,
    "doll"    :    "인형"    ,
    "soup"    :    "수프"    ,
    "meat"    :    "고기"    ,
    "muffins"    :    "머핀"    ,
    "tire"    :    "타이어"    ,
    "necklace"    :    "목걸이"    ,
    "tablet"    :    "태블릿"    ,
    "corn"    :    "옥수수"    ,
    "ladder"    :    "사닥다리"    ,
    "pineapple"    :    "파인애플"    ,
    "candle"    :    "양초"    ,
    "desktop"    :    "데스크톱"    ,
    "carpet"    :    "양탄자"    ,
    "cookie"    :    "쿠키"    ,
    "toycars"    :    "장난감 자동차들"    ,
    "bracelet"    :    "팔찌"    ,
    "bat"    :    "박쥐"    ,
    "balloon"    :    "풍선"    ,
    "gloves"    :    "장갑"    ,
    "milk"    :    "우유"    ,
    "pants"    :    "바지"    ,
    "wheelchair"    :    "바퀴 달린 의자"    ,
    "building"    :    "건물"    ,
    "bacon"    :    "베이컨"    ,
    "box"    :    "상자"    ,
    "platypus"    :    "오리너구리"    ,
    "pancake"    :    "팬케이크"    ,
    "cabinet"    :    "내각"    ,
    "whale"    :    "고래"    ,
    "dryer"    :    "건조기"    ,
    "torso"    :    "몸통"    ,
    "lizard"    :    "도마뱀"    ,
    "shirt"    :    "셔츠"    ,
    "shorts"    :    "반바지"    ,
    "pasta"    :    "파스타"    ,
    "grapes"    :    "포도"    ,
    "shark"    :    "상어"    ,
    "swan"    :    "백조"    ,
    "fingers"    :    "손가락"    ,
    "sidetable"    :    "사이드 테이블"    ,
    "gate"    :    "문"    ,
    "beans"    :    "콩"    ,
    "flip flops"    :    "플립 플롭"    ,
    "moon"    :    "달"    ,
    "road/street/"    :    "도로 / 거리 /"    ,
    "fountain"    :    "분수"    ,
    "faxmachine"    :    "팩스"    ,
    "hotair balloon"    :    "열기구"    ,
    "cereal"    :    "시리얼"    ,
    "seahorse"    :    "해마"    ,
    "rocket"    :    "로켓"    ,
    "cabinets"    :    "캐비닛"    ,
    "basketball"    :    "농구"    ,
    "telephone"    :    "전화"    ,
    "movie(disc)"    :    "영화 (디스크)"    ,
    "football"    :    "축구"    ,
    "goose"    :    "거위"    ,
    "long-sleeve shirt"    :    "긴 소매 셔츠"    ,
    "short-sleeve shirt"    :    "반소매 셔츠"    ,
    "raft"    :    "뗏목"    ,
    "rooster"    :    "수탉"    ,
    "copier"    :    "복사기"    ,
    "radio"    :    "라디오"    ,
    "fences"    :    "울타리"    ,
    "goalnet"    :    "목표 망"    ,
    "toys"    :    "장난감"    ,
    "engine"    :    "엔진"    ,
    "soccerball"    :    "축구 공"    ,
    "fieldgoal posts"    :    "필드 골 포스트"    ,
    "socks"    :    "양말"    ,
    "tennisnet"    :    "테니스 넷"    ,
    "seats"    :    "좌석"    ,
    "elbows"    :    "팔꿈치"    ,
    "aardvark"    :    "지루한 마음"    ,
    "dinosaur"    :    "공룡"    ,
    "unicycle"    :    "외발 자전거 타다"    ,
    "honey"    :    "꿀"    ,
    "legos"    :    "레고스"    ,
    "fly"    :    "파리"    ,
    "roof"    :    "지붕"    ,
    "baseball"    :    "야구"    ,
    "mat"    :    "매트"    ,
    "ipad"    :    "ipad"    ,
    "iphone"    :    "아이폰"    ,
    "hoop"    :    "테두리"    ,
    "hen"    :    "암탉"    ,
    "back"    :    "뒤로"    ,
    "table cloth"    :    "테이블 천"    ,
    "soccer nets"    :    "축구 그물"    ,
    "turkey"    :    "터키"    ,
    "pajamas"    :    "잠옷"    ,
    "underpants"    :    "팬티"    ,
    "goldfish"    :    "금붕어"    ,
    "robot"    :    "기계 인간"    ,
    "crusher"    :    "파쇄기"    ,
    "animal crackers"    :    "동물 크래커"    ,
    "basketball court"    :    "농구 코트"    ,
    "horn"    :    "뿔"    ,
    "firefly"    :    "반딧불"    ,
    "armpits"    :    "겨드랑이"    ,
    "nectar"    :    "넥타"    ,
    "superhero costume"    :    "슈퍼 히어로 의상"    ,
    "jetpack"    :    "제트 팩"    ,
    "robots"    :    "로봇"
]
