//
//  russian.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-28.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let russian = [
    "person"    :    "человек"    ,
    "bicycle"    :    "велосипед"    ,
    "car"    :    "автомобиль"    ,
    "motorcycle"    :    "мотоцикл"    ,
    "bird"    :    "птица"    ,
    "cat"    :    "Кот"    ,
    "dog"    :    "собака"    ,
    "horse"    :    "лошадь"    ,
    "sheep"    :    "овца"    ,
    "bottle"    :    "бутылка"    ,
    "chair"    :    "стул"    ,
    "couch"    :    "диван"    ,
    "potted plant"    :    "растение в горшке"    ,
    "tv"    :    "ТВ"    ,
    "cow"    :    "корова"    ,
    "airplane"    :    "самолет"    ,
    "hat"    :    "шапка"    ,
    "license plate"    :    "Номерной знак"    ,
    "bed"    :    "постель"    ,
    "laptop"    :    "портативный компьютер"    ,
    "fridge"    :    "холодильник"    ,
    "microwave"    :    "микроволновая печь"    ,
    "sink"    :    "раковина"    ,
    "oven"    :    "духовой шкаф"    ,
    "toaster"    :    "тостер"    ,
    "bus"    :    "автобус"    ,
    "train"    :    "поезд"    ,
    "mirror"    :    "зеркало"    ,
    "dining table"    :    "обеденный стол"    ,
    "elephant"    :    "слон"    ,
    "banana"    :    "банан"    ,
    "bread"    :    "хлеб"    ,
    "toilet"    :    "туалет"    ,
    "book"    :    "книга"    ,
    "boat"    :    "лодка"    ,
    "plate"    :    "пластина"    ,
    "cellphone"    :    "Сотовый телефон"    ,
    "mouse"    :    "мышь"    ,
    "remote"    :    "дистанционный пульт"    ,
    "clock"    :    "Часы"    ,
    "face"    :    "лицо"    ,
    "hand"    :    "рука"    ,
    "apple"    :    "яблоко"    ,
    "keyboard"    :    "клавиатура"    ,
    "backpack"    :    "рюкзак"    ,
    "steering wheel"    :    "руль"    ,
    "wineglass"    :    "бокал для вина"    ,
    "chicken"    :    "курица"    ,
    "zebra"    :    "зебра"    ,
    "shoe"    :    "башмак"    ,
    "eye"    :    "глаз"    ,
    "mouth"    :    "рот"    ,
    "scissors"    :    "ножницы"    ,
    "truck"    :    "грузовая машина"    ,
    "traffic light"    :    "светофор"    ,
    "eyeglasses"    :    "очки"    ,
    "cup"    :    "кружка"    ,
    "blender"    :    "смеситель"    ,
    "hairdrier"    :    "фен"    ,
    "wheel"    :    "колесо"    ,
    "streetsign"    :    "дорожный знак"    ,
    "umbrella"    :    "зонтик"    ,
    "door"    :    "дверь"    ,
    "firehydrant"    :    "пожарный гидрант"    ,
    "bowl"    :    "миска"    ,
    "teapot"    :    "заварочный чайник"    ,
    "fork"    :    "вилка"    ,
    "knife"    :    "нож"    ,
    "spoon"    :    "ложка"    ,
    "bear"    :    "медведь"    ,
    "headlights"    :    "Фары"    ,
    "window"    :    "окно"    ,
    "desk"    :    "стол письменный"    ,
    "computer"    :    "компьютер"    ,
    "refrigerator"    :    "холодильник"    ,
    "pizza"    :    "пицца"    ,
    "squirrel"    :    "белка"    ,
    "duck"    :    "утка"    ,
    "frisbee"    :    "фрисби"    ,
    "guitar"    :    "гитара"    ,
    "nose"    :    "нос"    ,
    "teddybear"    :    "плюшевый медведь"    ,
    "tie"    :    "галстук"    ,
    "stopsign"    :    "знак СТОП"    ,
    "surfboard"    :    "доска для серфинга"    ,
    "sandwich"    :    "сэндвич"    ,
    "pen/pencil"    :    "ручка карандаш"    ,
    "kite"    :    "воздушный змей"    ,
    "orange"    :    "оранжевый"    ,
    "toothbrush"    :    "зубная щетка"    ,
    "printer"    :    "принтер"    ,
    "pans"    :    "сковородки"    ,
    "head"    :    "глава"    ,
    "sports ball"    :    "спортивный мяч"    ,
    "broccoli"    :    "брокколи"    ,
    "suitcase"    :    "чемодан"    ,
    "carrot"    :    "морковь"    ,
    "chandelier"    :    "люстра"    ,
    "parking meter"    :    "счетчик на стоянке"    ,
    "fish"    :    "рыба"    ,
    "handbag"    :    "сумка"    ,
    "hotdog"    :    "хотдог"    ,
    "stapler"    :    "стэплер"    ,
    "basketball hoop"    :    "баскетбольное кольцо"    ,
    "donut"    :    "пончик"    ,
    "vase"    :    "ваза"    ,
    "baseball bat"    :    "бейсбольная бита"    ,
    "baseball glove"    :    "бейсбольная перчатка"    ,
    "giraffe"    :    "жирафа"    ,
    "jacket"    :    "куртка"    ,
    "skis"    :    "лыжи"    ,
    "snowboard"    :    "сноуборд"    ,
    "tablelamp"    :    "настольная лампа"    ,
    "egg"    :    "яйцо"    ,
    "door handle"    :    "дверная ручка"    ,
    "power outlet"    :    "розетка"    ,
    "hair"    :    "волосы"    ,
    "tiger"    :    "тигр"    ,
    "table"    :    "Таблица"    ,
    "coffee table"    :    "кофейный столик"    ,
    "skate board"    :    "коньковая доска"    ,
    "helicopter"    :    "вертолет"    ,
    "tomato"    :    "помидор"    ,
    "tree"    :    "дерево"    ,
    "bunny"    :    "кролик"    ,
    "pillow"    :    "подушка"    ,
    "tennis racket"    :    "теннисная ракетка"    ,
    "cake"    :    "кекс"    ,
    "feet"    :    "ноги"    ,
    "bench"    :    "скамейка"    ,
    "chopping board"    :    "разделочная доска"    ,
    "washer"    :    "Шайба"    ,
    "lion"    :    "лев"    ,
    "monkey"    :    "обезьяна"    ,
    "hairbrush"    :    "щетка для волос"    ,
    "light switch"    :    "выключатель"    ,
    "arms"    :    "оружие"    ,
    "legs"    :    "ноги"    ,
    "house"    :    "дом"    ,
    "cheese"    :    "сыр"    ,
    "goat"    :    "козел"    ,
    "magazine"    :    "журнал"    ,
    "key"    :    "ключ"    ,
    "picture"    :    "картина"    ,
    "frame"    :    "Рамка"    ,
    "cupcake"    :    "кекс"    ,
    "fan(ceil/floor)"    :    "вентилятор (CEIL / этаж)"    ,
    "frogs"    :    "лягушки"    ,
    "rabbit"    :    "кролик"    ,
    "owl"    :    "сова"    ,
    "scarf"    :    "шарф"    ,
    "ears"    :    "уши"    ,
    "homephone"    :    "домашний телефон"    ,
    "pig"    :    "свинья"    ,
    "strawberries"    :    "клубника"    ,
    "pumpkin"    :    "тыква"    ,
    "van"    :    "фургон"    ,
    "kangaroo"    :    "кенгуру"    ,
    "rhinoceros"    :    "носорог"    ,
    "sailboat"    :    "парусная лодка"    ,
    "deer"    :    "олень"    ,
    "playing cards"    :    "игральные карты"    ,
    "towel"    :    "полотенце"    ,
    "hyppo hyppo"    :    "hyppo hyppo"    ,
    "can"    :    "Можно"    ,
    "dollar bill"    :    "долларовый счет"    ,
    "doll"    :    "кукла"    ,
    "soup"    :    "суп"    ,
    "meat"    :    "мясо"    ,
    "muffins"    :    "кексы"    ,
    "tire"    :    "шина"    ,
    "necklace"    :    "ожерелье"    ,
    "tablet"    :    "таблетка"    ,
    "corn"    :    "кукуруза"    ,
    "ladder"    :    "лестница"    ,
    "pineapple"    :    "ананас"    ,
    "candle"    :    "свеча"    ,
    "desktop"    :    "рабочий стол"    ,
    "carpet"    :    "ковер"    ,
    "cookie"    :    "печенье"    ,
    "toycars"    :    "игрушечные машинки"    ,
    "bracelet"    :    "браслет"    ,
    "bat"    :    "летучая мышь"    ,
    "balloon"    :    "воздушный шар"    ,
    "gloves"    :    "перчатки"    ,
    "milk"    :    "молоко"    ,
    "pants"    :    "брюки"    ,
    "wheelchair"    :    "инвалидная коляска"    ,
    "building"    :    "здание"    ,
    "bacon"    :    "бекон"    ,
    "box"    :    "коробка"    ,
    "platypus"    :    "утконос"    ,
    "pancake"    :    "блин"    ,
    "cabinet"    :    "кабинет"    ,
    "whale"    :    "кит"    ,
    "dryer"    :    "сушилка"    ,
    "torso"    :    "торс"    ,
    "lizard"    :    "ящерица"    ,
    "shirt"    :    "Рубашка"    ,
    "shorts"    :    "шорты"    ,
    "pasta"    :    "макаронные изделия"    ,
    "grapes"    :    "виноград"    ,
    "shark"    :    "акула"    ,
    "swan"    :    "лебедь"    ,
    "fingers"    :    "пальцы"    ,
    "sidetable"    :    "столик"    ,
    "gate"    :    "Ворота"    ,
    "beans"    :    "фасоль"    ,
    "flip flops"    :    "шлепки"    ,
    "moon"    :    "Луна"    ,
    "road/street/"    :    "дорога / улица /"    ,
    "fountain"    :    "фонтан"    ,
    "faxmachine"    :    "Факс"    ,
    "hotair balloon"    :    "воздушный шар"    ,
    "cereal"    :    "зерновой"    ,
    "seahorse"    :    "конек"    ,
    "rocket"    :    "ракета"    ,
    "cabinets"    :    "шкафы"    ,
    "basketball"    :    "баскетбол"    ,
    "telephone"    :    "телефон"    ,
    "movie(disc)"    :    "фильм (диск)"    ,
    "football"    :    "футбол"    ,
    "goose"    :    "Гусь"    ,
    "long-sleeve shirt"    :    "рубашка с длинными рукавами"    ,
    "short-sleeve shirt"    :    "рубашка с коротким рукавом"    ,
    "raft"    :    "рафт"    ,
    "rooster"    :    "петух"    ,
    "copier"    :    "копировальное устройство"    ,
    "radio"    :    "радио"    ,
    "fences"    :    "заборы"    ,
    "goalnet"    :    "goalnet"    ,
    "toys"    :    "игрушки"    ,
    "engine"    :    "двигатель"    ,
    "soccerball"    :    "футбольный мяч"    ,
    "fieldgoal posts"    :    "полевые сообщения"    ,
    "socks"    :    "носки"    ,
    "tennisnet"    :    "tennisnet"    ,
    "seats"    :    "места"    ,
    "elbows"    :    "локти"    ,
    "aardvark"    :    "трубкозуб"    ,
    "dinosaur"    :    "динозавр"    ,
    "unicycle"    :    "Моноцикл"    ,
    "honey"    :    "мед"    ,
    "legos"    :    "Legos"    ,
    "fly"    :    "летать"    ,
    "roof"    :    "крыша"    ,
    "baseball"    :    "бейсбол"    ,
    "mat"    :    "мат"    ,
    "ipad"    :    "Ipad"    ,
    "iphone"    :    "iphone"    ,
    "hoop"    :    "обруч"    ,
    "hen"    :    "курица"    ,
    "back"    :    "назад"    ,
    "table cloth"    :    "скатерть"    ,
    "soccer nets"    :    "футбольные сети"    ,
    "turkey"    :    "Турция"    ,
    "pajamas"    :    "пижама"    ,
    "underpants"    :    "Трусы"    ,
    "goldfish"    :    "золотая рыбка"    ,
    "robot"    :    "робот"    ,
    "crusher"    :    "дробилка"    ,
    "animal crackers"    :    "животные крекеры"    ,
    "basketball court"    :    "баскетбольная площадка"    ,
    "horn"    :    "рог"    ,
    "firefly"    :    "Светляк"    ,
    "armpits"    :    "подмышки"    ,
    "nectar"    :    "нектар"    ,
    "superhero costume"    :    "костюм супергероя"    ,
    "jetpack"    :    "Реактивный ранец"    ,
    "robots"    :    "роботы"    ,
]
