//
//  simpChinese.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-12.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let simpChinese = [
"kit fox"    :    "套装狐狸"    ,
"English setter"    :    "英语二传手"    ,
"Australian terrier"    :    "澳大利亚梗"    ,
"grey whale"    :    "灰鲸"    ,
"lesser panda"    :    "小熊猫"    ,
"Egyptian cat"    :    "埃及猫"    ,
"ibex"    :    "山羊"    ,
"Persian cat "    :    "波斯猫"    ,
"cougar"    :    "美洲狮"    ,
"gazelle "    :    "羚羊"    ,
"porcupine"    :    "豪猪"    ,
"sea lion "    :    "海狮"    ,
"badger "    :    "獾"    ,
"Great Dane "    :    "大丹犬"    ,
"Scottish deerhound"    :    "苏格兰猎鹿犬"    ,
"killer whale"    :    "逆戟鲸"    ,
"mink "    :    "貂"    ,
"African elephant"    :    "非洲大象"    ,
"red wolf"    :    "红狼"    ,
"jaguar"    :    "美洲虎"    ,
"hyena"    :    "鬣狗"    ,
"titi"    :    "蒂蒂"    ,
"three-toed sloth"    :    "三趾树懒"    ,
"sorrel "    :    "酢浆草"    ,
"black-footed ferret"    :    "黑脚鼬"    ,
"dalmatian"    :    "达尔马提亚"    ,
"Staffordshire bullterrier"    :    "斯塔福郡斗牛场"    ,
"Bouvier des Flandres"    :    "Bouvier des Flandres"    ,
"weasel "    :    "黄鼠狼"    ,
"miniature poodle "    :    "微型狮子狗"    ,
"bighorn"    :    "大号角"    ,
"fox squirrel"    :    "狐狸松鼠"    ,
"colobus"    :    "疣"    ,
"tiger cat "    :    "老虎猫"    ,
"impala"    :    "黑斑羚"    ,
"coyote"    :    "郊狼"    ,
"Yorkshire terrier "    :    "约克夏犬"    ,
"Newfoundland"    :    "纽芬兰"    ,
"red fox"    :    "红狐"    ,
"hartebeest "    :    "麋羚"    ,
"grey fox"    :    "灰狐狸"    ,
"Pekinese"    :    "北京人"    ,
"guenon"    :    "长尾"    ,
"mongoose "    :    "猫鼬"    ,
"indri"    :    "大狐猴"    ,
"tiger"    :    "虎"    ,
"wild boar"    :    "野猪"    ,
"zebra "    :    "斑马"    ,
"ram"    :    "内存"    ,
"orangutan"    :    "猩猩"    ,
"basenji "    :    "购买basenji"    ,
"leopard"    :    "豹"    ,
"vizsla"    :    "交易所vizsla"    ,
"squirrel monkey"    :    "松鼠猴"    ,
"Siamese cat"    :    "暹罗猫"    ,
"chimpanzee"    :    "黑猩猩"    ,
"komondor "    :    "购买komondor"    ,
"proboscis monkey"    :    "长鼻猴"    ,
"guinea pig"    :    "豚鼠"    ,
"white wolf"    :    "白狼"    ,
"ice bear"    :    "冰熊"    ,
"gorilla"    :    "大猩猩"    ,
"ox "    :    "牛"    ,
"Tibetan mastiff "    :    "藏獒"    ,
"spider monkey"    :    "蜘蛛猴"    ,
"Doberman"    :    "杜宾"    ,
"warthog "    :    "疣猪"    ,
"Arabian camel"    :    "阿拉伯骆驼"    ,
"siamang"    :    "合趾猿"    ,
"golden retriever "    :    "金毛猎犬"    ,
"Border collie "    :    "边境牧羊犬"    ,
"hare "    :    "野兔"    ,
"boxer "    :    "拳击手"    ,
"patas"    :    "PATAS"    ,
"baboon "    :    "狒狒"    ,
"macaque "    :    "猕"    ,
"capuchin"    :    "僧帽"    ,
"flat-coated retriever "    :    "平坦的猎犬"    ,
"hog"    :    "豕"    ,
"Eskimo dog"    :    "爱斯基摩狗"    ,
"Brittany spaniel "    :    "布列塔尼西班牙猎狗"    ,
"dial telephone"    :    "拨打电话"    ,
"maze"    :    "迷宫"    ,
"Gordon setter "    :    "戈登二传手"    ,
"dingo"    :    "野狗"    ,
"hamster "    :    "仓鼠"    ,
"Arctic fox"    :    "白狐"    ,
"water buffalo"    :    "水牛"    ,
"American black bear"    :    "美国黑熊"    ,
"Angora"    :    "安哥拉"    ,
"bison "    :    "野牛"    ,
"howler monkey"    :    "吼猴"    ,
"hippopotamus"    :    "河马"    ,
"giant panda"    :    "大熊猫"    ,
"tabby"    :    "虎斑猫"    ,
"marmoset "    :    "狨猴"    ,
"Saint Bernard"    :    "圣伯纳德"    ,
"armadillo "    :    "犰狳"    ,
"redbone "    :    "redbone"    ,
"polecat"    :    "臭鼬"    ,
"marmot "    :    "旱獭"    ,
"gibbon"    :    "长臂猿"    ,
"llama "    :    "骆驼"    ,
"wood rabbit"    :    "木兔子"    ,
"lion"    :    "狮子"    ,
"Irish setter"    :    "爱尔兰二传手"    ,
"dugong"    :    "儒艮"    ,
"Indian elephant"    :    "印度大象"    ,
"beaver "    :    "海狸"    ,
"Madagascar cat"    :    "马达加斯加猫"    ,
"Rhodesian ridgeback "    :    "罗得西亚ridgeback"    ,
"lynx"    :    "猞猁"    ,
"African hunting dog"    :    "非洲猎犬"    ,
"langur "    :    "叶猴"    ,
"timber wolf"    :    "大灰狼"    ,
"cheetah"    :    "猎豹"    ,
"sloth bear"    :    "懒惰的熊"    ,
"German shepherd"    :    "德国牧羊犬"    ,
"otter "    :    "獭"    ,
"koala"    :    "考拉"    ,
"tusker "    :    "塔斯克"    ,
"echidna"    :    "针鼹"    ,
"wallaby"    :    "袋鼠"    ,
"platypus"    :    "鸭嘴兽"    ,
"wombat "    :    "袋熊"    ,
"revolver"    :    "左轮手枪"    ,
"umbrella "    :    "雨伞"    ,
"schooner "    :    "大篷车"    ,
"soccer ball "    :    "足球"    ,
"accordion"    :    "手风琴"    ,
"ant"    :    "蚂蚁"    ,
"starfish"    :    "海星"    ,
"chambered nautilus"    :    "带着鹦鹉螺"    ,
"grand piano"    :    "大钢琴"    ,
"laptop"    :    "笔记本电脑"    ,
"strawberry "    :    "草莓"    ,
"airliner "    :    "客机"    ,
"warplane"    :    "战机"    ,
"airship"    :    "飞艇"    ,
"balloon "    :    "气球"    ,
"space shuttle "    :    "航天飞机"    ,
"fireboat "    :    "消防艇"    ,
"gondola "    :    "贡多拉"    ,
"speedboat "    :    "快艇"    ,
"lifeboat "    :    "救生艇"    ,
"canoe "    :    "独木舟"    ,
"yawl "    :    "YAWL"    ,
"catamaran "    :    "双体船"    ,
"trimaran "    :    "三体船"    ,
"container ship"    :    "集装箱船"    ,
"liner"    :    "衬垫"    ,
"pirate"    :    "海盗"    ,
"aircraft carrier"    :    "航空母舰"    ,
"submarine"    :    "潜艇"    ,
"wreck "    :    "破坏"    ,
"half track "    :    "一半的轨道"    ,
"tank"    :    "坦克"    ,
"missile "    :    "导弹"    ,
"bobsled"    :    "雪橇"    ,
"dogsled"    :    "狗拉雪橇"    ,
"bicycle-built-for-two"    :    "自行车内置于二"    ,
"mountain bike"    :    "山地自行车"    ,
"freight car "    :    "货运车"    ,
"passenger car"    :    "乘用车"    ,
"barrow"    :    "独轮车"    ,
"shopping cart "    :    "购物车"    ,
"motor scooter"    :    "小型摩托车"    ,
"forklift "    :    "叉车"    ,
"electric locomotive "    :    "电力机车"    ,
"steam locomotive "    :    "蒸汽机车"    ,
"amphibian"    :    "两栖动物"    ,
"ambulance "    :    "救护车"    ,
"beach wagon"    :    "沙滩车"    ,
"cab"    :    "出租车"    ,
"convertible "    :    "可兑换"    ,
"jeep"    :    "吉普车"    ,
"limousine"    :    "豪华轿车"    ,
"minivan "    :    "面包车"    ,
"Model T "    :    "型号T"    ,
"racer"    :    "赛车"    ,
"sports car"    :    "跑车"    ,
"go-kart "    :    "卡丁车"    ,
"golfcart"    :    "高尔夫车"    ,
"moped "    :    "助力车"    ,
"snowplow"    :    "雪犁"    ,
"fire engine"    :    "消防车"    ,
"garbage truck"    :    "垃圾车"    ,
"pickup"    :    "捡起"    ,
"tow truck"    :    "拖车"    ,
"trailer truck"    :    "拖车"    ,
"moving van "    :    "搬运车"    ,
"police van"    :    "警车"    ,
"recreational vehicle"    :    "休闲车"    ,
"streetcar"    :    "电车"    ,
"snowmobile "    :    "雪地车"    ,
"tractor "    :    "拖拉机"    ,
"mobile home"    :    "移动房屋"    ,
"tricycle"    :    "三轮车"    ,
"unicycle"    :    "独轮车"    ,
"horse cart"    :    "马车"    ,
"mosquito net "    :    "蚊帐"    ,
"oxcart "    :    "牛车"    ,
"bassinet "    :    "摇篮"    ,
"cradle "    :    "摇篮"    ,
"crib"    :    "婴儿床"    ,
"four-poster "    :    "四柱"    ,
"bookcase "    :    "书柜"    ,
"china cabinet"    :    "中国内阁"    ,
"medicine chest"    :    "医药箱"    ,
"chiffonier"    :    "小衣橱"    ,
"table lamp "    :    "台灯"    ,
"file"    :    "文件"    ,
"pay-phone"    :    "付费电话"    ,
"park bench "    :    "公园的长椅上"    ,
"barber chair "    :    "理发椅"    ,
"throne "    :    "王座"    ,
"folding chair "    :    "折叠椅"    ,
"rocking chair"    :    "摇椅"    ,
"studio couch"    :    "工作室沙发"    ,
"toilet seat "    :    "马桶座圈"    ,
"desk "    :    "台"    ,
"pool table"    :    "台球桌"    ,
"dining table"    :    "餐桌"    ,
"entertainment center "    :    "娱乐中心"    ,
"wardrobe"    :    "衣柜"    ,
"Granny Smith "    :    "格兰尼史密斯"    ,
"orange "    :    "橙子"    ,
"lemon "    :    "柠檬"    ,
"fig "    :    "图"    ,
"pineapple"    :    "菠萝"    ,
"banana "    :    "香蕉"    ,
"jackfruit"    :    "菠萝蜜"    ,
"custard apple "    :    "南美番荔枝"    ,
"pomegranate "    :    "石榴"    ,
"acorn "    :    "橡子"    ,
"hip"    :    "臀部"    ,
"ear"    :    "耳"    ,
"rapeseed "    :    "菜子"    ,
"corn "    :    "玉米"    ,
"buckeye"    :    "七叶树"    ,
"organ"    :    "器官"    ,
"upright"    :    "直立"    ,
"chime"    :    "钟"    ,
"drum"    :    "鼓"    ,
"gong"    :    "锣"    ,
"maraca "    :    "马拉卡"    ,
"marimba"    :    "马林巴"    ,
"steel drum "    :    "钢鼓"    ,
"banjo "    :    "班卓琴"    ,
"cello"    :    "大提琴"    ,
"lampshade"    :    "灯罩"    ,
"harp "    :    "竖琴"    ,
"acoustic guitar "    :    "原声吉他"    ,
"electric guitar "    :    "电吉他"    ,
"cornet"    :    "信号旗"    ,
"French horn"    :    "法国号角"    ,
"trombone "    :    "长号"    ,
"harmonica"    :    "口琴"    ,
"ocarina"    :    "奥卡利那笛"    ,
"panpipe"    :    "箫"    ,
"bassoon "    :    "巴松管"    ,
"sax"    :    "萨克斯"    ,
"flute"    :    "长笛"    ,
"daisy "    :    "雏菊"    ,
"yellow lady's slipper"    :    "黄女士的拖鞋"    ,
"cliff"    :    "悬崖"    ,
"valley"    :    "谷"    ,
"alp "    :    "岳"    ,
"volcano "    :    "火山"    ,
"promontory"    :    "海角"    ,
"sandbar"    :    "坝"    ,
"coral reef "    :    "珊瑚礁"    ,
"lakeside"    :    "湖边"    ,
"seashore"    :    "海滨"    ,
"geyser "    :    "喷泉"    ,
"hatchet "    :    "斧头"    ,
"cleaver"    :    "切肉刀"    ,
"letter opener"    :    "开信刀"    ,
"plane"    :    "平面"    ,
"power drill "    :    "电钻"    ,
"lawn mower"    :    "割草机"    ,
"hammer "    :    "锤子"    ,
"corkscrew"    :    "螺旋形的"    ,
"can opener"    :    "开罐器"    ,
"plunger"    :    "柱塞"    ,
"screwdriver "    :    "螺丝刀"    ,
"shovel "    :    "铲"    ,
"plow"    :    "犁"    ,
"chain saw"    :    "链锯"    ,
"cock "    :    "公鸡"    ,
"hen "    :    "母鸡"    ,
"ostrich"    :    "鸵鸟"    ,
"brambling"    :    "花鸡"    ,
"goldfinch"    :    "金翅雀"    ,
"house finch"    :    "房子雀"    ,
"junco"    :    "洪科"    ,
"indigo bunting"    :    "靛蓝旗布"    ,
"robin"    :    "知更鸟"    ,
"bulbul "    :    "夜莺"    ,
"jay "    :    "松鸦"    ,
"magpie "    :    "鹊"    ,
"chickadee "    :    "山雀"    ,
"water ouzel"    :    "水ouzel"    ,
"kite "    :    "风筝"    ,
"bald eagle"    :    "白头鹰"    ,
"vulture "    :    "秃鹫"    ,
"great grey owl"    :    "伟大的灰色猫头鹰"    ,
"black grouse "    :    "黑松鸡"    ,
"ptarmigan "    :    "鹧鸪"    ,
"ruffed grouse"    :    "松鸡松鸡"    ,
"prairie chicken"    :    "草原鸡"    ,
"peacock "    :    "孔雀"    ,
"quail "    :    "鹌鹑"    ,
"partridge "    :    "鹧鸪"    ,
"African grey"    :    "非洲灰色"    ,
"macaw "    :    "金刚鹦鹉"    ,
"sulphur-crested cockatoo"    :    "硫磺凤头鹦鹉"    ,
"lorikeet "    :    "吸蜜"    ,
"coucal "    :    "褐翅鸦鹃"    ,
"bee eater "    :    "蜜蜂食者"    ,
"hornbill "    :    "犀鸟"    ,
"hummingbird "    :    "蜂鸟"    ,
"jacamar "    :    "jacamar"    ,
"toucan "    :    "巨嘴鸟"    ,
"drake "    :    "鸭"    ,
"red-breasted merganser"    :    "红胸秋沙鸭"    ,
"goose "    :    "鹅"    ,
"black swan"    :    "黑天鹅"    ,
"white stork"    :    "白鹳"    ,
"black stork"    :    "黑鹳"    ,
"spoonbill "    :    "鹭"    ,
"flamingo "    :    "火烈鸟"    ,
"American egret"    :    "美国白鹭"    ,
"little blue heron"    :    "小蓝鹭"    ,
"bittern "    :    "卤水"    ,
"limpkin"    :    "秧鹤"    ,
"American coot"    :    "美国老傻瓜"    ,
"bustard "    :    "鸨鸟"    ,
"ruddy turnstone"    :    "红润的翻石"    ,
"red-backed sandpiper"    :    "红背鹬"    ,
"redshank"    :    "redshank"    ,
"dowitcher "    :    "dowitcher"    ,
"oystercatcher"    :    "蛎"    ,
"European gallinule"    :    "欧洲gallinule"    ,
"pelican "    :    "鹈"    ,
"king penguin"    :    "王企鹅"    ,
"albatross"    :    "信天翁"    ,
"great white shark"    :    "大白鲨"    ,
"tiger shark"    :    "虎鲨"    ,
"hammerhead"    :    "锤头"    ,
"electric ray"    :    "电射线"    ,
"stingray "    :    "黄貂鱼"    ,
"barracouta"    :    "barracouta"    ,
"coho"    :    "银鲑"    ,
"tench"    :    "丁鲷"    ,
"goldfish"    :    "金鱼"    ,
"eel "    :    "鳗鱼"    ,
"rock beauty"    :    "岩石之美"    ,
"anemone fish "    :    "海葵鱼"    ,
"lionfish "    :    "狮子鱼"    ,
"puffer"    :    "河豚"    ,
"sturgeon "    :    "鲟"    ,
"gar"    :    "噶尔"    ,
"loggerhead"    :    "糊涂虫"    ,
"mud turtle "    :    "泥龟"    ,
"terrapin "    :    "龟鳖"    ,
"box turtle"    :    "盒龟"    ,
"banded gecko "    :    "带壁虎"    ,
"common iguana"    :    "共同的鬣蜥"    ,
"American chameleon"    :    "美国变色龙"    ,
"whiptail"    :    "鞭尾"    ,
"agama "    :    "阿含"    ,
"frilled lizard"    :    "frilled蜥蜴"    ,
"alligator lizard "    :    "鳄鱼蜥蜴"    ,
"Gila monster"    :    "吉拉怪物"    ,
"green lizard"    :    "绿蜥蜴"    ,
"African chameleon"    :    "非洲变色龙"    ,
"Komodo dragon"    :    "科莫多巨蜥"    ,
"triceratops "    :    "三角龙"    ,
"African crocodile"    :    "非洲鳄鱼"    ,
"American alligator"    :    "美国短吻鳄"    ,
"thunder snake"    :    "雷蛇"    ,
"ringneck snake"    :    "戒指蛇"    ,
"hognose snake"    :    "猪鼻蛇"    ,
"green snake"    :    "青蛇"    ,
"king snake"    :    "王蛇"    ,
"garter snake"    :    "袜带蛇"    ,
"water snake "    :    "水蛇"    ,
"vine snake "    :    "藤蛇"    ,
"night snake"    :    "晚上蛇"    ,
"boa constrictor"    :    "大蟒蛇"    ,
"rock python"    :    "岩蟒"    ,
"Indian cobra"    :    "印度眼镜蛇"    ,
"green mamba "    :    "绿曼巴"    ,
"sea snake "    :    "海蛇"    ,
"horned viper"    :    "有角的毒蛇"    ,
"stone wall "    :    "石墙"    ,
"sidewinder"    :    "响尾蛇"    ,
"European fire salamander"    :    "欧洲火蝾螈"    ,
"common newt"    :    "共同的蝾螈"    ,
"eft "    :    "鲵"    ,
"spotted salamander"    :    "发现蝾螈"    ,
"axolotl"    :    "蝾螈"    ,
"bullfrog"    :    "牛蛙"    ,
"tree frog"    :    "树蛙"    ,
"tailed frog"    :    "被盯梢的青蛙"    ,
"whistle "    :    "哨"    ,
"wing "    :    "翅膀"    ,
"paintbrush "    :    "画笔"    ,
"oxygen mask "    :    "氧气面罩"    ,
"snorkel "    :    "浮潜"    ,
"loudspeaker"    :    "喇叭"    ,
"microphone"    :    "麦克风"    ,
"screen"    :    "屏幕"    ,
"mouse"    :    "老鼠"    ,
"electric fan"    :    "电扇"    ,
"oil filter "    :    "机油滤清器"    ,
"strainer "    :    "过滤器"    ,
"space heater "    :    "小型供暖器"    ,
"stove "    :    "火炉"    ,
"guillotine "    :    "断头台"    ,
"barometer "    :    "晴雨表"    ,
"rule"    :    "规则"    ,
"odometer"    :    "里程表"    ,
"scale"    :    "规模"    ,
"analog clock "    :    "模拟时钟"    ,
"digital clock "    :    "数码时钟"    ,
"wall clock "    :    "挂钟"    ,
"hourglass "    :    "滴漏"    ,
"sundial "    :    "晷"    ,
"parking meter "    :    "停车收费表"    ,
"stopwatch"    :    "跑表"    ,
"digital watch "    :    "数字手表"    ,
"stethoscope "    :    "听筒"    ,
"syringe "    :    "注射器"    ,
"magnetic compass "    :    "磁罗盘"    ,
"binoculars"    :    "望远镜"    ,
"projector "    :    "放映机"    ,
"sunglasses"    :    "墨镜"    ,
"loupe"    :    "放大镜"    ,
"radio telescope"    :    "射电望远镜"    ,
"bow "    :    "弓"    ,
"cannon "    :    "大炮"    ,
"assault rifle"    :    "突击步枪"    ,
"rifle "    :    "步枪"    ,
"projectile"    :    "抛射物"    ,
"computer keyboard"    :    "计算机键盘"    ,
"typewriter keyboard "    :    "打字机键盘"    ,
"crane "    :    "起重机"    ,
"lighter"    :    "打火机"    ,
"abacus "    :    "算盘"    ,
"cash machine"    :    "自动取款机"    ,
"slide rule"    :    "幻灯片规则"    ,
"desktop computer "    :    "台式电脑"    ,
"hand-held computer"    :    "手提电脑"    ,
"notebook"    :    "笔记本"    ,
"padlock "    :    "挂锁"    ,
"harvester"    :    "收割机"    ,
"thresher"    :    "脱粒机"    ,
"printer "    :    "打印机"    ,
"slot"    :    "插槽"    ,
"vending machine "    :    "售货机"    ,
"sewing machine "    :    "缝纫机"    ,
"joystick "    :    "操纵杆"    ,
"switch"    :    "开关"    ,
"hook"    :    "钩"    ,
"car wheel "    :    "车轮"    ,
"paddlewheel"    :    "桨轮"    ,
"pinwheel "    :    "风车"    ,
"potter's wheel "    :    "陶轮"    ,
"gas pump"    :    "加油站"    ,
"carousel"    :    "圆盘传送带"    ,
"swing "    :    "摇摆"    ,
"reel "    :    "卷轴"    ,
"radiator "    :    "散热器"    ,
"puck"    :    "冰球"    ,
"hard disc"    :    "硬盘"    ,
"sunglass "    :    "太阳镜"    ,
"pick"    :    "挑"    ,
"car mirror "    :    "车镜"    ,
"solar dish"    :    "太阳能碟"    ,
"remote control"    :    "遥控"    ,
"disk brake"    :    "盘式制动器"    ,
"buckle "    :    "扣"    ,
"hair slide "    :    "头发幻灯片"    ,
"knot "    :    "结"    ,
"combination lock "    :    "密码锁"    ,
"web site"    :    "网站"    ,
"nail "    :    "钉"    ,
"safety pin "    :    "安全别针"    ,
"screw "    :    "拧"    ,
"muzzle "    :    "枪口"    ,
"seat belt"    :    "安全带"    ,
"ski "    :    "滑雪"    ,
"candle"    :    "蜡烛"    ,
"jack-o'-lantern "    :    "鬼火"    ,
"spotlight"    :    "聚光灯"    ,
"torch "    :    "火炬"    ,
"neck brace "    :    "颈托"    ,
"pier "    :    "码头"    ,
"tripod "    :    "鼎"    ,
"maypole "    :    "五朔节花柱"    ,
"hand blower"    :    "手吹风机"    ,
"mousetrap "    :    "捕鼠器"    ,
"spider web"    :    "蜘蛛网"    ,
"trilobite "    :    "三叶虫"    ,
"harvestman"    :    "harvestman"    ,
"scorpion "    :    "蝎"    ,
"black and gold garden spider"    :    "黑色和金色的花园蜘蛛"    ,
"barn spider"    :    "谷仓蜘蛛"    ,
"garden spider"    :    "花园蜘蛛"    ,
"black widow"    :    "黑寡妇"    ,
"tarantula "    :    "狼蛛"    ,
"wolf spider"    :    "狼蛛"    ,
"tick "    :    "蜱"    ,
"centipede "    :    "蜈"    ,
"isopod "    :    "等足"    ,
"Dungeness crab"    :    "太平洋蟹"    ,
"rock crab"    :    "岩蟹"    ,
"fiddler crab "    :    "提琴手螃蟹"    ,
"king crab"    :    "鲎"    ,
"American lobster"    :    "美国龙虾"    ,
"spiny lobster"    :    "多刺的龙虾"    ,
"crayfish"    :    "小龙虾"    ,
"hermit crab "    :    "寄居蟹"    ,
"tiger beetle "    :    "老虎甲虫"    ,
"ladybug"    :    "瓢虫"    ,
"ground beetle"    :    "地面甲虫"    ,
"long-horned beetle"    :    "长角的甲虫"    ,
"leaf beetle"    :    "叶甲虫"    ,
"dung beetle "    :    "粪甲虫"    ,
"rhinoceros beetle "    :    "犀牛甲虫"    ,
"weevil "    :    "象鼻虫"    ,
"fly "    :    "飞"    ,
"bee "    :    "蜜蜂"    ,
"grasshopper"    :    "蚱蜢"    ,
"cricket "    :    "蟋蟀"    ,
"walking stick"    :    "拐杖"    ,
"cockroach"    :    "蟑螂"    ,
"mantis"    :    "螂"    ,
"cicada"    :    "蝉"    ,
"leafhopper "    :    "叶蝉"    ,
"lacewing"    :    "草蛉"    ,
"dragonfly"    :    "蜻蜓"    ,
"damselfly "    :    "豆娘"    ,
"admiral "    :    "上将"    ,
"ringlet"    :    "小环"    ,
"monarch"    :    "君主"    ,
"cabbage butterfly "    :    "菜粉蝶"    ,
"sulphur butterfly"    :    "硫蝴蝶"    ,
"lycaenid"    :    "lycaenid"    ,
"jellyfish "    :    "海蜇"    ,
"sea anemone"    :    "海葵"    ,
"brain coral "    :    "脑珊瑚"    ,
"flatworm"    :    "扁虫"    ,
"nematode"    :    "线虫"    ,
"conch "    :    "海螺"    ,
"snail "    :    "蜗牛"    ,
"slug "    :    "金属块"    ,
"sea slug"    :    "海蛞蝓"    ,
"chiton"    :    "宽大长袍"    ,
"sea urchin "    :    "海胆"    ,
"sea cucumber"    :    "海参"    ,
"iron"    :    "铁"    ,
"espresso maker "    :    "浓缩咖啡机"    ,
"microwave"    :    "微波"    ,
"Dutch oven "    :    "荷兰烤箱"    ,
"rotisserie "    :    "烤肉店"    ,
"toaster "    :    "烤面包机"    ,
"waffle iron "    :    "华夫饼铁"    ,
"vacuum"    :    "真空"    ,
"dishwasher"    :    "洗碗机"    ,
"refrigerator"    :    "冰箱"    ,
"washer"    :    "垫圈"    ,
"Crock Pot "    :    "缸罐"    ,
"frying pan"    :    "平底锅"    ,
"wok "    :    "炒锅"    ,
"caldron"    :    "甑"    ,
"coffeepot "    :    "咖啡壶"    ,
"teapot "    :    "茶壶"    ,
"spatula "    :    "抹刀"    ,
"altar "    :    "坛"    ,
"triumphal arch "    :    "凯旋门"    ,
"patio"    :    "庭院"    ,
"steel arch bridge "    :    "钢拱桥"    ,
"suspension bridge "    :    "吊桥"    ,
"viaduct "    :    "高架桥"    ,
"barn "    :    "谷仓"    ,
"greenhouse"    :    "温室"    ,
"palace "    :    "宫"    ,
"monastery "    :    "修道院"    ,
"library "    :    "图书馆"    ,
"apiary"    :    "蜂房"    ,
"boathouse "    :    "船屋"    ,
"church"    :    "教会"    ,
"mosque "    :    "清真寺"    ,
"stupa"    :    "佛塔"    ,
"planetarium "    :    "天文馆"    ,
"restaurant"    :    "餐厅"    ,
"cinema"    :    "电影"    ,
"home theater"    :    "家庭电影院"    ,
"lumbermill"    :    "伐木场"    ,
"coil"    :    "盘"    ,
"obelisk "    :    "方尖碑"    ,
"totem pole "    :    "图腾柱"    ,
"castle "    :    "城堡"    ,
"prison"    :    "监狱"    ,
"grocery store"    :    "杂货店"    ,
"bakery"    :    "面包店"    ,
"barbershop "    :    "理发店"    ,
"bookshop"    :    "书店"    ,
"butcher shop"    :    "肉店"    ,
"confectionery"    :    "糕饼"    ,
"shoe shop"    :    "鞋店"    ,
"tobacco shop"    :    "烟草店"    ,
"toyshop "    :    "玩具店"    ,
"fountain "    :    "喷泉"    ,
"cliff dwelling "    :    "悬崖住宅"    ,
"yurt "    :    "蒙古包"    ,
"dock"    :    "码头"    ,
"brass"    :    "黄铜"    ,
"megalith"    :    "巨石"    ,
"bannister"    :    "栏干"    ,
"breakwater"    :    "矶"    ,
"dam"    :    "坝"    ,
"chainlink fence "    :    "chainlink围栏"    ,
"picket fence"    :    "栅栏"    ,
"worm fence"    :    "蠕虫篱笆"    ,
"diamondback"    :    "菱"    ,
"grille"    :    "进气格栅"    ,
"sliding door "    :    "滑行门"    ,
"turnstile "    :    "旋转门"    ,
"mountain tent "    :    "山帐篷"    ,
"scoreboard "    :    "记分牌"    ,
"honeycomb "    :    "蜂窝"    ,
"plate rack "    :    "盘架"    ,
"pedestal"    :    "座"    ,
"beacon"    :    "烽火"    ,
"leatherback turtle"    :    "棱皮龟"    ,
"mashed potato "    :    "土豆泥"    ,
"bell pepper "    :    "灯笼椒"    ,
"head cabbage "    :    "卷心菜头"    ,
"broccoli "    :    "西兰花"    ,
"cauliflower "    :    "菜花"    ,
"zucchini"    :    "夏南瓜"    ,
"spaghetti squash "    :    "意粉南瓜"    ,
"acorn squash "    :    "橡子壁球"    ,
"butternut squash "    :    "冬南瓜"    ,
"cucumber"    :    "黄瓜"    ,
"artichoke"    :    "朝鲜蓟"    ,
"cardoon "    :    "刺苞菜蓟"    ,
"mushroom "    :    "蘑菇"    ,
"shower curtain "    :    "浴帘"    ,
"jean"    :    "牛仔"    ,
"carton "    :    "纸板箱"    ,
"handkerchief"    :    "手帕"    ,
"sandal "    :    "檀香"    ,
"ashcan"    :    "垃圾桶"    ,
"safe "    :    "安全"    ,
"plate "    :    "盘子"    ,
"necklace "    :    "项链"    ,
"croquet ball "    :    "槌球"    ,
"fur coat "    :    "皮毛大衣"    ,
"thimble "    :    "顶针"    ,
"pajama"    :    "睡衣"    ,
"running shoe "    :    "跑鞋"    ,
"oboe"    :    "双簧管"    ,
"cocktail shaker "    :    "鸡尾酒调酒器"    ,
"chest "    :    "胸部"    ,
"manhole cover "    :    "井盖"    ,
"modem "    :    "调制解调器"    ,
"tub"    :    "桶"    ,
"tray "    :    "托盘"    ,
"balance beam"    :    "平衡木"    ,
"bagel"    :    "面包圈"    ,
"violin"    :    "小提琴"    ,
"prayer rug"    :    "祈祷地毯"    ,
"kimono "    :    "和服"    ,
"hot pot"    :    "火锅"    ,
"whiskey jug "    :    "威士忌壶"    ,
"knee pad "    :    "护膝"    ,
"book jacket"    :    "书夹克"    ,
"spindle "    :    "纺锤"    ,
"ski mask "    :    "滑雪面罩"    ,
"beer bottle "    :    "啤酒瓶"    ,
"crash helmet "    :    "防撞头盔"    ,
"bottlecap "    :    "瓶盖"    ,
"tile roof "    :    "瓦屋顶"    ,
"mask "    :    "面具"    ,
"maillot "    :    "运动衣"    ,
"Petri dish "    :    "培养皿"    ,
"football helmet "    :    "橄榄球头盔"    ,
"bathing cap"    :    "浴帽"    ,
"teddy"    :    "泰迪熊"    ,
"holster "    :    "皮套"    ,
"pop bottle"    :    "流行音乐瓶"    ,
"photocopier "    :    "复印机"    ,
"vestment "    :    "法衣"    ,
"crossword puzzle"    :    "填字游戏"    ,
"golf ball "    :    "高尔夫球"    ,
"trifle "    :    "琐事"    ,
"suit"    :    "适合"    ,
"water tower "    :    "水塔"    ,
"feather boa"    :    "羽毛围巾"    ,
"cloak "    :    "披风"    ,
"red wine "    :    "红酒"    ,
"drumstick "    :    "鼓槌"    ,
"shield"    :    "屏蔽"    ,
"Christmas stocking "    :    "圣诞节放养"    ,
"hoopskirt"    :    "hoopskirt"    ,
"menu "    :    "菜单"    ,
"stage "    :    "阶段"    ,
"bonnet"    :    "帽子"    ,
"meat loaf"    :    "肉饼"    ,
"baseball "    :    "棒球"    ,
"face powder "    :    "香粉"    ,
"scabbard "    :    "刀鞘"    ,
"sunscreen"    :    "防晒"    ,
"beer glass "    :    "啤酒杯"    ,
"hen-of-the-woods"    :    "母鸡的最树林"    ,
"guacamole "    :    "鳄梨"    ,
"wool"    :    "羊毛"    ,
"hay "    :    "干草"    ,
"bow tie"    :    "领结"    ,
"mailbag"    :    "邮袋"    ,
"water jug "    :    "水壶"    ,
"bucket"    :    "桶"    ,
"dishrag"    :    "抹布"    ,
"soup bowl "    :    "汤碗"    ,
"eggnog "    :    "蛋酒"    ,
"mortar "    :    "砂浆"    ,
"trench coat "    :    "风衣"    ,
"paddle"    :    "桨"    ,
"chain "    :    "链"    ,
"swab"    :    "拖把"    ,
"mixing bowl "    :    "搅拌碗"    ,
"potpie "    :    "锅饼"    ,
"wine bottle "    :    "葡萄酒瓶"    ,
"shoji "    :    "商事"    ,
"bulletproof vest "    :    "防弹背心"    ,
"drilling platform"    :    "钻井平台"    ,
"binder"    :    "粘合剂"    ,
"cardigan "    :    "羊毛衣"    ,
"sweatshirt "    :    "运动衫"    ,
"pot"    :    "锅"    ,
"birdhouse "    :    "鸟巢"    ,
"jinrikisha"    :    "黄包车"    ,
"hamper "    :    "阻碍"    ,
"ping-pong ball "    :    "乒乓球"    ,
"pencil box"    :    "铅笔盒"    ,
"consomme "    :    "清汤"    ,
"apron "    :    "围裙"    ,
"punching bag"    :    "出气筒"    ,
"backpack"    :    "背包"    ,
"groom"    :    "马夫"    ,
"bearskin"    :    "熊皮"    ,
"pencil sharpener "    :    "卷笔刀"    ,
"broom "    :    "扫帚"    ,
"abaya "    :    "阿巴亚"    ,
"mortarboard "    :    "砂浆板"    ,
"poncho "    :    "雨披"    ,
"crutch "    :    "拐杖"    ,
"Polaroid camera"    :    "宝丽来相机"    ,
"space bar "    :    "空间酒吧"    ,
"cup "    :    "杯子"    ,
"racket"    :    "球拍"    ,
"traffic light"    :    "红绿灯"    ,
"quill"    :    "鹅毛笔"    ,
"radio"    :    "无线电"    ,
"snow leopard"    :    "雪豹"    ,
"dough "    :    "面团"    ,
"cuirass "    :    "胸甲"    ,
"military uniform "    :    "军装"    ,
"lipstick"    :    "口红"    ,
"shower cap "    :    "浴帽"    ,
"monitor "    :    "监控"    ,
"oscilloscope"    :    "示波器"    ,
"mitten "    :    "手套"    ,
"brassiere"    :    "乳罩"    ,
"French loaf "    :    "法国面包"    ,
"vase "    :    "花瓶"    ,
"milk can "    :    "牛奶可以"    ,
"rugby ball "    :    "橄榄球"    ,
"paper towel "    :    "纸巾"    ,
"earthstar "    :    "earthstar"    ,
"envelope "    :    "信封"    ,
"miniskirt"    :    "迷你裙"    ,
"cowboy hat"    :    "牛仔帽"    ,
"trolleybus"    :    "电车"    ,
"perfume"    :    "香水"    ,
"bathtub"    :    "浴缸"    ,
"hotdog"    :    "热狗"    ,
"coral fungus "    :    "珊瑚菌"    ,
"bullet train"    :    "子弹头列车"    ,
"pillow "    :    "枕头"    ,
"toilet tissue"    :    "卫生纸"    ,
"cassette "    :    "暗盒"    ,
"carpenter's kit"    :    "木匠的工具包"    ,
"ladle "    :    "瓢"    ,
"stinkhorn"    :    "stinkhorn"    ,
"lotion "    :    "洗剂"    ,
"hair spray "    :    "发胶"    ,
"academic gown"    :    "学院礼服"    ,
"dome "    :    "拱顶"    ,
"crate "    :    "箱"    ,
"wig "    :    "假发"    ,
"burrito "    :    "卷饼"    ,
"pill bottle "    :    "药瓶"    ,
"chain mail"    :    "连锁邮件"    ,
"theater curtain"    :    "剧院幕布"    ,
"window shade "    :    "窗帘"    ,
"barrel"    :    "桶"    ,
"washbasin"    :    "脸盆"    ,
"ballpoint"    :    "圆珠笔"    ,
"basketball "    :    "篮球"    ,
"bath towel "    :    "浴巾"    ,
"cowboy boot "    :    "牛仔靴"    ,
"gown "    :    "袍"    ,
"window screen "    :    "窗纱"    ,
"agaric "    :    "伞菌"    ,
"standard poodle "    :    "标准贵宾犬"    ,
"cellular telephone"    :    "蜂窝电话"    ,
"nipple "    :    "乳头"    ,
"barbell "    :    "杠铃"    ,
"mailbox"    :    "邮箱"    ,
"lab coat"    :    "实验工作服"    ,
"fire screen"    :    "防火屏"    ,
"minibus "    :    "小巴"    ,
"packet "    :    "包"    ,
"brown bear"    :    "棕熊"    ,
"pole "    :    "极"    ,
"horizontal bar"    :    "单杠"    ,
"sombrero "    :    "宽边帽"    ,
"pickelhaube "    :    "钉盔"    ,
"rain barrel "    :    "雨桶"    ,
"wallet"    :    "钱包"    ,
"cassette player "    :    "卡带机"    ,
"comic book "    :    "漫画书"    ,
"piggy bank"    :    "储钱罐"    ,
"street sign "    :    "街道路标"    ,
"bell cote"    :    "钟形棚"    ,
"fountain pen "    :    "钢笔"    ,
"Windsor tie "    :    "温莎领带"    ,
"volleyball "    :    "排球"    ,
"overskirt "    :    "罩裙"    ,
"sarong "    :    "纱笼"    ,
"purse "    :    "钱包"    ,
"bolo tie"    :    "bolo领带"    ,
"bib "    :    "围兜"    ,
"parachute"    :    "降落伞"    ,
"sleeping bag "    :    "睡袋"    ,
"television"    :    "电视"    ,
"swimming trunks"    :    "游泳裤"    ,
"measuring cup "    :    "量杯"    ,
"espresso "    :    "浓咖啡"    ,
"pizza"    :    "比萨"    ,
"breastplate"    :    "护胸甲"    ,
"shopping basket "    :    "购物篮"    ,
"wooden spoon "    :    "木勺子"    ,
"saltshaker"    :    "saltshaker"    ,
"chocolate sauce"    :    "巧克力酱"    ,
"ballplayer"    :    "球坛"    ,
"goblet "    :    "高脚杯"    ,
"gyromitra "    :    "gyromitra"    ,
"stretcher "    :    "担架"    ,
"water bottle "    :    "水瓶"    ,
"skunk"    :    "臭鼬"    ,
"soap dispenser "    :    "皂液器"    ,
"jersey"    :    "球衣"    ,
"school bus "    :    "校车"    ,
"jigsaw puzzle "    :    "拼图游戏"    ,
"plastic bag "    :    "塑料袋"    ,
"reflex camera "    :    "反光照相机"    ,
"diaper"    :    "尿布"    ,
"Band Aid "    :    "创可贴"    ,
"ice lolly"    :    "冰棒"    ,
"velvet "    :    "丝绒"    ,
"tennis ball "    :    "网球"    ,
"gasmask"    :    "防毒面具"    ,
"doormat"    :    "门垫"    ,
"Loafer "    :    "浪子"    ,
"ice cream"    :    "冰淇淋"    ,
"pretzel "    :    "椒盐卷饼"    ,
"quilt"    :    "被子"    ,
"maillot"    :    "运动衣"    ,
"tape player "    :    "磁带播放器"    ,
"clog"    :    "阻塞"    ,
"iPod "    :    "iPod的"    ,
"bolete "    :    "牛肝菌"    ,
"meerkat"    :    "猫鼬"    ,
"scuba diver "    :    "潜水员"    ,
"pitcher"    :    "投手"    ,
"matchstick "    :    "火柴"    ,
"bikini"    :    "比基尼泳装"    ,
"sock "    :    "袜子"    ,
"CD player "    :    "光碟播放器"    ,
"lens cap"    :    "镜头盖"    ,
"thatch"    :    "苫"    ,
"vault "    :    "拱顶"    ,
"beaker "    :    "烧杯"    ,
"bubble "    :    "泡沫"    ,
"cheeseburger "    :    "乳酪汉堡"    ,
"parallel bars"    :    "双杠"    ,
"flagpole"    :    "旗杆"    ,
"coffee mug "    :    "咖啡杯"    ,
"rubber eraser"    :    "橡皮擦"    ,
"stole "    :    "偷了"    ,
"carbonara"    :    "培根蛋面"    ,
"dumbbell"    :    "哑铃"
]
