//
//  simpChinese.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-12.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let simpChinese = [
    "person"     :    "人"    ,
    "bicycle"    :    "自行车"    ,
    "car"        :    "汽车"    ,
    "motorcycle"    :    "摩托车"    ,
    "bird"    :    "鸟"    ,
    "cat"    :    "猫"    ,
    "dog"    :    "狗"    ,
    "horse"    :    "马"    ,
    "sheep"    :    "羊"    ,
    "bottle"    :    "瓶子"    ,
    "chair"    :    "椅子"    ,
    "couch"    :    "长椅"    ,
    "potted plant"    :    "盆栽"    ,
    "tv"    :    "电视"    ,
    "cow"    :    "牛"    ,
    "airplane"    :    "飞机"    ,
    "hat"    :    "帽子"    ,
    "license plate"    :    "牌照"    ,
    "bed"    :    "床"    ,
    "laptop"    :    "笔记本电脑"    ,
    "fridge"    :    "冰箱"    ,
    "microwave"    :    "微波"    ,
    "sink"    :    "水槽"    ,
    "oven"    :    "烤箱"    ,
    "toaster"    :    "烤面包机"    ,
    "bus"    :    "总线"    ,
    "train"    :    "培养"    ,
    "mirror"    :    "镜子"    ,
    "dining table"    :    "餐桌"    ,
    "elephant"    :    "象"    ,
    "banana"    :    "香蕉"    ,
    "bread"    :    "面包"    ,
    "toilet"    :    "厕所"    ,
    "book"    :    "书"    ,
    "boat"    :    "船"    ,
    "plate"    :    "盘子"    ,
    "cellphone"    :    "手机"    ,
    "mouse"    :    "老鼠"    ,
    "remote"    :    "远程"    ,
    "clock"    :    "时钟"    ,
    "face"    :    "面对"    ,
    "hand"    :    "手"    ,
    "apple"    :    "苹果"    ,
    "keyboard"    :    "键盘"    ,
    "backpack"    :    "背包"    ,
    "steering wheel"    :    "方向盘"    ,
    "wineglass"    :    "红酒杯"    ,
    "chicken"    :    "鸡"    ,
    "zebra"    :    "斑马"    ,
    "shoe"    :    "鞋"    ,
    "eye"    :    "眼"    ,
    "mouth"    :    "口"    ,
    "scissors"    :    "剪刀"    ,
    "truck"    :    "卡车"    ,
    "traffic light"    :    "红绿灯"    ,
    "eyeglasses"    :    "眼镜"    ,
    "cup"    :    "杯子"    ,
    "blender"    :    "搅拌机"    ,
    "hairdrier"    :    "吹风机"    ,
    "wheel"    :    "轮"    ,
    "streetsign"    :    "街道路标"    ,
    "umbrella"    :    "雨伞"    ,
    "door"    :    "门"    ,
    "firehydrant"    :    "消防栓"    ,
    "bowl"    :    "碗"    ,
    "teapot"    :    "茶壶"    ,
    "fork"    :    "叉子"    ,
    "knife"    :    "刀"    ,
    "spoon"    :    "勺"    ,
    "bear"    :    "熊"    ,
    "headlights"    :    "头灯"    ,
    "window"    :    "窗口"    ,
    "desk"    :    "台"    ,
    "computer"    :    "电脑"    ,
    "refrigerator"    :    "冰箱"    ,
    "pizza"    :    "比萨"    ,
    "squirrel"    :    "松鼠"    ,
    "duck"    :    "鸭"    ,
    "frisbee"    :    "飞盘"    ,
    "guitar"    :    "吉他"    ,
    "nose"    :    "鼻子"    ,
    "teddybear"    :    "泰迪熊"    ,
    "tie"    :    "领带"    ,
    "stopsign"    :    "停止标志"    ,
    "surfboard"    :    "冲浪板"    ,
    "sandwich"    :    "三明治"    ,
    "pen/pencil"    :    "钢笔铅笔"    ,
    "kite"    :    "风筝"    ,
    "orange"    :    "橙子"    ,
    "toothbrush"    :    "牙刷"    ,
    "printer"    :    "打印机"    ,
    "pans"    :    "锅"    ,
    "head"    :    "头"    ,
    "sports ball"    :    "运动球"    ,
    "broccoli"    :    "西兰花"    ,
    "suitcase"    :    "手提箱"    ,
    "carrot"    :    "胡萝卜"    ,
    "chandelier"    :    "吊灯"    ,
    "parking meter"    :    "停车收费表"    ,
    "fish"    :    "鱼"    ,
    "handbag"    :    "手提包"    ,
    "hotdog"    :    "热狗"    ,
    "stapler"    :    "订书机"    ,
    "basketball hoop"    :    "篮球框"    ,
    "donut"    :    "甜甜圈"    ,
    "vase"    :    "花瓶"    ,
    "baseball bat"    :    "棒球棒"    ,
    "baseball glove"    :    "棒球手套"    ,
    "giraffe"    :    "长颈鹿"    ,
    "jacket"    :    "夹克"    ,
    "skis"    :    "滑雪板"    ,
    "snowboard"    :    "单板滑雪"    ,
    "tablelamp"    :    "台灯"    ,
    "egg"    :    "蛋"    ,
    "door handle"    :    "门把手"    ,
    "power outlet"    :    "电源插座"    ,
    "hair"    :    "头发"    ,
    "tiger"    :    "虎"    ,
    "table"    :    "表"    ,
    "coffee table"    :    "咖啡桌"    ,
    "skate board"    :    "滑板"    ,
    "helicopter"    :    "直升机"    ,
    "tomato"    :    "番茄"    ,
    "tree"    :    "树"    ,
    "bunny"    :    "兔子"    ,
    "pillow"    :    "枕头"    ,
    "tennis racket"    :    "网球拍"    ,
    "cake"    :    "蛋糕"    ,
    "feet"    :    "脚"    ,
    "bench"    :    "长凳"    ,
    "chopping board"    :    "切菜板"    ,
    "washer"    :    "垫圈"    ,
    "lion"    :    "狮子"    ,
    "monkey"    :    "猴"    ,
    "hairbrush"    :    "发刷"    ,
    "light switch"    :    "灯开关"    ,
    "arms"    :    "武器"    ,
    "legs"    :    "腿"    ,
    "house"    :    "屋"    ,
    "cheese"    :    "起司"    ,
    "goat"    :    "山羊"    ,
    "magazine"    :    "杂志"    ,
    "key"    :    "键"    ,
    "picture"    :    "图片"    ,
    "frame"    :    "帧"    ,
    "cupcake"    :    "杯形饼"    ,
    "fan(ceil/floor)"    :    "风扇（小区/地板）"    ,
    "frogs"    :    "青蛙"    ,
    "rabbit"    :    "兔子"    ,
    "owl"    :    "猫头鹰"    ,
    "scarf"    :    "围巾"    ,
    "ears"    :    "耳朵"    ,
    "homephone"    :    "家庭电话"    ,
    "pig"    :    "猪"    ,
    "strawberries"    :    "草莓"    ,
    "pumpkin"    :    "南瓜"    ,
    "van"    :    "面包车"    ,
    "kangaroo"    :    "袋鼠"    ,
    "rhinoceros"    :    "犀牛"    ,
    "sailboat"    :    "帆船"    ,
    "deer"    :    "鹿"    ,
    "playing cards"    :    "玩纸牌"    ,
    "towel"    :    "毛巾"    ,
    "hyppo hyppo"    :    "hyppo hyppo"    ,
    "can"    :    "能够"    ,
    "dollar bill"    :    "美元的钞票"    ,
    "doll"    :    "娃娃"    ,
    "soup"    :    "汤"    ,
    "meat"    :    "肉"    ,
    "muffins"    :    "松饼"    ,
    "tire"    :    "胎"    ,
    "necklace"    :    "项链"    ,
    "tablet"    :    "片剂"    ,
    "corn"    :    "玉米"    ,
    "ladder"    :    "阶梯"    ,
    "pineapple"    :    "菠萝"    ,
    "candle"    :    "蜡烛"    ,
    "desktop"    :    "桌面"    ,
    "carpet"    :    "地毯"    ,
    "cookie"    :    "曲奇饼"    ,
    "toycars"    :    "玩具车"    ,
    "bracelet"    :    "手镯"    ,
    "bat"    :    "蝙蝠"    ,
    "balloon"    :    "气球"    ,
    "gloves"    :    "手套"    ,
    "milk"    :    "牛奶"    ,
    "pants"    :    "裤子"    ,
    "wheelchair"    :    "轮椅"    ,
    "building"    :    "建造"    ,
    "bacon"    :    "培根"    ,
    "box"    :    "框"    ,
    "platypus"    :    "鸭嘴兽"    ,
    "pancake"    :    "饼子"    ,
    "cabinet"    :    "内阁"    ,
    "whale"    :    "鲸"    ,
    "dryer"    :    "烘干机"    ,
    "torso"    :    "躯干"    ,
    "lizard"    :    "蜥蜴"    ,
    "shirt"    :    "衬衫"    ,
    "shorts"    :    "短裤"    ,
    "pasta"    :    "意大利面"    ,
    "grapes"    :    "葡萄"    ,
    "shark"    :    "鲨鱼"    ,
    "swan"    :    "天鹅"    ,
    "fingers"    :    "手指"    ,
    "sidetable"    :    "茶几"    ,
    "gate"    :    "门"    ,
    "beans"    :    "豆"    ,
    "flip flops"    :    "人字拖"    ,
    "moon"    :    "月亮"    ,
    "road/street/"    :    "道路/街道/"    ,
    "fountain"    :    "喷泉"    ,
    "faxmachine"    :    "传真机"    ,
    "hotair balloon"    :    "热气球"    ,
    "cereal"    :    "谷类"    ,
    "seahorse"    :    "海马"    ,
    "rocket"    :    "火箭"    ,
    "cabinets"    :    "橱柜"    ,
    "basketball"    :    "篮球"    ,
    "telephone"    :    "电话"    ,
    "movie(disc)"    :    "电影（光盘）"    ,
    "football"    :    "足球"    ,
    "goose"    :    "鹅"    ,
    "long-sleeve shirt"    :    "长袖衬衫"    ,
    "short-sleeve shirt"    :    "短袖上衣"    ,
    "raft"    :    "筏"    ,
    "rooster"    :    "公鸡"    ,
    "copier"    :    "复印机"    ,
    "radio"    :    "无线电"    ,
    "fences"    :    "围栏"    ,
    "goalnet"    :    "球门网"    ,
    "toys"    :    "玩具"    ,
    "engine"    :    "发动机"    ,
    "soccerball"    :    "足球"    ,
    "fieldgoal posts"    :    "场目标职位"    ,
    "socks"    :    "袜子"    ,
    "tennisnet"    :    "网球网"    ,
    "seats"    :    "席"    ,
    "elbows"    :    "肘部"    ,
    "aardvark"    :    "土豚"    ,
    "dinosaur"    :    "恐龙"    ,
    "unicycle"    :    "独轮车"    ,
    "honey"    :    "蜜糖"    ,
    "legos"    :    "积木"    ,
    "fly"    :    "飞"    ,
    "roof"    :    "屋顶"    ,
    "baseball"    :    "棒球"    ,
    "mat"    :    "垫"    ,
    "ipad"    :    "iPad"    ,
    "iphone"    :    "苹果手机"    ,
    "hoop"    :    "箍"    ,
    "hen"    :    "母鸡"    ,
    "back"    :    "背部"    ,
    "table cloth"    :    "桌布"    ,
    "soccer nets"    :    "足球网"    ,
    "turkey"    :    "火鸡"    ,
    "pajamas"    :    "睡衣"    ,
    "underpants"    :    "内裤"    ,
    "goldfish"    :    "金鱼"    ,
    "robot"    :    "机器人"    ,
    "crusher"    :    "破碎机"    ,
    "animal crackers"    :    "动物饼干"    ,
    "basketball court"    :    "篮球场"    ,
    "horn"    :    "喇叭"    ,
    "firefly"    :    "萤火虫"    ,
    "armpits"    :    "腋下"    ,
    "nectar"    :    "花蜜"    ,
    "superhero costume"    :    "超级英雄服装"    ,
    "jetpack"    :    "喷气背包"    ,
    "robots"    :    "机器人"
]
