//
//  spanish.swift
//  iKnow
//
//  Created by Shao-Wei Liang on 2018-03-28.
//  Copyright © 2018 Shao-Wei Liang. All rights reserved.
//

import Foundation

let spanish = [
    "person"    :    "persona"        ,
    "bicycle"    :    "bicicleta"        ,
    "car"    :    "coche"        ,
    "motorcycle"    :    "motocicleta"        ,
    "bird"    :    "pájaro"        ,
    "cat"    :    "gato"        ,
    "dog"    :    "perro"        ,
    "horse"    :    "caballo"        ,
    "sheep"    :    "oveja"        ,
    "bottle"    :    "botella"        ,
    "chair"    :    "silla"        ,
    "couch"    :    "sofá"        ,
    "potted plant"    :    "planta en maceta"        ,
    "tv"    :    "televisión"        ,
    "cow"    :    "vaca"        ,
    "airplane"    :    "avión"        ,
    "hat"    :    "sombrero"        ,
    "license plate"    :    "placa"        ,
    "bed"    :    "cama"        ,
    "laptop"    :    "ordenador portátil"        ,
    "fridge"    :    "refrigerador"        ,
    "microwave"    :    "microonda"        ,
    "sink"    :    "lavabo"        ,
    "oven"    :    "horno"        ,
    "toaster"    :    "tostadora"        ,
    "bus"    :    "autobús"        ,
    "train"    :    "tren"        ,
    "mirror"    :    "espejo"        ,
    "dining table"    :    "comedor"        ,
    "elephant"    :    "elefante"        ,
    "banana"    :    "plátano"        ,
    "bread"    :    "pan de molde"        ,
    "toilet"    :    "baño"        ,
    "book"    :    "libro"        ,
    "boat"    :    "barco"        ,
    "plate"    :    "plato"        ,
    "cellphone"    :    "Teléfono móvil"        ,
    "mouse"    :    "ratón"        ,
    "remote"    :    "remoto"        ,
    "clock"    :    "reloj"        ,
    "face"    :    "cara"        ,
    "hand"    :    "mano"        ,
    "apple"    :    "manzana"        ,
    "keyboard"    :    "teclado"        ,
    "backpack"    :    "mochila"        ,
    "steering wheel"    :    "volante"        ,
    "wineglass"    :    "Copa de vino"        ,
    "chicken"    :    "pollo"        ,
    "zebra"    :    "cebra"        ,
    "shoe"    :    "zapato"        ,
    "eye"    :    "ojo"        ,
    "mouth"    :    "boca"        ,
    "scissors"    :    "tijeras"        ,
    "truck"    :    "camión"        ,
    "traffic light"    :    "semáforo"        ,
    "eyeglasses"    :    "los anteojos"        ,
    "cup"    :    "vaso"        ,
    "blender"    :    "licuadora"        ,
    "hairdrier"    :    "Secadora de pelo"        ,
    "wheel"    :    "rueda"        ,
    "streetsign"    :    "cartel de la calle"        ,
    "umbrella"    :    "paraguas"        ,
    "door"    :    "puerta"        ,
    "firehydrant"    :    "antihielo"        ,
    "bowl"    :    "cuenco"        ,
    "teapot"    :    "tetera"        ,
    "fork"    :    "tenedor"        ,
    "knife"    :    "cuchillo"        ,
    "spoon"    :    "cuchara"        ,
    "bear"    :    "oso"        ,
    "headlights"    :    "faros"        ,
    "window"    :    "ventana"        ,
    "desk"    :    "escritorio"        ,
    "computer"    :    "computadora"        ,
    "refrigerator"    :    "refrigerador"        ,
    "pizza"    :    "Pizza"        ,
    "squirrel"    :    "ardilla"        ,
    "duck"    :    "pato"        ,
    "frisbee"    :    "frisbee"        ,
    "guitar"    :    "guitarra"        ,
    "nose"    :    "nariz"        ,
    "teddybear"    :    "oso de peluche"        ,
    "tie"    :    "Corbata"        ,
    "stopsign"    :    "señal de stop"        ,
    "surfboard"    :    "tabla de surf"        ,
    "sandwich"    :    "emparedado"        ,
    "pen/pencil"    :    "pluma lapiz"        ,
    "kite"    :    "cometa"        ,
    "orange"    :    "naranja"        ,
    "toothbrush"    :    "cepillo de dientes"        ,
    "printer"    :    "impresora"        ,
    "pans"    :    "sartenes"        ,
    "head"    :    "cabeza"        ,
    "sports ball"    :    "pelota deportiva"        ,
    "broccoli"    :    "brócoli"        ,
    "suitcase"    :    "maleta"        ,
    "carrot"    :    "Zanahoria"        ,
    "chandelier"    :    "candelabro"        ,
    "parking meter"    :    "parquímetro"        ,
    "fish"    :    "pescado"        ,
    "handbag"    :    "bolso"        ,
    "hotdog"    :    "Pancho"        ,
    "stapler"    :    "engrapadora"        ,
    "basketball hoop"    :    "aro de baloncesto"        ,
    "donut"    :    "rosquilla"        ,
    "vase"    :    "florero"        ,
    "baseball bat"    :    "bate de béisbol"        ,
    "baseball glove"    :    "guante de béisbol"        ,
    "giraffe"    :    "jirafa"        ,
    "jacket"    :    "chaqueta"        ,
    "skis"    :    "esquís"        ,
    "snowboard"    :    "snowboard"        ,
    "tablelamp"    :    "Lámpara de mesa"        ,
    "egg"    :    "huevo"        ,
    "door handle"    :    "manija de puerta"        ,
    "power outlet"    :    "Toma de corriente"        ,
    "hair"    :    "cabello"        ,
    "tiger"    :    "Tigre"        ,
    "table"    :    "mesa"        ,
    "coffee table"    :    "mesa de café"        ,
    "skate board"    :    "patineta"        ,
    "helicopter"    :    "helicóptero"        ,
    "tomato"    :    "tomate"        ,
    "tree"    :    "árbol"        ,
    "bunny"    :    "conejito"        ,
    "pillow"    :    "almohada"        ,
    "tennis racket"    :    "raqueta de tenis"        ,
    "cake"    :    "pastel"        ,
    "feet"    :    "pies"        ,
    "bench"    :    "banco"        ,
    "chopping board"    :    "tabla de cortar"        ,
    "washer"    :    "lavadora"        ,
    "lion"    :    "león"        ,
    "monkey"    :    "mono"        ,
    "hairbrush"    :    "cepillo para el pelo"        ,
    "light switch"    :    "Interruptor de luz"        ,
    "arms"    :    "brazos"        ,
    "legs"    :    "piernas"        ,
    "house"    :    "casa"        ,
    "cheese"    :    "queso"        ,
    "goat"    :    "cabra"        ,
    "magazine"    :    "revista"        ,
    "key"    :    "llave"        ,
    "picture"    :    "imagen"        ,
    "frame"    :    "marco"        ,
    "cupcake"    :    "cupcake"        ,
    "fan(ceil/floor)"    :    "ventilador (ceil / piso)"        ,
    "frogs"    :    "ranas"        ,
    "rabbit"    :    "Conejo"        ,
    "owl"    :    "búho"        ,
    "scarf"    :    "bufanda"        ,
    "ears"    :    "orejas"        ,
    "homephone"    :    "teléfono de casa"        ,
    "pig"    :    "cerdo"        ,
    "strawberries"    :    "fresas"        ,
    "pumpkin"    :    "calabaza"        ,
    "van"    :    "camioneta"        ,
    "kangaroo"    :    "canguro"        ,
    "rhinoceros"    :    "rinoceronte"        ,
    "sailboat"    :    "velero"        ,
    "deer"    :    "ciervo"        ,
    "playing cards"    :    "jugando a las cartas"        ,
    "towel"    :    "toalla"        ,
    "hyppo hyppo"    :    "hyppo hyppo"        ,
    "can"    :    "poder"        ,
    "dollar bill"    :    "billete de un dólar"        ,
    "doll"    :    "muñeca"        ,
    "soup"    :    "sopa"        ,
    "meat"    :    "carne"        ,
    "muffins"    :    "magdalenas"        ,
    "tire"    :    "neumático"        ,
    "necklace"    :    "collar"        ,
    "tablet"    :    "tableta"        ,
    "corn"    :    "maíz"        ,
    "ladder"    :    "escalera"        ,
    "pineapple"    :    "piña"        ,
    "candle"    :    "vela"        ,
    "desktop"    :    "escritorio"        ,
    "carpet"    :    "alfombra"        ,
    "cookie"    :    "Galleta"        ,
    "toycars"    :    "carros de juguete"        ,
    "bracelet"    :    "pulsera"        ,
    "bat"    :    "murciélago"        ,
    "balloon"    :    "globo"        ,
    "gloves"    :    "guantes"        ,
    "milk"    :    "Leche"        ,
    "pants"    :    "pantalones"        ,
    "wheelchair"    :    "silla de ruedas"        ,
    "building"    :    "edificio"        ,
    "bacon"    :    "tocino"        ,
    "box"    :    "caja"        ,
    "platypus"    :    "ornitorrinco"        ,
    "pancake"    :    "crepe"        ,
    "cabinet"    :    "gabinete"        ,
    "whale"    :    "ballena"        ,
    "dryer"    :    "secadora"        ,
    "torso"    :    "torso"        ,
    "lizard"    :    "lagartija"        ,
    "shirt"    :    "camisa"        ,
    "shorts"    :    "pantalones cortos"        ,
    "pasta"    :    "pastas"        ,
    "grapes"    :    "uvas"        ,
    "shark"    :    "tiburón"        ,
    "swan"    :    "cisne"        ,
    "fingers"    :    "dedos"        ,
    "sidetable"    :    "Mesa auxiliar"        ,
    "gate"    :    "portón"        ,
    "beans"    :    "frijoles"        ,
    "flip flops"    :    "chancletas"        ,
    "moon"    :    "Luna"        ,
    "road/street/"    :    "carretera/"        ,
    "fountain"    :    "fuente"        ,
    "faxmachine"    :    "máquina de fax"        ,
    "hotair balloon"    :    "globo aerostático"        ,
    "cereal"    :    "cereal"        ,
    "seahorse"    :    "caballo de mar"        ,
    "rocket"    :    "cohete"        ,
    "cabinets"    :    "armarios"        ,
    "basketball"    :    "baloncesto"        ,
    "telephone"    :    "teléfono"        ,
    "movie(disc)"    :    "película (disco)"        ,
    "football"    :    "fútbol"        ,
    "goose"    :    "ganso"        ,
    "long-sleeve shirt"    :    "camisa de manga larga"        ,
    "short-sleeve shirt"    :    "camisa manga corta"        ,
    "raft"    :    "balsa"        ,
    "rooster"    :    "gallo"        ,
    "copier"    :    "copiador"        ,
    "radio"    :    "radio"        ,
    "fences"    :    "vallas"        ,
    "goalnet"    :    "goalnet"        ,
    "toys"    :    "juguetes"        ,
    "engine"    :    "motor"        ,
    "soccerball"    :    "balón de fútbol"        ,
    "fieldgoal posts"    :    "mensajes de trabajo de campo"        ,
    "socks"    :    "calcetines"        ,
    "tennisnet"    :    "tennisnet"        ,
    "seats"    :    "asientos"        ,
    "elbows"    :    "codos"        ,
    "aardvark"    :    "cerdo hormiguero"        ,
    "dinosaur"    :    "dinosaurio"        ,
    "unicycle"    :    "monociclo"        ,
    "honey"    :    "miel"        ,
    "legos"    :    "legos"        ,
    "fly"    :    "mosca"        ,
    "roof"    :    "techo"        ,
    "baseball"    :    "béisbol"        ,
    "mat"    :    "estera"        ,
    "ipad"    :    "ipad"        ,
    "iphone"    :    "iphone"        ,
    "hoop"    :    "aro"        ,
    "hen"    :    "gallina"        ,
    "back"    :    "espalda"        ,
    "table cloth"    :    "Manteles"        ,
    "soccer nets"    :    "redes de fútbol"        ,
    "turkey"    :    "Turquía"        ,
    "pajamas"    :    "pijama"        ,
    "underpants"    :    "calzoncillos"        ,
    "goldfish"    :    "pez de colores"        ,
    "robot"    :    "robot"        ,
    "crusher"    :    "trituradora"        ,
    "animal crackers"    :    "Galletas de animales"        ,
    "basketball court"    :    "cancha de basketball"        ,
    "horn"    :    "cuerno"        ,
    "firefly"    :    "luciérnaga"        ,
    "armpits"    :    "axilas"        ,
    "nectar"    :    "néctar"        ,
    "superhero costume"    :    "traje de superhéroe"        ,
    "jetpack"    :    "jetpack"        ,
    "robots"    :    "robots"
]
