//Traditonal Chinese
let tradChinese = [
    "person"    :    "人"    ,
    "bicycle"    :    "自行車"    ,
    "car"    :    "汽車"    ,
    "motorcycle"    :    "摩托車"    ,
    "bird"    :    "鳥"    ,
    "cat"    :    "貓"    ,
    "dog"    :    "狗"    ,
    "horse"    :    "馬"    ,
    "sheep"    :    "羊"    ,
    "bottle"    :    "瓶子"    ,
    "chair"    :    "椅子"    ,
    "couch"    :    "長椅"    ,
    "potted plant"    :    "盆栽"    ,
    "tv"    :    "電視"    ,
    "cow"    :    "牛"    ,
    "airplane"    :    "飛機"    ,
    "hat"    :    "帽子"    ,
    "license plate"    :    "牌照"    ,
    "bed"    :    "床"    ,
    "laptop"    :    "筆記本電腦"    ,
    "fridge"    :    "冰箱"    ,
    "microwave"    :    "微波"    ,
    "sink"    :    "水槽"    ,
    "oven"    :    "烤箱"    ,
    "toaster"    :    "烤麵包機"    ,
    "bus"    :    "總線"    ,
    "train"    :    "培養"    ,
    "mirror"    :    "鏡子"    ,
    "dining table"    :    "餐桌"    ,
    "elephant"    :    "象"    ,
    "banana"    :    "香蕉"    ,
    "bread"    :    "麵包"    ,
    "toilet"    :    "廁所"    ,
    "book"    :    "書"    ,
    "boat"    :    "船"    ,
    "plate"    :    "盤子"    ,
    "cellphone"    :    "手機"    ,
    "mouse"    :    "老鼠"    ,
    "remote"    :    "遠程"    ,
    "clock"    :    "時鐘"    ,
    "face"    :    "面對"    ,
    "hand"    :    "手"    ,
    "apple"    :    "蘋果"    ,
    "keyboard"    :    "鍵盤"    ,
    "backpack"    :    "背包"    ,
    "steering wheel"    :    "方向盤"    ,
    "wineglass"    :    "紅酒杯"    ,
    "chicken"    :    "雞"    ,
    "zebra"    :    "斑馬"    ,
    "shoe"    :    "鞋"    ,
    "eye"    :    "眼"    ,
    "mouth"    :    "口"    ,
    "scissors"    :    "剪刀"    ,
    "truck"    :    "卡車"    ,
    "traffic light"    :    "紅綠燈"    ,
    "eyeglasses"    :    "眼鏡"    ,
    "cup"    :    "杯子"    ,
    "blender"    :    "攪拌機"    ,
    "hairdrier"    :    "吹風機"    ,
    "wheel"    :    "輪"    ,
    "streetsign"    :    "街道路標"    ,
    "umbrella"    :    "雨傘"    ,
    "door"    :    "門"    ,
    "firehydrant"    :    "消防栓"    ,
    "bowl"    :    "碗"    ,
    "teapot"    :    "茶壺"    ,
    "fork"    :    "叉子"    ,
    "knife"    :    "刀"    ,
    "spoon"    :    "勺"    ,
    "bear"    :    "熊"    ,
    "headlights"    :    "頭燈"    ,
    "window"    :    "窗口"    ,
    "desk"    :    "台"    ,
    "computer"    :    "電腦"    ,
    "refrigerator"    :    "冰箱"    ,
    "pizza"    :    "比薩"    ,
    "squirrel"    :    "松鼠"    ,
    "duck"    :    "鴨"    ,
    "frisbee"    :    "飛盤"    ,
    "guitar"    :    "吉他"    ,
    "nose"    :    "鼻子"    ,
    "teddybear"    :    "泰迪熊"    ,
    "tie"    :    "領帶"    ,
    "stopsign"    :    "停止標誌"    ,
    "surfboard"    :    "衝浪板"    ,
    "sandwich"    :    "三明治"    ,
    "pen/pencil"    :    "鋼筆鉛筆"    ,
    "kite"    :    "風箏"    ,
    "orange"    :    "橙子"    ,
    "toothbrush"    :    "牙刷"    ,
    "printer"    :    "打印機"    ,
    "pans"    :    "鍋"    ,
    "head"    :    "頭"    ,
    "sports ball"    :    "運動球"    ,
    "broccoli"    :    "西蘭花"    ,
    "suitcase"    :    "手提箱"    ,
    "carrot"    :    "胡蘿蔔"    ,
    "chandelier"    :    "吊燈"    ,
    "parking meter"    :    "停車收費表"    ,
    "fish"    :    "魚"    ,
    "handbag"    :    "手提包"    ,
    "hotdog"    :    "熱狗"    ,
    "stapler"    :    "訂書機"    ,
    "basketball hoop"    :    "籃球框"    ,
    "donut"    :    "甜甜圈"    ,
    "vase"    :    "花瓶"    ,
    "baseball bat"    :    "棒球棒"    ,
    "baseball glove"    :    "棒球手套"    ,
    "giraffe"    :    "長頸鹿"    ,
    "jacket"    :    "夾克"    ,
    "skis"    :    "滑雪板"    ,
    "snowboard"    :    "單板滑雪"    ,
    "tablelamp"    :    "檯燈"    ,
    "egg"    :    "蛋"    ,
    "door handle"    :    "門把手"    ,
    "power outlet"    :    "電源插座"    ,
    "hair"    :    "頭髮"    ,
    "tiger"    :    "虎"    ,
    "table"    :    "表"    ,
    "coffee table"    :    "咖啡桌"    ,
    "skate board"    :    "滑板"    ,
    "helicopter"    :    "直升機"    ,
    "tomato"    :    "番茄"    ,
    "tree"    :    "樹"    ,
    "bunny"    :    "兔子"    ,
    "pillow"    :    "枕頭"    ,
    "tennis racket"    :    "網球拍"    ,
    "cake"    :    "蛋糕"    ,
    "feet"    :    "腳"    ,
    "bench"    :    "長凳"    ,
    "chopping board"    :    "切菜板"    ,
    "washer"    :    "墊圈"    ,
    "lion"    :    "獅子"    ,
    "monkey"    :    "猴"    ,
    "hairbrush"    :    "髮刷"    ,
    "light switch"    :    "燈開關"    ,
    "arms"    :    "武器"    ,
    "legs"    :    "腿"    ,
    "house"    :    "屋"    ,
    "cheese"    :    "起司"    ,
    "goat"    :    "山羊"    ,
    "magazine"    :    "雜誌"    ,
    "key"    :    "鍵"    ,
    "picture"    :    "圖片"    ,
    "frame"    :    "幀"    ,
    "cupcake"    :    "杯形餅"    ,
    "fan(ceil/floor)"    :    "風扇（小區/地板）"    ,
    "frogs"    :    "青蛙"    ,
    "rabbit"    :    "兔子"    ,
    "owl"    :    "貓頭鷹"    ,
    "scarf"    :    "圍巾"    ,
    "ears"    :    "耳朵"    ,
    "homephone"    :    "家庭電話"    ,
    "pig"    :    "豬"    ,
    "strawberries"    :    "草莓"    ,
    "pumpkin"    :    "南瓜"    ,
    "van"    :    "麵包車"    ,
    "kangaroo"    :    "袋鼠"    ,
    "rhinoceros"    :    "犀牛"    ,
    "sailboat"    :    "帆船"    ,
    "deer"    :    "鹿"    ,
    "playing cards"    :    "玩紙牌"    ,
    "towel"    :    "毛巾"    ,
    "hyppo hyppo"    :    "hyppo hyppo"    ,
    "can"    :    "能夠"    ,
    "dollar bill"    :    "美元的鈔票"    ,
    "doll"    :    "娃娃"    ,
    "soup"    :    "湯"    ,
    "meat"    :    "肉"    ,
    "muffins"    :    "鬆餅"    ,
    "tire"    :    "胎"    ,
    "necklace"    :    "項鍊"    ,
    "tablet"    :    "片劑"    ,
    "corn"    :    "玉米"    ,
    "ladder"    :    "階梯"    ,
    "pineapple"    :    "菠蘿"    ,
    "candle"    :    "蠟燭"    ,
    "desktop"    :    "桌面"    ,
    "carpet"    :    "地毯"    ,
    "cookie"    :    "曲奇餅"    ,
    "toycars"    :    "玩具車"    ,
    "bracelet"    :    "手鐲"    ,
    "bat"    :    "蝙蝠"    ,
    "balloon"    :    "氣球"    ,
    "gloves"    :    "手套"    ,
    "milk"    :    "牛奶"    ,
    "pants"    :    "褲子"    ,
    "wheelchair"    :    "輪椅"    ,
    "building"    :    "建造"    ,
    "bacon"    :    "培根"    ,
    "box"    :    "框"    ,
    "platypus"    :    "鴨嘴獸"    ,
    "pancake"    :    "餅子"    ,
    "cabinet"    :    "內閣"    ,
    "whale"    :    "鯨"    ,
    "dryer"    :    "烘乾機"    ,
    "torso"    :    "軀幹"    ,
    "lizard"    :    "蜥蜴"    ,
    "shirt"    :    "襯衫"    ,
    "shorts"    :    "短褲"    ,
    "pasta"    :    "意大利面"    ,
    "grapes"    :    "葡萄"    ,
    "shark"    :    "鯊魚"    ,
    "swan"    :    "天鵝"    ,
    "fingers"    :    "手指"    ,
    "sidetable"    :    "茶几"    ,
    "gate"    :    "門"    ,
    "beans"    :    "豆"    ,
    "flip flops"    :    "人字拖"    ,
    "moon"    :    "月亮"    ,
    "road/street/"    :    "道路/街道/"    ,
    "fountain"    :    "噴泉"    ,
    "faxmachine"    :    "傳真機"    ,
    "hotair balloon"    :    "熱氣球"    ,
    "cereal"    :    "穀類"    ,
    "seahorse"    :    "海馬"    ,
    "rocket"    :    "火箭"    ,
    "cabinets"    :    "櫥櫃"    ,
    "basketball"    :    "籃球"    ,
    "telephone"    :    "電話"    ,
    "movie(disc)"    :    "電影（光盤）"    ,
    "football"    :    "足球"    ,
    "goose"    :    "鵝"    ,
    "long-sleeve shirt"    :    "長袖襯衫"    ,
    "short-sleeve shirt"    :    "短袖上衣"    ,
    "raft"    :    "筏"    ,
    "rooster"    :    "公雞"    ,
    "copier"    :    "複印機"    ,
    "radio"    :    "無線電"    ,
    "fences"    :    "圍欄"    ,
    "goalnet"    :    "球門網"    ,
    "toys"    :    "玩具"    ,
    "engine"    :    "發動機"    ,
    "soccerball"    :    "足球"    ,
    "fieldgoal posts"    :    "場目標職位"    ,
    "socks"    :    "襪子"    ,
    "tennisnet"    :    "網球網"    ,
    "seats"    :    "席"    ,
    "elbows"    :    "肘部"    ,
    "aardvark"    :    "土豚"    ,
    "dinosaur"    :    "恐龍"    ,
    "unicycle"    :    "獨輪車"    ,
    "honey"    :    "蜜糖"    ,
    "legos"    :    "積木"    ,
    "fly"    :    "飛"    ,
    "roof"    :    "屋頂"    ,
    "baseball"    :    "棒球"    ,
    "mat"    :    "墊"    ,
    "ipad"    :    "iPad的"    ,
    "iphone"    :    "蘋果手機"    ,
    "hoop"    :    "箍"    ,
    "hen"    :    "母雞"    ,
    "back"    :    "背部"    ,
    "table cloth"    :    "桌布"    ,
    "soccer nets"    :    "足球網"    ,
    "turkey"    :    "火雞"    ,
    "pajamas"    :    "睡衣"    ,
    "underpants"    :    "內褲"    ,
    "goldfish"    :    "金魚"    ,
    "robot"    :    "機器人"    ,
    "crusher"    :    "破碎機"    ,
    "animal crackers"    :    "動物餅乾"    ,
    "basketball court"    :    "籃球場"    ,
    "horn"    :    "喇叭"    ,
    "firefly"    :    "螢火蟲"    ,
    "armpits"    :    "腋下"    ,
    "nectar"    :    "花蜜"    ,
    "superhero costume"    :    "超級英雄服​​裝"    ,
    "jetpack"    :    "噴氣背包"    ,
    "robots"    :    "機器人"
]
