//Traditonal Chinese
let tradChinese = [
    "kit fox"    :    "工具箱狐狸"    ,
    "English setter "    :    "英語二傳手"    ,
    "Australian terrier "    :    "澳大利亞梗"    ,
    "grey whale"    :    "灰鯨"    ,
    "lesser panda"    :    "小熊貓"    ,
    "Egyptian cat "    :    "埃及貓"    ,
    "ibex"    :    "山羊"    ,
    "Persian cat "    :    "波斯貓"    ,
    "cougar"    :    "美洲獅"    ,
    "gazelle "    :    "羚羊"    ,
    "porcupine"    :    "豪豬"    ,
    "sea lion "    :    "海獅"    ,
    "badger "    :    "獾"    ,
    "Great Dane "    :    "大丹犬"    ,
    "Scottish deerhound"    :    "蘇格蘭獵鹿犬"    ,
    "killer whale"    :    "虎鯨"    ,
    "mink "    :    "貂"    ,
    "African elephant"    :    "非洲大象"    ,
    "red wolf"    :    "紅狼"    ,
    "jaguar"    :    "捷豹"    ,
    "hyena"    :    "鬣狗"    ,
    "titi"    :    "titi"    ,
    "three-toed sloth"    :    "三趾樹懶"    ,
    "sorrel "    :    "酢漿草"    ,
    "black-footed ferret"    :    "黑腳鼬"    ,
    "dalmatian"    :    "達爾馬提亞狗"    ,
    "Staffordshire bullterrier"    :    "斯塔福郡鬥牛犬"    ,
    "Bouvier des Flandres"    :    "Bouvier des Flandres"    ,
    "weasel "    :    "黃鼠狼"    ,
    "miniature poodle "    :    "微型獅子狗"    ,
    "bighorn"    :    "大角羊"    ,
    "fox squirrel"    :    "狐狸松鼠"    ,
    "colobus"    :    "疣猴"    ,
    "tiger cat "    :    "老虎貓"    ,
    "impala"    :    "飛羚"    ,
    "coyote"    :    "土狼"    ,
    "Yorkshire terrier "    :    "約克夏犬"    ,
    "Newfoundland"    :    "紐芬蘭犬"    ,
    "red fox"    :    "紅狐狸"    ,
    "hartebeest "    :    "麋羚"    ,
    "grey fox"    :    "灰狐狸"    ,
    "Pekinese"    :    "北京人"    ,
    "guenon"    :    "guenon"    ,
    "mongoose "    :    "貓鼬"    ,
    "indri"    :    "indri"    ,
    "tiger"    :    "老虎"    ,
    "wild boar"    :    "野豬"    ,
    "zebra "    :    "斑馬"    ,
    "ram"    :    "ram"    ,
    "orangutan"    :    "猩猩"    ,
    "basenji "    :    "購買basenji"    ,
    "leopard"    :    "豹"    ,
    "vizsla"    :    "vizsla"    ,
    "squirrel monkey"    :    "松鼠猴"    ,
    "Siamese cat"    :    "暹羅貓"    ,
    "chimpanzee"    :    "黑猩猩"    ,
    "komondor "    :    "購買komondor"    ,
    "proboscis monkey"    :    "長鼻猴"    ,
    "guinea pig"    :    "豚鼠"    ,
    "white wolf"    :    "白狼"    ,
    "ice bear"    :    "冰熊"    ,
    "gorilla"    :    "大猩猩"    ,
    "ox "    :    "牛"    ,
    "Tibetan mastiff "    :    "藏獒"    ,
    "spider monkey"    :    "蜘蛛猴"    ,
    "Doberman"    :    "杜賓犬"    ,
    "warthog "    :    "疣豬"    ,
    "Arabian camel"    :    "阿拉伯駱駝"    ,
    "siamang"    :    "siamang"    ,
    "golden retriever "    :    "金毛獵犬"    ,
    "Border collie "    :    "邊境牧羊犬"    ,
    "hare "    :    "野兔"    ,
    "boxer "    :    "拳擊手"    ,
    "patas"    :    "帕達斯"    ,
    "baboon "    :    "狒狒"    ,
    "macaque "    :    "獼"    ,
    "capuchin"    :    "卷尾猴"    ,
    "flat-coated retriever "    :    "平坦的獵犬"    ,
    "hog"    :    "豬"    ,
    "Eskimo dog"    :    "愛斯基摩狗"    ,
    "Brittany spaniel "    :    "布列塔尼西班牙獵狗"    ,
    "dial telephone"    :    "撥號電話"    ,
    "maze"    :    "迷宮"    ,
    "Gordon setter "    :    "戈登二傳手"    ,
    "dingo"    :    "dingo"    ,
    "hamster "    :    "倉鼠"    ,
    "Arctic fox"    :    "北極狐"    ,
    "water buffalo"    :    "水牛"    ,
    "American black bear"    :    "美國黑熊"    ,
    "Angora"    :    "安哥拉"    ,
    "bison "    :    "野牛"    ,
    "howler monkey"    :    "吼猴"    ,
    "hippopotamus"    :    "河馬"    ,
    "giant panda"    :    "大熊貓"    ,
    "tabby"    :    "虎斑貓"    ,
    "marmoset "    :    "狨猴"    ,
    "Saint Bernard"    :    "聖伯納德"    ,
    "armadillo "    :    "犰狳"    ,
    "redbone "    :    "redbone"    ,
    "polecat"    :    "貂皮"    ,
    "marmot "    :    "旱獺"    ,
    "gibbon"    :    "長臂猿"    ,
    "llama "    :    "駱駝"    ,
    "wood rabbit"    :    "木兔"    ,
    "lion"    :    "獅子"    ,
    "Irish setter"    :    "愛爾蘭二傳手"    ,
    "dugong"    :    "儒艮"    ,
    "Indian elephant"    :    "印度大象"    ,
    "beaver "    :    "海狸"    ,
    "Madagascar cat"    :    "馬達加斯加貓"    ,
    "Rhodesian ridgeback "    :    "羅得西亞ridgeback"    ,
    "lynx"    :    "l"    ,
    "African hunting dog"    :    "非洲狩獵犬"    ,
    "langur "    :    "葉猴"    ,
    "timber wolf"    :    "狼"    ,
    "cheetah"    :    "獵豹"    ,
    "sloth bear"    :    "懶惰熊"    ,
    "German shepherd"    :    "德國牧羊犬"    ,
    "otter "    :    "獺"    ,
    "koala"    :    "考拉"    ,
    "tusker "    :    "塔斯克"    ,
    "echidna"    :    "針鼴"    ,
    "wallaby"    :    "袋鼠"    ,
    "platypus"    :    "鴨嘴獸"    ,
    "wombat "    :    "袋熊"    ,
    "revolver"    :    "左輪手槍"    ,
    "umbrella "    :    "雨傘"    ,
    "schooner "    :    "大篷車"    ,
    "soccer ball "    :    "足球"    ,
    "accordion"    :    "手風琴"    ,
    "ant"    :    "螞蟻"    ,
    "starfish"    :    "海星"    ,
    "chambered nautilus"    :    "鸚鵡螺"    ,
    "grand piano"    :    "大鋼琴"    ,
    "laptop"    :    "筆記本電腦"    ,
    "strawberry "    :    "草莓"    ,
    "airliner "    :    "客機"    ,
    "warplane"    :    "戰機"    ,
    "airship"    :    "飛艇"    ,
    "balloon "    :    "氣球"    ,
    "space shuttle "    :    "航天飛機"    ,
    "fireboat "    :    "消防艇"    ,
    "gondola "    :    "貢多拉"    ,
    "speedboat "    :    "快艇"    ,
    "lifeboat "    :    "救生艇"    ,
    "canoe "    :    "獨木舟"    ,
    "yawl "    :    "YAWL"    ,
    "catamaran "    :    "雙體船"    ,
    "trimaran "    :    "三體船"    ,
    "container ship"    :    "集裝箱船"    ,
    "liner"    :    "班輪"    ,
    "pirate"    :    "海盜"    ,
    "aircraft carrier"    :    "航母"    ,
    "submarine"    :    "潛艇"    ,
    "wreck "    :    "破壞"    ,
    "half track "    :    "一半的軌道"    ,
    "tank"    :    "坦克"    ,
    "missile "    :    "導彈"    ,
    "bobsled"    :    "雪橇"    ,
    "dogsled"    :    "狗拉雪橇"    ,
    "bicycle-built-for-two"    :    "自行車雙人自行車"    ,
    "mountain bike"    :    "山地自行車"    ,
    "freight car "    :    "貨運車"    ,
    "passenger car"    :    "客車"    ,
    "barrow"    :    "手推車"    ,
    "shopping cart "    :    "購物車"    ,
    "motor scooter"    :    "小型摩托車"    ,
    "forklift "    :    "叉車"    ,
    "electric locomotive "    :    "電力機車"    ,
    "steam locomotive "    :    "蒸汽機車"    ,
    "amphibian"    :    "兩棲類"    ,
    "ambulance "    :    "救護車"    ,
    "beach wagon"    :    "海灘旅行車"    ,
    "cab"    :    "出租車"    ,
    "convertible "    :    "可兌換"    ,
    "jeep"    :    "吉普車"    ,
    "limousine"    :    "豪華轎車"    ,
    "minivan "    :    "麵包車"    ,
    "Model T "    :    "型號T"    ,
    "racer"    :    "賽車手"    ,
    "sports car"    :    "跑車"    ,
    "go-kart "    :    "卡丁車"    ,
    "golfcart"    :    "高爾夫車"    ,
    "moped "    :    "助力車"    ,
    "snowplow"    :    "除雪車"    ,
    "fire engine"    :    "消防車"    ,
    "garbage truck"    :    "垃圾車"    ,
    "pickup"    :    "皮卡"    ,
    "tow truck"    :    "拖車"    ,
    "trailer truck"    :    "拖車"    ,
    "moving van "    :    "搬運車"    ,
    "police van"    :    "警車"    ,
    "recreational vehicle"    :    "休閒車"    ,
    "streetcar"    :    "有軌電車"    ,
    "snowmobile "    :    "雪地車"    ,
    "tractor "    :    "拖拉機"    ,
    "mobile home"    :    "移動房屋"    ,
    "tricycle"    :    "三輪車"    ,
    "unicycle"    :    "獨輪車"    ,
    "horse cart"    :    "馬車"    ,
    "mosquito net "    :    "蚊帳"    ,
    "oxcart "    :    "牛車"    ,
    "bassinet "    :    "搖籃"    ,
    "cradle "    :    "搖籃"    ,
    "crib"    :    "嬰兒床"    ,
    "four-poster "    :    "四柱"    ,
    "bookcase "    :    "書櫃"    ,
    "china cabinet"    :    "中國內閣"    ,
    "medicine chest"    :    "藥箱"    ,
    "chiffonier"    :    "雪紡綢"    ,
    "table lamp "    :    "檯燈"    ,
    "file"    :    "文件"    ,
    "pay-phone"    :    "付費電話"    ,
    "park bench "    :    "公園的長椅上"    ,
    "barber chair "    :    "理髮椅"    ,
    "throne "    :    "王座"    ,
    "folding chair "    :    "折疊椅"    ,
    "rocking chair"    :    "搖椅"    ,
    "studio couch"    :    "工作室沙發"    ,
    "toilet seat "    :    "馬桶座圈"    ,
    "desk "    :    "台"    ,
    "pool table"    :    "台球桌"    ,
    "dining table"    :    "餐桌"    ,
    "entertainment center "    :    "娛樂中心"    ,
    "wardrobe"    :    "衣櫃"    ,
    "Granny Smith "    :    "格蘭尼史密斯"    ,
    "orange "    :    "橙子"    ,
    "lemon "    :    "檸檬"    ,
    "fig "    :    "圖"    ,
    "pineapple"    :    "菠蘿"    ,
    "banana "    :    "香蕉"    ,
    "jackfruit"    :    "菠蘿蜜"    ,
    "custard apple "    :    "南美番荔枝"    ,
    "pomegranate "    :    "石榴"    ,
    "acorn "    :    "橡子"    ,
    "hip"    :    "臀部"    ,
    "ear"    :    "耳朵"    ,
    "rapeseed "    :    "菜子"    ,
    "corn "    :    "玉米"    ,
    "buckeye"    :    "七葉樹"    ,
    "organ"    :    "器官"    ,
    "upright"    :    "直立的鋼琴"    ,
    "chime"    :    "編鐘"    ,
    "drum"    :    "鼓"    ,
    "gong"    :    "龔"    ,
    "maraca "    :    "馬拉卡"    ,
    "marimba"    :    "木琴"    ,
    "steel drum "    :    "鋼鼓"    ,
    "banjo "    :    "班卓琴"    ,
    "cello"    :    "大提琴"    ,
    "lampshade"    :    "燈罩"    ,
    "harp "    :    "豎琴"    ,
    "acoustic guitar "    :    "原聲吉他"    ,
    "electric guitar "    :    "電吉他"    ,
    "cornet"    :    "短號"    ,
    "French horn"    :    "法國號​​角"    ,
    "trombone "    :    "長號"    ,
    "harmonica"    :    "口琴"    ,
    "ocarina"    :    "ocarina"    ,
    "panpipe"    :    "排管"    ,
    "bassoon "    :    "巴鬆管"    ,
    "sax"    :    "薩克斯管"    ,
    "flute"    :    "長笛"    ,
    "daisy "    :    "雛菊"    ,
    "yellow lady's slipper"    :    "黃女士的拖鞋"    ,
    "cliff"    :    "懸崖"    ,
    "valley"    :    "谷"    ,
    "alp "    :    "岳"    ,
    "volcano "    :    "火山"    ,
    "promontory"    :    "海角"    ,
    "sandbar"    :    "沙洲"    ,
    "coral reef "    :    "珊瑚礁"    ,
    "lakeside"    :    "湖畔"    ,
    "seashore"    :    "海濱"    ,
    "geyser "    :    "噴泉"    ,
    "hatchet "    :    "斧頭"    ,
    "cleaver"    :    "切肉刀"    ,
    "letter opener"    :    "開信刀"    ,
    "plane"    :    "飛機"    ,
    "power drill "    :    "電鑽"    ,
    "lawn mower"    :    "割草機"    ,
    "hammer "    :    "錘子"    ,
    "corkscrew"    :    "開瓶器"    ,
    "can opener"    :    "開罐器"    ,
    "plunger"    :    "柱塞"    ,
    "screwdriver "    :    "螺絲刀"    ,
    "shovel "    :    "鏟"    ,
    "plow"    :    "犁"    ,
    "chain saw"    :    "鏈鋸"    ,
    "cock "    :    "公雞"    ,
    "hen "    :    "母雞"    ,
    "ostrich"    :    "鴕鳥"    ,
    "brambling"    :    "bra"    ,
    "goldfinch"    :    "金翅雀"    ,
    "house finch"    :    "房子雀"    ,
    "junco"    :    "junco"    ,
    "indigo bunting"    :    "靛藍旗"    ,
    "robin"    :    "羅賓"    ,
    "bulbul "    :    "夜鶯"    ,
    "jay "    :    "松鴉"    ,
    "magpie "    :    "鵲"    ,
    "chickadee "    :    "山雀"    ,
    "water ouzel"    :    "水ouzel"    ,
    "kite "    :    "風箏"    ,
    "bald eagle"    :    "禿鷹"    ,
    "vulture "    :    "禿鷲"    ,
    "great grey owl"    :    "偉大的灰色貓頭鷹"    ,
    "black grouse "    :    "黑松雞"    ,
    "ptarmigan "    :    "鷓鴣"    ,
    "ruffed grouse"    :    "松雞松雞"    ,
    "prairie chicken"    :    "草原雞"    ,
    "peacock "    :    "孔雀"    ,
    "quail "    :    "鵪鶉"    ,
    "partridge "    :    "鷓鴣"    ,
    "African grey"    :    "非洲灰色"    ,
    "macaw "    :    "金剛鸚鵡"    ,
    "sulphur-crested cockatoo"    :    "硫磺鳳頭鸚鵡"    ,
    "lorikeet "    :    "吸蜜"    ,
    "coucal "    :    "褐翅鴉鵑"    ,
    "bee eater "    :    "蜜蜂食者"    ,
    "hornbill "    :    "犀鳥"    ,
    "hummingbird "    :    "蜂鳥"    ,
    "jacamar "    :    "jacamar"    ,
    "toucan "    :    "巨嘴鳥"    ,
    "drake "    :    "鴨"    ,
    "red-breasted merganser"    :    "紅胸秋沙鴨"    ,
    "goose "    :    "鵝"    ,
    "black swan"    :    "黑天鵝"    ,
    "white stork"    :    "白鸛"    ,
    "black stork"    :    "黑鸛"    ,
    "spoonbill "    :    "鷺"    ,
    "flamingo "    :    "火烈鳥"    ,
    "American egret"    :    "美國白鷺"    ,
    "little blue heron"    :    "小藍鷺"    ,
    "bittern "    :    "鹵水"    ,
    "limpkin"    :    "limpkin"    ,
    "American coot"    :    "美國白骨雞"    ,
    "bustard "    :    "鴇鳥"    ,
    "ruddy turnstone"    :    "紅潤的翻石"    ,
    "red-backed sandpiper"    :    "紅背鷸"    ,
    "redshank"    :    "赤腳鷸"    ,
    "dowitcher "    :    "dowitcher"    ,
    "oystercatcher"    :    "蠣鷸"    ,
    "European gallinule"    :    "歐洲gallinule"    ,
    "pelican "    :    "鵜"    ,
    "king penguin"    :    "王企鵝"    ,
    "albatross"    :    "信天翁"    ,
    "great white shark"    :    "大白鯊"    ,
    "tiger shark"    :    "虎鯊"    ,
    "hammerhead"    :    "鎚頭"    ,
    "electric ray"    :    "電光線"    ,
    "stingray "    :    "黃貂魚"    ,
    "barracouta"    :    "barracouta"    ,
    "coho"    :    "coho"    ,
    "tench"    :    "丁香"    ,
    "goldfish"    :    "金魚"    ,
    "eel "    :    "鰻魚"    ,
    "rock beauty"    :    "岩石之美"    ,
    "anemone fish "    :    "海葵魚"    ,
    "lionfish "    :    "獅子魚"    ,
    "puffer"    :    "河豚"    ,
    "sturgeon "    :    "鱘"    ,
    "gar"    :    "gar"    ,
    "loggerhead"    :    "log"    ,
    "mud turtle "    :    "泥龜"    ,
    "terrapin "    :    "龜鱉"    ,
    "box turtle"    :    "箱龜"    ,
    "banded gecko "    :    "帶壁虎"    ,
    "common iguana"    :    "共同的鬣鱗蜥"    ,
    "American chameleon"    :    "美國變色龍"    ,
    "whiptail"    :    "鞭尾"    ,
    "agama "    :    "阿含"    ,
    "frilled lizard"    :    "frilled蜥蜴"    ,
    "alligator lizard "    :    "鱷魚蜥蜴"    ,
    "Gila monster"    :    "吉拉怪物"    ,
    "green lizard"    :    "綠蜥蜴"    ,
    "African chameleon"    :    "非洲變色龍"    ,
    "Komodo dragon"    :    "科莫多巨蜥"    ,
    "triceratops "    :    "三角龍"    ,
    "African crocodile"    :    "非洲鱷魚"    ,
    "American alligator"    :    "美國短吻鱷"    ,
    "thunder snake"    :    "雷蛇"    ,
    "ringneck snake"    :    "戒指蛇"    ,
    "hognose snake"    :    "豬鼻蛇"    ,
    "green snake"    :    "青蛇"    ,
    "king snake"    :    "王蛇"    ,
    "garter snake"    :    "襪帶蛇"    ,
    "water snake "    :    "水蛇"    ,
    "vine snake "    :    "藤蛇"    ,
    "night snake"    :    "夜蛇"    ,
    "boa constrictor"    :    "大蟒"    ,
    "rock python"    :    "岩石蟒蛇"    ,
    "Indian cobra"    :    "印度眼鏡蛇"    ,
    "green mamba "    :    "綠曼巴"    ,
    "sea snake "    :    "海蛇"    ,
    "horned viper"    :    "角v蛇"    ,
    "stone wall "    :    "石牆"    ,
    "sidewinder"    :    "響尾蛇"    ,
    "European fire salamander"    :    "歐洲火蠑螈"    ,
    "common newt"    :    "常見的蠑螈"    ,
    "eft "    :    "鯢"    ,
    "spotted salamander"    :    "斑點蠑螈"    ,
    "axolotl"    :    "ax"    ,
    "bullfrog"    :    "牛蛙"    ,
    "tree frog"    :    "樹蛙"    ,
    "tailed frog"    :    "被盯梢的青蛙"    ,
    "whistle "    :    "哨"    ,
    "wing "    :    "翅膀"    ,
    "paintbrush "    :    "畫筆"    ,
    "oxygen mask "    :    "氧氣面罩"    ,
    "snorkel "    :    "浮潛"    ,
    "loudspeaker"    :    "揚聲器"    ,
    "microphone"    :    "麥克風"    ,
    "screen"    :    "屏幕"    ,
    "mouse"    :    "鼠標"    ,
    "electric fan"    :    "電風扇"    ,
    "oil filter "    :    "機油濾清器"    ,
    "strainer "    :    "過濾器"    ,
    "space heater "    :    "小型供暖器"    ,
    "stove "    :    "火爐"    ,
    "guillotine "    :    "斷頭台"    ,
    "barometer "    :    "晴雨表"    ,
    "rule"    :    "規則"    ,
    "odometer"    :    "里程表"    ,
    "scale"    :    "秤"    ,
    "analog clock "    :    "模擬時鐘"    ,
    "digital clock "    :    "數碼時鐘"    ,
    "wall clock "    :    "掛鐘"    ,
    "hourglass "    :    "滴漏"    ,
    "sundial "    :    "晷"    ,
    "parking meter "    :    "停車收費表"    ,
    "stopwatch"    :    "秒錶"    ,
    "digital watch "    :    "數字手錶"    ,
    "stethoscope "    :    "聽筒"    ,
    "syringe "    :    "注射器"    ,
    "magnetic compass "    :    "磁羅盤"    ,
    "binoculars"    :    "雙筒望遠鏡"    ,
    "projector "    :    "放映機"    ,
    "sunglasses"    :    "太陽鏡"    ,
    "loupe"    :    "放大鏡"    ,
    "radio telescope"    :    "射電望遠鏡"    ,
    "bow "    :    "弓"    ,
    "cannon "    :    "大砲"    ,
    "assault rifle"    :    "突擊步槍"    ,
    "rifle "    :    "步槍"    ,
    "projectile"    :    "射彈"    ,
    "computer keyboard"    :    "電腦鍵盤"    ,
    "typewriter keyboard "    :    "打字機鍵盤"    ,
    "crane "    :    "起重機"    ,
    "lighter"    :    "點火器"    ,
    "abacus "    :    "算盤"    ,
    "cash machine"    :    "自動取款機"    ,
    "slide rule"    :    "滑尺"    ,
    "desktop computer"    :    "台式電腦"    ,
    "hand-held computer"    :    "手持式電腦"    ,
    "notebook"    :    "筆記本"    ,
    "padlock "    :    "掛鎖"    ,
    "harvester"    :    "收割機"    ,
    "thresher"    :    "打穀機"    ,
    "printer "    :    "打印機"    ,
    "slot"    :    "插槽"    ,
    "vending machine "    :    "售貨機"    ,
    "sewing machine "    :    "縫紉機"    ,
    "joystick "    :    "操縱桿"    ,
    "switch"    :    "開關"    ,
    "hook"    :    "鉤"    ,
    "car wheel "    :    "車輪"    ,
    "paddlewheel"    :    "槳輪"    ,
    "pinwheel "    :    "風車"    ,
    "potter's wheel "    :    "陶輪"    ,
    "gas pump"    :    "燃氣泵"    ,
    "carousel"    :    "旋轉木馬"    ,
    "swing "    :    "搖擺"    ,
    "reel "    :    "捲軸"    ,
    "radiator "    :    "散熱器"    ,
    "puck"    :    "冰球"    ,
    "hard disc"    :    "硬盤"    ,
    "sunglass "    :    "太陽鏡"    ,
    "pick"    :    "撥"    ,
    "car mirror "    :    "車鏡"    ,
    "solar dish"    :    "太陽能碟"    ,
    "remote control"    :    "遙控器"    ,
    "disk brake"    :    "盤式製動器"    ,
    "buckle "    :    "扣"    ,
    "hair slide "    :    "頭髮幻燈片"    ,
    "knot "    :    "結"    ,
    "combination lock "    :    "密碼鎖"    ,
    "web site"    :    "網站"    ,
    "nail "    :    "釘"    ,
    "safety pin "    :    "安全別針"    ,
    "screw "    :    "擰"    ,
    "muzzle "    :    "槍口"    ,
    "seat belt"    :    "安全帶"    ,
    "ski "    :    "滑雪"    ,
    "candle"    :    "蠟燭"    ,
    "jack-o'-lantern "    :    "鬼火"    ,
    "spotlight"    :    "聚光燈"    ,
    "torch "    :    "火炬"    ,
    "neck brace "    :    "頸托"    ,
    "pier "    :    "碼頭"    ,
    "tripod "    :    "鼎"    ,
    "maypole "    :    "五朔節花柱"    ,
    "hand blower"    :    "手吹風機"    ,
    "mousetrap "    :    "捕鼠器"    ,
    "spider web"    :    "蜘蛛網"    ,
    "trilobite "    :    "三葉蟲"    ,
    "harvestman"    :    "收割者"    ,
    "scorpion "    :    "蠍"    ,
    "black and gold garden spider"    :    "黑色和金色的花園蜘蛛"    ,
    "barn spider"    :    "穀倉蜘蛛"    ,
    "garden spider"    :    "花園蜘蛛"    ,
    "black widow"    :    "黑寡婦"    ,
    "tarantula "    :    "狼蛛"    ,
    "wolf spider"    :    "狼蛛"    ,
    "tick "    :    "蜱"    ,
    "centipede "    :    "蜈"    ,
    "isopod "    :    "等足"    ,
    "Dungeness crab"    :    "太平洋蟹"    ,
    "rock crab"    :    "岩蟹"    ,
    "fiddler crab "    :    "提琴手螃蟹"    ,
    "king crab"    :    "帝王蟹"    ,
    "American lobster"    :    "美國龍蝦"    ,
    "spiny lobster"    :    "龍蝦"    ,
    "crayfish"    :    "小龍蝦"    ,
    "hermit crab "    :    "寄居蟹"    ,
    "tiger beetle "    :    "老虎甲蟲"    ,
    "ladybug"    :    "瓢蟲"    ,
    "ground beetle"    :    "地甲蟲"    ,
    "long-horned beetle"    :    "長角甲蟲"    ,
    "leaf beetle"    :    "葉甲蟲"    ,
    "dung beetle "    :    "糞甲蟲"    ,
    "rhinoceros beetle "    :    "犀牛甲蟲"    ,
    "weevil "    :    "象鼻蟲"    ,
    "fly "    :    "飛"    ,
    "bee "    :    "蜜蜂"    ,
    "grasshopper"    :    "蚱蜢"    ,
    "cricket "    :    "蟋蟀"    ,
    "walking stick"    :    "手杖"    ,
    "cockroach"    :    "蟑螂"    ,
    "mantis"    :    "螳螂"    ,
    "cicada"    :    "蟬"    ,
    "leafhopper "    :    "葉蟬"    ,
    "lacewing"    :    "草"    ,
    "dragonfly"    :    "蜻蜓"    ,
    "damselfly "    :    "豆娘"    ,
    "admiral "    :    "上將"    ,
    "ringlet"    :    "小環"    ,
    "monarch"    :    "君主"    ,
    "cabbage butterfly "    :    "菜粉蝶"    ,
    "sulphur butterfly"    :    "硫磺蝴蝶"    ,
    "lycaenid"    :    "lycaenid"    ,
    "jellyfish "    :    "海蜇"    ,
    "sea anemone"    :    "海葵"    ,
    "brain coral "    :    "腦珊瑚"    ,
    "flatworm"    :    "扁蟲"    ,
    "nematode"    :    "線蟲"    ,
    "conch "    :    "海螺"    ,
    "snail "    :    "蝸牛"    ,
    "slug "    :    "金屬塊"    ,
    "sea slug"    :    "海參"    ,
    "chiton"    :    "chiton"    ,
    "sea urchin "    :    "海膽"    ,
    "sea cucumber"    :    "海參"    ,
    "iron"    :    "鐵"    ,
    "espresso maker "    :    "濃縮咖啡機"    ,
    "microwave"    :    "微波爐"    ,
    "Dutch oven "    :    "荷蘭烤箱"    ,
    "rotisserie "    :    "烤肉店"    ,
    "toaster "    :    "烤麵包機"    ,
    "waffle iron "    :    "華夫餅鐵"    ,
    "vacuum"    :    "真空"    ,
    "dishwasher"    :    "洗碗機"    ,
    "refrigerator"    :    "冰箱"    ,
    "washer"    :    "洗衣機"    ,
    "Crock Pot "    :    "缸罐"    ,
    "frying pan"    :    "煎鍋"    ,
    "wok "    :    "炒鍋"    ,
    "caldron"    :    "大鍋"    ,
    "coffeepot "    :    "咖啡壺"    ,
    "teapot "    :    "茶壺"    ,
    "spatula "    :    "抹刀"    ,
    "altar "    :    "壇"    ,
    "triumphal arch "    :    "凱旋門"    ,
    "patio"    :    "庭院"    ,
    "steel arch bridge "    :    "鋼拱橋"    ,
    "suspension bridge "    :    "吊橋"    ,
    "viaduct "    :    "高架橋"    ,
    "barn "    :    "穀倉"    ,
    "greenhouse"    :    "溫室"    ,
    "palace "    :    "宮"    ,
    "monastery "    :    "修道院"    ,
    "library "    :    "圖書館"    ,
    "apiary"    :    "蜂房"    ,
    "boathouse "    :    "船屋"    ,
    "church"    :    "教堂"    ,
    "mosque "    :    "清真寺"    ,
    "stupa"    :    "佛塔"    ,
    "planetarium "    :    "天文館"    ,
    "restaurant"    :    "餐廳"    ,
    "cinema"    :    "電影院"    ,
    "home theater"    :    "家庭影院"    ,
    "lumbermill"    :    "伐木場"    ,
    "coil"    :    "線圈"    ,
    "obelisk "    :    "方尖碑"    ,
    "totem pole "    :    "圖騰柱"    ,
    "castle "    :    "城堡"    ,
    "prison"    :    "監獄"    ,
    "grocery store"    :    "雜貨店"    ,
    "bakery"    :    "麵包店"    ,
    "barbershop "    :    "理髮店"    ,
    "bookshop"    :    "書店"    ,
    "butcher shop"    :    "肉店"    ,
    "confectionery"    :    "糖果店"    ,
    "shoe shop"    :    "鞋店"    ,
    "tobacco shop"    :    "煙草商店"    ,
    "toyshop "    :    "玩具店"    ,
    "fountain "    :    "噴泉"    ,
    "cliff dwelling "    :    "懸崖住宅"    ,
    "yurt "    :    "蒙古包"    ,
    "dock"    :    "碼頭"    ,
    "brass"    :    "黃銅"    ,
    "megalith"    :    "巨石"    ,
    "bannister"    :    "欄杆"    ,
    "breakwater"    :    "防波堤"    ,
    "dam"    :    "大壩"    ,
    "chainlink fence "    :    "chainlink圍欄"    ,
    "picket fence"    :    "柵欄"    ,
    "worm fence"    :    "蠕蟲柵欄"    ,
    "diamondback"    :    "菱紋背響尾蛇"    ,
    "grille"    :    "格柵"    ,
    "sliding door "    :    "滑行門"    ,
    "turnstile "    :    "旋轉門"    ,
    "mountain tent "    :    "山帳篷"    ,
    "scoreboard "    :    "記分牌"    ,
    "honeycomb "    :    "蜂窩"    ,
    "plate rack "    :    "盤架"    ,
    "pedestal"    :    "底座"    ,
    "beacon"    :    "燈塔"    ,
    "leatherback turtle"    :    "棱皮龜"    ,
    "mashed potato "    :    "土豆泥"    ,
    "bell pepper "    :    "燈籠椒"    ,
    "head cabbage "    :    "捲心菜頭"    ,
    "broccoli "    :    "西蘭花"    ,
    "cauliflower "    :    "菜花"    ,
    "zucchini"    :    "西葫蘆"    ,
    "spaghetti squash "    :    "意粉南瓜"    ,
    "acorn squash "    :    "橡子壁球"    ,
    "butternut squash "    :    "冬南瓜"    ,
    "cucumber"    :    "黃瓜"    ,
    "artichoke"    :    "朝鮮薊"    ,
    "cardoon "    :    "刺苞菜薊"    ,
    "mushroom "    :    "蘑菇"    ,
    "shower curtain "    :    "浴簾"    ,
    "jean"    :    "牛仔褲"    ,
    "carton "    :    "紙板箱"    ,
    "handkerchief"    :    "手帕"    ,
    "sandal "    :    "檀香"    ,
    "ashcan"    :    "垃圾箱"    ,
    "safe "    :    "安全"    ,
    "plate "    :    "盤子"    ,
    "necklace "    :    "項鍊"    ,
    "croquet ball "    :    "槌球"    ,
    "fur coat "    :    "皮毛大衣"    ,
    "thimble "    :    "頂針"    ,
    "pajama"    :    "睡衣"    ,
    "running shoe "    :    "跑鞋"    ,
    "oboe"    :    "雙簧管"    ,
    "cocktail shaker "    :    "雞尾酒調酒器"    ,
    "chest "    :    "胸部"    ,
    "manhole cover "    :    "井蓋"    ,
    "modem "    :    "調製解調器"    ,
    "tub"    :    "浴缸"    ,
    "tray "    :    "托盤"    ,
    "balance beam"    :    "平衡木"    ,
    "bagel"    :    "百吉餅"    ,
    "violin"    :    "小提琴"    ,
    "prayer rug"    :    "祈禱地毯"    ,
    "kimono "    :    "和服"    ,
    "hot pot"    :    "火鍋"    ,
    "whiskey jug "    :    "威士忌壺"    ,
    "knee pad "    :    "護膝"    ,
    "book jacket"    :    "書夾"    ,
    "spindle "    :    "紡錘"    ,
    "ski mask "    :    "滑雪面罩"    ,
    "beer bottle "    :    "啤酒瓶"    ,
    "crash helmet "    :    "防撞頭盔"    ,
    "bottlecap "    :    "瓶蓋"    ,
    "tile roof "    :    "瓦屋頂"    ,
    "mask "    :    "面具"    ,
    "maillot "    :    "運動衣"    ,
    "Petri dish "    :    "培養皿"    ,
    "football helmet "    :    "橄欖球頭盔"    ,
    "bathing cap"    :    "泳帽"    ,
    "teddy"    :    "泰迪熊"    ,
    "holster "    :    "皮套"    ,
    "pop bottle"    :    "流行音樂瓶"    ,
    "photocopier "    :    "複印機"    ,
    "vestment "    :    "法衣"    ,
    "crossword puzzle"    :    "填字遊戲"    ,
    "golf ball "    :    "高爾夫球"    ,
    "trifle "    :    "瑣事"    ,
    "suit"    :    "西裝"    ,
    "water tower "    :    "水塔"    ,
    "feather boa"    :    "羽毛蟒蛇"    ,
    "cloak "    :    "披風"    ,
    "red wine "    :    "紅酒"    ,
    "drumstick "    :    "鼓槌"    ,
    "shield"    :    "盾牌"    ,
    "Christmas stocking "    :    "聖誕節放養"    ,
    "hoopskirt"    :    "箍"    ,
    "menu "    :    "菜單"    ,
    "stage "    :    "階段"    ,
    "bonnet"    :    "發動機罩"    ,
    "meat loaf"    :    "肉糕"    ,
    "baseball "    :    "棒球"    ,
    "face powder "    :    "香粉"    ,
    "scabbard "    :    "刀鞘"    ,
    "sunscreen"    :    "防曬霜"    ,
    "beer glass "    :    "啤酒杯"    ,
    "hen-of-the-woods"    :    "樹林裡的母雞"    ,
    "guacamole "    :    "鱷梨"    ,
    "wool"    :    "羊毛"    ,
    "hay "    :    "乾草"    ,
    "bow tie"    :    "領結"    ,
    "mailbag"    :    "郵袋"    ,
    "water jug "    :    "水壺"    ,
    "bucket"    :    "桶"    ,
    "dishrag"    :    "洗碗布"    ,
    "soup bowl "    :    "湯碗"    ,
    "eggnog "    :    "蛋酒"    ,
    "mortar "    :    "砂漿"    ,
    "trench coat "    :    "風衣"    ,
    "paddle"    :    "槳"    ,
    "chain "    :    "鏈"    ,
    "swab"    :    "拭子"    ,
    "mixing bowl "    :    "攪拌碗"    ,
    "potpie "    :    "鍋餅"    ,
    "wine bottle "    :    "葡萄酒瓶"    ,
    "shoji "    :    "商事"    ,
    "bulletproof vest "    :    "防彈背心"    ,
    "drilling platform"    :    "鑽井平台"    ,
    "binder"    :    "粘合劑"    ,
    "cardigan "    :    "羊毛衣"    ,
    "sweatshirt "    :    "運動衫"    ,
    "pot"    :    "鍋"    ,
    "birdhouse "    :    "鳥巢"    ,
    "jinrikisha"    :    "jinrikisha"    ,
    "hamper "    :    "阻礙"    ,
    "ping-pong ball "    :    "乒乓球"    ,
    "pencil box"    :    "鉛筆盒"    ,
    "consomme "    :    "清湯"    ,
    "apron "    :    "圍裙"    ,
    "punching bag"    :    "拳擊袋"    ,
    "backpack"    :    "背包"    ,
    "groom"    :    "新郎"    ,
    "bearskin"    :    "熊皮"    ,
    "pencil sharpener "    :    "卷筆刀"    ,
    "broom "    :    "掃帚"    ,
    "abaya "    :    "阿巴亞"    ,
    "mortarboard "    :    "砂漿板"    ,
    "poncho "    :    "雨披"    ,
    "crutch "    :    "拐杖"    ,
    "Polaroid camera"    :    "寶麗來相機"    ,
    "space bar "    :    "空間酒吧"    ,
    "cup "    :    "杯子"    ,
    "racket"    :    "球拍"    ,
    "traffic light"    :    "交通燈"    ,
    "quill"    :    "羽毛筆"    ,
    "radio"    :    "收音機"    ,
    "snow leopard"    :    "雪豹"    ,
    "dough "    :    "麵團"    ,
    "cuirass "    :    "胸甲"    ,
    "military uniform "    :    "軍裝"    ,
    "lipstick"    :    "口紅"    ,
    "shower cap "    :    "浴帽"    ,
    "monitor "    :    "監控"    ,
    "oscilloscope"    :    "示波器"    ,
    "mitten "    :    "手套"    ,
    "brassiere"    :    "胸罩"    ,
    "French loaf "    :    "法國麵包"    ,
    "vase "    :    "花瓶"    ,
    "milk can "    :    "牛奶可以"    ,
    "rugby ball "    :    "橄欖球"    ,
    "paper towel "    :    "紙巾"    ,
    "earthstar "    :    "earthstar"    ,
    "envelope "    :    "信封"    ,
    "miniskirt"    :    "迷你裙"    ,
    "cowboy hat"    :    "牛仔帽"    ,
    "trolleybus"    :    "無軌電車"    ,
    "perfume"    :    "香水"    ,
    "bathtub"    :    "浴缸"    ,
    "hotdog"    :    "熱狗"    ,
    "coral fungus "    :    "珊瑚菌"    ,
    "bullet train"    :    "子彈頭列車"    ,
    "pillow "    :    "枕頭"    ,
    "toilet tissue"    :    "衛生紙"    ,
    "cassette "    :    "暗盒"    ,
    "carpenter's kit"    :    "木匠工具包"    ,
    "ladle "    :    "瓢"    ,
    "stinkhorn"    :    "stinkhorn"    ,
    "lotion "    :    "洗劑"    ,
    "hair spray "    :    "髮膠"    ,
    "academic gown"    :    "學院長袍"    ,
    "dome "    :    "拱頂"    ,
    "crate "    :    "箱"    ,
    "wig "    :    "假髮"    ,
    "burrito "    :    "捲餅"    ,
    "pill bottle "    :    "藥瓶"    ,
    "chain mail"    :    "連鎖郵件"    ,
    "theater curtain"    :    "劇院幕布"    ,
    "window shade "    :    "窗簾"    ,
    "barrel"    :    "桶"    ,
    "washbasin"    :    "洗臉盆"    ,
    "ballpoint"    :    "圓珠筆"    ,
    "basketball "    :    "籃球"    ,
    "bath towel "    :    "浴巾"    ,
    "cowboy boot "    :    "牛仔靴"    ,
    "gown "    :    "袍"    ,
    "window screen "    :    "窗紗"    ,
    "agaric "    :    "傘菌"    ,
    "standard poodle "    :    "標準貴賓犬"    ,
    "cellular telephone"    :    "手機"    ,
    "nipple "    :    "乳頭"    ,
    "barbell "    :    "槓鈴"    ,
    "mailbox"    :    "郵箱"    ,
    "lab coat"    :    "實驗室外套"    ,
    "fire screen"    :    "防火屏"    ,
    "minibus "    :    "小巴"    ,
    "packet "    :    "包"    ,
    "brown bear"    :    "棕熊"    ,
    "pole "    :    "極"    ,
    "horizontal bar"    :    "單槓"    ,
    "sombrero "    :    "寬邊帽"    ,
    "pickelhaube "    :    "釘盔"    ,
    "rain barrel "    :    "雨桶"    ,
    "wallet"    :    "錢包"    ,
    "cassette player "    :    "卡帶機"    ,
    "comic book "    :    "漫畫書"    ,
    "piggy bank"    :    "存錢罐"    ,
    "street sign "    :    "街道路標"    ,
    "bell cote"    :    "貝爾棚"    ,
    "fountain pen "    :    "鋼筆"    ,
    "Windsor tie "    :    "溫莎領帶"    ,
    "volleyball "    :    "排球"    ,
    "overskirt "    :    "罩裙"    ,
    "sarong "    :    "紗籠"    ,
    "purse "    :    "錢包"    ,
    "bolo tie"    :    "bolo tie"    ,
    "bib "    :    "圍兜"    ,
    "parachute"    :    "降落傘"    ,
    "sleeping bag "    :    "睡袋"    ,
    "television"    :    "電視"    ,
    "swimming trunks"    :    "游泳褲"    ,
    "measuring cup "    :    "量杯"    ,
    "espresso "    :    "濃咖啡"    ,
    "pizza"    :    "比薩餅"    ,
    "breastplate"    :    "胸甲"    ,
    "shopping basket "    :    "購物籃"    ,
    "wooden spoon "    :    "木勺子"    ,
    "saltshaker"    :    "鹽瓶"    ,
    "chocolate sauce"    :    "巧克力醬"    ,
    "ballplayer"    :    "棒球運動員"    ,
    "goblet "    :    "高腳杯"    ,
    "gyromitra "    :    "gyromitra"    ,
    "stretcher "    :    "擔架"    ,
    "water bottle "    :    "水瓶"    ,
    "skunk"    :    "臭鼬"    ,
    "soap dispenser "    :    "皂液器"    ,
    "jersey"    :    "球衣"    ,
    "school bus "    :    "校車"    ,
    "jigsaw puzzle "    :    "拼圖遊戲"    ,
    "plastic bag "    :    "塑料袋"    ,
    "reflex camera "    :    "反光照相機"    ,
    "diaper"    :    "尿布"    ,
    "Band Aid "    :    "創可貼"    ,
    "ice lolly"    :    "冰棍"    ,
    "velvet "    :    "絲絨"    ,
    "tennis ball "    :    "網球"    ,
    "gasmask"    :    "防毒面具"    ,
    "doormat"    :    "門墊"    ,
    "Loafer "    :    "浪子"    ,
    "ice cream"    :    "冰淇淋"    ,
    "pretzel "    :    "椒鹽捲餅"    ,
    "quilt"    :    "被子"    ,
    "maillot"    :    "maillot"    ,
    "tape player "    :    "磁帶播放器"    ,
    "clog"    :    "堵塞"    ,
    "iPod "    :    "iPod的"    ,
    "bolete "    :    "牛肝菌"    ,
    "meerkat"    :    "貓鼬"    ,
    "scuba diver "    :    "潛水員"    ,
    "pitcher"    :    "投手"    ,
    "matchstick "    :    "火柴"    ,
    "bikini"    :    "比基尼"    ,
    "sock "    :    "襪子"    ,
    "CD player "    :    "光碟播放器"    ,
    "lens cap"    :    "鏡頭蓋"    ,
    "thatch"    :    "茅草屋頂"    ,
    "vault "    :    "拱頂"    ,
    "beaker "    :    "燒杯"    ,
    "bubble "    :    "泡沫"    ,
    "cheeseburger "    :    "乳酪漢堡"    ,
    "parallel bars"    :    "雙槓"    ,
    "flagpole"    :    "旗桿"    ,
    "coffee mug "    :    "咖啡杯"    ,
    "rubber eraser"    :    "橡皮橡皮"    ,
    "stole "    :    "偷了"    ,
    "carbonara "    :    "培根蛋面"    ,
    "dumbbell "    :    "啞鈴"
]
